### ISSUE TITLE
dxx doesn't work on cpus, which don't support unaligned memory access

### ISSUE THREAD

**Issue by s-macke** [dxx-rebirth/dxx-rebirth#10]
For my Openrisc emulator https://github.com/s-macke/jor1k I wanted to compile dxx. But unfortunately
dxx uses a lot of unaligned memory accesses, which don't work currently on Openrisc cpus. For example pointers to packed structures.
Would it be a big problem to get rid of all those unaligned memory access. I can give you the places step by step where it happens.

**Comment by vLKp** [comment]
@s-macke: could you address the questions posted Sep 2014 and Dec 2014 in this ticket?  While I would like to eliminate misaligned accesses, I expect such an elimination to be a very large project.

**Comment by vLKp** [comment]
No response from original reporter for more than 2 years.  Closing.

OP: if this remains an issue when you define the C preprocessor symbol `DXX_WORDS_NEED_ALIGNMENT`, please reopen.  You can set this symbol by including it in your `$CPPFLAGS` or by passing the SConf option `words_need_alignment=1`.  It is automatically enabled for Raspberry Pi targets.  All other targets default to off.
