### ISSUE TITLE
Fix ships "glancing" around

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#101]
Currently ships in multiplayer appear to look down and back up pretty often. I believe this has something to do with autoleveling? (Someone with more info, please add it).

**Comment by zicodxx** [comment]
This is probably related to the player ships have auto levelling enabled client side so the local physics try to level the ship despite the positional data received by the client. I am not sure if the wiggle flag is also set - which could cause a similar issue.

**Comment by Mako88** [comment]
This may have been fixed...I didn't notice it while testing the other day. I'll test some more, specifically looking for this though.

**Comment by zicodxx** [comment]
I think this depends on the Autolevel setting. I think all remote player ships get the Autolevel flag. Then if the actual player has this setting enabled, it will look fine - but if off, you may see a slight jitter.

**Comment by Mako88** [comment]
After more testing, with and without autolevel, I'm not seeing this bug anymore. Closing.
