### ISSUE TITLE
Add mouse overrun buffer

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#105]
Basically this adds a buffer so that if the mouse is moved farther than the ship is able to turn, the extra movement is "saved" and applied to the ship after the mouse has stopped moving. It adds a slider to set how long the buffer should be.

Here's the Retro pull request for reference: https://github.com/CDarrow/DXX-Retro/pull/56

**Comment by vLKp** [comment]
@zicodxx: do you want to add a UI to the patch I'd sent you for this or should I take it?

**Comment by zicodxx** [comment]
I am going to patch this in the following days. The draft you sent me looks like all we need and I can at least take care of the UI stuff. :)

**Comment by zicodxx** [comment]
Now added in d3660207d2b11d3b05bfec2d13219bbfe27662bb.
