### ISSUE TITLE
Secluded Spawns

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#108]
Currently the spawn point you are given is entirely random. This causes spawns in VERY inconvenient locations sometimes, often resulting in spawn-kills and the like.

There are quite a few people in the community who would appreciate the option to force spawns to happen at the spawn point the farthest distance from any other ship. (Basically when the person hits a button to respawn, the game would check the distance between each ship and the spawn points. Whichever spawn point is the farthest away from any other ship is the one that the player will spawn at).

This would be a host-settable option.

**Comment by vLKp** [comment]
Implemented in fe360b18e3bc797b1ad16d69d436487377def431.
