### ISSUE TITLE
-debug (and possibly -verbose) no longer working...

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#110]
The -debug option no longer makes the game print out debug statements (I'm not sure if -verbose is working, because -debug isn't).

**Comment by vLKp** [comment]
`-debug` works fine for me in 2a62fa7d7817b50f0ba3bf2f1c1282e908e956ea.  I get quite a bit of console spew.

`-verbose` is less verbose than `-debug`.

**Comment by Mako88** [comment]
This may only happen when compiled with debug=1.

**Comment by vLKp** [comment]
I tested it using a debug=1 build for the previous comment.  It works fine.  If you are still seeing problems, please indicate the commit you tested, the `scons` command you used to build it, and the command line you passed to Rebirth.

**Comment by vLKp** [comment]
I cannot reproduce this.  Original reporter is unavailable.  Closing as INVALID.
