### ISSUE TITLE
Fullscreen HUD misalignment of secondary weapon info

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#112]
When playing in the Fullscreen HUD (no cockpit or statusbar), the secondary weapon info does not seem to be right-aligned properly and tends to go offscreen.

**Comment by vLKp** [comment]
Confirmed.  Applies to "Standard HUD", but does not apply to "Alternate HUD \#1" (which lists all the weapons, but has no labels) or "Alternate HUD \#2" (like \#1, but moves everything to the center of the screen).

**Comment by vLKp** [comment]
2d70cd65ea5e96922ef73cb3f609afbd33881a4b cached too aggressively, so it reused a value from the primary weapon instead of the computed value for the secondary.  Fixed in 268f9649afce7d2510a9a11a18762f502cda5d53.
