### ISSUE TITLE
scanline.cpp Compiler errors on Mac OS X

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#120]
Hi team,

I tried compiling on Mac OS X 10.10.5 using SCons 2.3.4 directly and get this output:
DXX-Archive.3: compiling on darwin for darwin into .
DXX-Archive.3: LittleEndian machine detected
DXX-Archive.3: building with OpenGL
DXX-Archive.3: checking whether C++ compiler and linker work...yes
DXX-Archive.3: checking for usable library physfs...yes
DXX-Archive.3: checking SDL pkg-config sdl
DXX-Archive.3: no usable pkg-config 'pkg-config' found in $PATH
DXX-Archive.3: skipping SDL pkg-config
DXX-Archive.3: checking for usable library SDL...yes
DXX-Archive.3: checking whether to use SDL_mixer...yes
DXX-Archive.3: checking SDL_mixer pkg-config SDL_mixer
DXX-Archive.3: skipping SDL_mixer pkg-config
DXX-Archive.3: checking for usable library SDL_mixer...yes
DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++14...yes
DXX-Archive.3: checking whether C++ compiler warns for {} initialization...no
DXX-Archive.3: checking whether compiler optimizes function \__attribute\__((\__error\__))...no
DXX-Archive.3: checking whether compiler accepts function \__attribute\__((\__error\__))...no
DXX-Archive.3: checking whether compiler implements \__builtin_bswap{16,32,64} functions...yes
DXX-Archive.3: checking whether compiler optimizes \__builtin_constant_p...no
DXX-Archive.3: checking whether compiler accepts \__builtin_constant_p...yes
DXX-Archive.3: checking whether compiler accepts \__builtin_expect...yes
DXX-Archive.3: checking whether compiler optimizes \__builtin_object_size...no
DXX-Archive.3: checking whether compiler accepts \__builtin_object_size...yes
DXX-Archive.3: checking whether compiler understands embedded compound statements...yes
DXX-Archive.3: checking for function \__attribute\__((always_inline))...yes
DXX-Archive.3: checking for function \__attribute\__((alloc_size))...no
DXX-Archive.3: checking for function \__attribute\__((cold))...yes
DXX-Archive.3: checking for function \__attribute\__((format_arg))...yes
DXX-Archive.3: checking for function \__attribute\__((format(printf)))...yes
DXX-Archive.3: checking for function \__attribute\__((malloc))...yes
DXX-Archive.3: checking for function \__attribute\__((nonnull))...yes
DXX-Archive.3: checking for function \__attribute\__((noreturn))...yes
DXX-Archive.3: checking for function \__attribute\__((used))...yes
DXX-Archive.3: checking for function \__attribute\__((unused))...yes
DXX-Archive.3: checking for function \__attribute\__((warn_unused_result))...yes
DXX-Archive.3: checking for \<array>...yes
DXX-Archive.3: checking for C++11 intrinsic static_assert when true...no
DXX-Archive.3: checking for Boost.StaticAssert when true...no
DXX-Archive.3: checking for C typedef static assertion when true...no
DXX-Archive.3: checking for \<type_traits>...yes
DXX-Archive.3: checking for C++11 range-based for...yes
DXX-Archive.3: checking for required C++11 features...yes
DXX-Archive.3: checking whether compiler supports constexpr union constructors...yes
DXX-Archive.3: checking when to pre-compile own headers...never
DXX-Archive.3: checking when to pre-compile system headers...never
error: no result
DXX-Archive.3: checking for explicitly deleted functions with named parameters...yes
DXX-Archive.3: checking for C++11 functions begin(), end()...yes
DXX-Archive.3: checking for C++11 function addressof()...yes
DXX-Archive.3: checking for C++14 exchange...yes
DXX-Archive.3: checking for C++14 integer_sequence...yes
DXX-Archive.3: checking for C++14 make_unique...yes
DXX-Archive.3: checking for C++11 inherited constructors with good unique_ptr\<T[]> support...no
DXX-Archive.3: checking for C++11 variadic templates on constructors...yes
DXX-Archive.3: checking for C++11 reference qualified methods...yes
DXX-Archive.3: checking whether compiler handles 20-element tuples...yes
DXX-Archive.3: checking whether to use Valgrind poisoning...(cached) no
DXX-Archive.3: checking whether to use overwrite poisoning...(cached) no
DXX-Archive.3: checking for strcasecmp...yes
DXX-Archive.3: checking whether compiler accepts -fvisibility=hidden...yes
DXX-Archive.3: checking whether compiler accepts -Wsuggest-attribute=noreturn...no
DXX-Archive.3: checking whether compiler accepts -Wlogical-op...no
D1X-Rebirth.1: compiling on darwin for darwin into . with prefix list ['d1x', '']
D1X-Rebirth.1: LittleEndian machine detected
D1X-Rebirth.1: building with OpenGL
 running tool: TOOL_BUNDLE
 running tool: TOOL_WRITE_VAL
D2X-Rebirth.2: compiling on darwin for darwin into . with prefix list ['d2x', '']
D2X-Rebirth.2: LittleEndian machine detected
D2X-Rebirth.2: building with OpenGL
 running tool: TOOL_BUNDLE
 running tool: TOOL_WRITE_VAL
scons: done reading SConscript files.
scons: Building targets ...
scons: Configure: creating dxxsconf.h
Compiling dxx-common . common/2d/2dsline.cpp
Compiling dxx-common . common/2d/bitblt.cpp
Compiling dxx-common . common/2d/bitmap.cpp
Compiling dxx-common . common/2d/box.cpp
Compiling dxx-common . common/2d/canvas.cpp
Compiling dxx-common . common/2d/circle.cpp
Compiling dxx-common . common/2d/disc.cpp
Compiling dxx-common . common/2d/gpixel.cpp
Compiling dxx-common . common/2d/line.cpp
Compiling dxx-common . common/2d/pixel.cpp
Compiling dxx-common . common/2d/rect.cpp
Compiling dxx-common . common/2d/rle.cpp
Compiling dxx-common . common/2d/scalec.cpp
Compiling dxx-common . common/3d/draw.cpp
Compiling dxx-common . common/3d/globvars.cpp
Compiling dxx-common . common/3d/instance.cpp
Compiling dxx-common . common/3d/matrix.cpp
Compiling dxx-common . common/3d/points.cpp
Compiling dxx-common . common/3d/rod.cpp
Compiling dxx-common . common/3d/setup.cpp
Compiling dxx-common . common/arch/sdl/event.cpp
Compiling dxx-common . common/arch/sdl/joy.cpp
Compiling dxx-common . common/arch/sdl/key.cpp
Compiling dxx-common . common/arch/sdl/mouse.cpp
Compiling dxx-common . common/arch/sdl/timer.cpp
Compiling dxx-common . common/arch/sdl/window.cpp
Compiling dxx-common . common/main/cli.cpp
Compiling dxx-common . common/main/cmd.cpp
Compiling dxx-common . common/main/cvar.cpp
Compiling dxx-common . common/maths/fixc.cpp
Compiling dxx-common . common/maths/rand.cpp
Compiling dxx-common . common/maths/tables.cpp
Compiling dxx-common . common/maths/vecmat.cpp
Compiling dxx-common . common/mem/mem.cpp
Compiling dxx-common . common/misc/error.cpp
Compiling dxx-common . common/misc/hash.cpp
Compiling dxx-common . common/misc/hmp.cpp
Compiling dxx-common . common/misc/ignorecase.cpp
Compiling dxx-common . common/misc/strutil.cpp
Compiling dxx-common . common/texmap/ntmap.cpp
Compiling dxx-common . common/texmap/scanline.cpp
common/texmap/scanline.cpp:182:6: error: cast from 'ubyte \*'
      (aka 'unsigned char \*') to 'unsigned long \*' increases required alignment
      from 1 to 8 [-Werror,-Wcast-align]
                        \*((unsigned long \*) dest) = destlong;
                          ^~~~~~~~~~~~~~~~~~~~~~
common/texmap/scanline.cpp:385:7: error: cast from 'ubyte \*'
      (aka 'unsigned char \*') to 'uint64_t \*' (aka 'unsigned long long \*')
      increases required alignment from 1 to 8 [-Werror,-Wcast-align]
                                \*((uint64_t \*) dest) = destlong;
                                  ^~~~~~~~~~~~~~~~~
common/texmap/scanline.cpp:427:18: error: cast from 'ubyte \*'
      (aka 'unsigned char \*') to 'uint64_t \*' (aka 'unsigned long long \*')
      increases required alignment from 1 to 8 [-Werror,-Wcast-align]
                                destlong = \*((uint64_t \*) dest);
                                             ^~~~~~~~~~~~~~~~~
common/texmap/scanline.cpp:509:7: error: cast from 'ubyte \*'
      (aka 'unsigned char \*') to 'uint64_t \*' (aka 'unsigned long long \*')
      increases required alignment from 1 to 8 [-Werror,-Wcast-align]
                                \*((uint64_t \*) dest) = destlong;
                                  ^~~~~~~~~~~~~~~~~
common/texmap/scanline.cpp:613:6: error: cast from 'ubyte \*'
      (aka 'unsigned char \*') to 'unsigned long \*' increases required alignment
      from 1 to 8 [-Werror,-Wcast-align]
                        \*((unsigned long \*) dest) = destlong;
                          ^~~~~~~~~~~~~~~~~~~~~~
5 errors generated.
scons: \*\*\* [common/texmap/scanline.o] Error 1
scons: building terminated because of errors.

Regards,

Chris

**Comment by vLKp** [comment]
I removed `-Wcast-align` from the default options.  As noted in the commit message, it was not producing warnings for me on x86_64-pc-linux-gnu, so the only way for me to find these would be to incrementally fix problems as you filed them.

If you want to fix these errors, feel free to revert the removal.

**Comment by kreatordxx** [comment]
OK, I might try doing this for Mac only, next time I play around with DXX-Rebirth. Thanks

**Comment by vLKp** [comment]
What do you need me to do with this ticket?  Are you still seeing compilation problems in scanline.cpp after I removed `-Wcast-align`?

**Comment by vLKp** [comment]
[Remove -Wcast-align from default compiler options](https://github.com/dxx-rebirth/dxx-rebirth/commit/4afae878835fc590623eed109869224448249af5) resolved this for the default build.  No response from original reporter after 2 weeks.  Closing.

@kreatordxx: please reopen and provide updated logs if this is still a problem.
