### ISSUE TITLE
Leaving Sub-Menus Moves Selection to Top

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#121]
Currently if you're in a sub menu and exit out, you will be moved back to the top of the previous menu. I believe this is original behavior, but since menus are starting to get longer, it would be nice to put you back on the sub menu item that you just left.

**Comment by Mako88** [comment]
Actually, I was wrong before. The only menus that don't do this are the "Set objects granted at spawn" and "Set objects allowed", so both of these should return to their respective menu item when the submenu is closed.

**Comment by vLKp** [comment]
Fixed by above commit.  Please reopen if you believe further work is needed.
