### ISSUE TITLE
Rearrange Escape Menu

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#126]
Some people have complained that they used to be able to hit escape, and then left-click to exit, whereas now the mouse is over "options" when they hit escape. Is it possible to either move where the mouse centers, or rearrange the menu so that abort is under the mouse by default?

**Comment by vLKp** [comment]
Yes, but you can also use Esc+Enter to quit, which in my opinion is even better than Esc+left-mouse-button.  Having the mouse centered over the option to leave game is a historical accident brought about by keeping the mouse centered in the window when the user has enabled mouse grab.

**Comment by Mako88** [comment]
I agree, and have always used Esc+Enter myself, but there are several pilots who use Esc+LMB, and this would probably become rather annoying for them rather quickly.

**Comment by vLKp** [comment]
I would rather not rearrange the menu, but we can look at moving the mouse.

**Comment by vLKp** [comment]
In looking at this on a build from before the new menu, my cursor is never centered when I opened the Abort Game menu.  I think that is why I went to using Esc+Enter, since it worked without trying to figure out where my cursor was on screen.

**Comment by Mako88** [comment]
This may be a resolution-dependent thing, in which case we shouldn't have to worry about it. I'll do some testing of this later on and see what I find.

**Comment by vLKp** [comment]
By "never centered", I mean that it is wherever the cursor would be based on how I have moved my mouse while steering.  If I just finished a hard left, my cursor is near the left edge of the screen.  This could be OS-dependent.  Some systems might allow the mouse cursor to move while grabbed, while others force it to remain in a particular place.

**Comment by vLKp** [comment]
This may be mitigated by [Hide save/load game menu items for non-host](https://github.com/dxx-rebirth/dxx-rebirth/commit/af3241098b4f524632a7049018ed8d5f1a3f1c4b).  After that commit, the added options are only shown if the player is in single player mode or if the player is the host of a cooperative multiplayer game.  Deathmatch games do not show the option since saving is not allowed there.  Non-hosts do not see the options since only the host is allowed to execute a save/load.

**Comment by Mako88** [comment]
I'm going to call this closed since it's not really feasible to reliably position the mouse underneath quit, and as you said, it's no longer an issue in the majority of cases.
