### ISSUE TITLE
Software rendering: GAME_FONT mirrored

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#130]
Just testing something today so I compiled the games (affects both d1x and d2x) without OpenGL support.
Here I noticed that GAME_FONT is completely mirrored horizontally. More so if using the low res version of GAME_FONT, they seem to be completely corrupted (just a few dots).

**Comment by vLKp** [comment]
Fixed in [Flip direction of bit scan[1]](https://github.com/dxx-rebirth/dxx-rebirth/commit/609e6ca584cf8c95a701cbe2db09c04a0331da5c) and [Flip direction of bit scan[2]](https://github.com/dxx-rebirth/dxx-rebirth/commit/3c297426982242c0257c3fad06198d27a43974c4).
