### ISSUE TITLE
2nd Spawner in Co-op (D1 First Strike Level 6) Doesn't Spawn All Bots

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#132]
On level 6 of D1 First Strike (playing on Trainee in co-op) the second spawner (the one that you will fly through if you fly straight from the spawn point) triggers correctly the first two times. The third time, it spawns one bot, then fires, but doesn't spawn a bot, then doesn't fire a third time.

In triggers 3 times, spawning 3 bots each time. There was talk of spawners not working correctly in co-op, though I never heard what exactly the problem was. This is a reproducible problem I've found, but if that's the only problem, I don't think it's very high-priority.

**Comment by zicodxx** [comment]
I would love to get this fixed asap but the thing is: I have yet to *see* this issue so I can start looking for the root. I do see a potential problem concerning Multiplayer but that would not allow the flash to appear  at all. 
If you can, can you give me a more accurate description on how to produce this? I assume it must be connected with how multiple player ships trigger the matcen (spawner). In my test I put the host ship in front of the door and turned around, observing a second player triggering it - with no issues. If you can recall any details on what you did to trigger this, I very much would welcome it. Thank you. :)

**Comment by vLKp** [comment]
This was re-reported in #386.  A likely fix was committed for that ticket, and is referenced above.  Please reopen if the problem persists.
