### ISSUE TITLE
The Only Multiplayer Command Working is /killreactor

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#134]
No other commands currently work.

**Comment by vLKp** [comment]
`/handicap` seems to work for me:

```
Telling others of your handicap of 10!
```

**Comment by zicodxx** [comment]
I also tested the /move and /kick commands. Works fine for me. Make sure you don't forget the ":" after the command and a space in between that and the player name.

**Comment by Mako88** [comment]
Oh, I didn't realize there had to be a colon...that's probably the problem.

**Comment by Mako88** [comment]
Tested with a colon, and it's working. Closing.
