### ISSUE TITLE
Negative score displays 65535 (which is 2^16 - 1) in team games

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#137]
When playing a team anarchy (whether or not a kill goal is set) when a player gets a negative score (through suicide or team kill), instead of -1, 65355 is shown. If he gets another suicide it shows 65354, and if he gains a point it goes back to 0.

Also, possibly related to issue #131, with a kill goal set, this does not trigger the goal (so there may be something wrong with checking kill goals at very high numbers).

**Comment by vLKp** [comment]
Which kill list mode are you using?  I looked into this for `(Netgame.PlayTimeAllowed || Netgame.KillGoal)` and it looks fine.  I was about to post, when I noticed you might be using `(Show_kill_list == 3)`, which does look like it is affected.

**Comment by Mako88** [comment]
What do you mean, which kill list? I'm just using the default hud that shows names and scores.

**Comment by vLKp** [comment]
`hud_show_kill_list` has a complicated set of conditionals for what to render.  Some of it is chosen based on game type.  Some of it is based on the user's choice of kill list mode, which can be changed by pressing `F7`.

**Comment by Mako88** [comment]
OK, this was in a team anarchy game, and I was using the default kill list (the one that shows a player's name and then his score, not his efficiency or anything).

**Comment by Mako88** [comment]
After further testing, this happens in all team games (not just anarchy). Also the number is 65535 (which seems to imply there's an unsigned number being read as a signed number)

**Comment by Mako88** [comment]
Correction: I checked all F3 hud settings...in the F7 hud settings it only happens in the team score (not the player score). The efficiency setting showed a large negative percentage.

**Comment by vLKp** [comment]
This may be fixed by [Make team_kills signed](https://github.com/dxx-rebirth/dxx-rebirth/commit/9da2a938d8e4b9771f20b4d915c2451ee9c1b3df).

**Comment by Mako88** [comment]
This is fixed. Closing.
