### ISSUE TITLE
Check if a kill that demotes a player is counted

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#142]
This is a bug I just discovered in Retro, and may still exist in Rebirth. When player A kills player B, causing player B to be demoted, player A is not given a point.

Because of the nature of the bug it's difficult to test, but could probably be checked in the code fairly easily.

**Comment by vLKp** [comment]
I think you overestimate the clarity of some of the old Parallax code. :wink:

Retro is based on 0.58.1, and I have not intentionally changed anything related to kill/point processing since 0.58.1, so we probably are affected.

**Comment by Mako88** [comment]
OK, so the good news is, a kill that demotes a player DOES give a point.

The bad news, is that if a player is promoted or demoted in a game it causes a crash for the people joined who are running Windows. While running Linux, as both the host and client, it never crashed (however, I was also always the person promoted or demoted).

Because it was crashing on Windows, I could not get a backtrace.

**Comment by vLKp** [comment]
Without register context, a backtrace, or some way to create one, there is not much I can do for you.  You could try rebuilding the Linux clients with AddressSanitizer to see if the rank change triggers an error that is normally harmless and silent on Linux.  Add `-fsanitize=address` to CXXFLAGS to enable AddressSanitizer.  I keep an entry in my `site-local.py` that defines `sa_CXXFLAGS='-fsanitize=address'` so that I can use `dxx=sa,` to enable the AddressSanitizer build.

**Comment by zicodxx** [comment]
Did you test this inside D1X or D2X? It was always present inside Descent 2 but never in the original game and I added it there at some point. However I see while D1X sends the MULTI_RANK packet just fine, the handling for a rank packet (multi_do_ranking()) is only compiled for D2X. So I suppose when such a packet is received by a client, it will throw an "invalid message type" error.
I pushed a96ceb2a460e5786ff1a8e6ae948bd9914bc8b04 (and tested it by triggering the packet on each kill) which would at least fix the issue in D1X but if you experienced this crash in D2X, we need to look further.

**Comment by Mako88** [comment]
Promotion no longer produces a crash. However, I could not demote a player, so I could not test that (is it possible that the demotion code was somehow changed)?

**Comment by Mako88** [comment]
To make this more clear...normally when a player is promoted, if he is immediately killed, he will be demoted again (sometimes it may take 2 or 3 kills...I'm not entirely sure exactly how the rank is calculated). When attempting to test this, however, I was never able to get a player to demote even after being killed upwards of 30 times.

**Comment by Mako88** [comment]
So...this seems to be about all that's left (other than @Matt1360 working on the tracker) before the next release. I would be willing to test this tomorrow evening CST @vLKp if you'd be available.

**Comment by Mako88** [comment]
I tested this just now. It's working correctly. Closing.
