### ISSUE TITLE
Disable Splash Damage With Friendly Fire

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#146]
If friendly damage is disabled, splash damage from friendly weapons should also be disabled.

**Comment by zicodxx** [comment]
This should be the case as of 57b4bd02810a0264c936cb49174d47fec3e9b639

**Comment by vLKp** [comment]
@Mako88: were you in a recent game where this did not work correctly?  @zicodxx's change went in on Aug 16.

**Comment by Mako88** [comment]
No, I was just in a Retro game and remembered that I had thought of this before, but didn't know if it was ever done. I just tested, and it's working right, so I'm gonna close this.
