### ISSUE TITLE
Players can fire flares during death roll

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#148]
While dying a player can still fire flares. Is this intended?

**Comment by zicodxx** [comment]
This is a small regression introduced in 29aa820dc0a2245158a52369634a0a7490d31997 in an effort by @vLKp to only flush fire button events.In ReadControls(), do_weapons_n_item_stuff() was not alled if Player_is_dead is set to true (which happens soon as the death animation starts. During this commit, it was changed so HandleDeathInput() must be set TRUE as well. However that only triggers if the player ship is already exploded.

**Comment by vLKp** [comment]
[Skip do_weapon_n_item_stuff if Player_is_dead](https://github.com/dxx-rebirth/dxx-rebirth/commit/bf52ebf4cd38cbfb4a01da44c16dcb8e2bfd7448) explicitly skips `do_weapons_n_item_stuff()` if `Player_is_dead`.  It also allows dead players to use the automap during the final reactor countdown.

**Comment by vLKp** [comment]
@Mako88: is [Skip do_weapon_n_item_stuff if Player_is_dead](https://github.com/dxx-rebirth/dxx-rebirth/commit/bf52ebf4cd38cbfb4a01da44c16dcb8e2bfd7448) sufficient to resolve the problem you saw?

**Comment by zicodxx** [comment]
For me your commit completely resolves the issue.

**Comment by Mako88** [comment]
I can confirm, the issue is fixed. Closing.
