### ISSUE TITLE
Always Select Highest Auto-Select Weapon

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#156]
In 0.58.1 (I haven't checked in the latest beta), when you run out of a certain weapon, the game automatically selects the next lowest fireable weapon on the autoselect list. It does this even if you have a weapon that is higher on the list than what is currently selected (i.e., you have 3 homers and 2 smarts. You manually select your homers and fire all of them. It will auto-select concs instead of switching to smarts, even though smarts are higher in your auto-select).

This is also true of manually selecting Vulcan and empyting the clip. The game will auto-select the next weapon lower than Vulcan on your auto-select list, even if you have a weapon that is higher.

**Comment by vLKp** [comment]
Confirmed.  [`auto_select_primary_weapon`](https://github.com/dxx-rebirth/dxx-rebirth/blob/e58cac874190823dfb308ce475361d7051b5dff0/similar/main/weapon.cpp#L595) and [`auto_select_secondary_weapon`](https://github.com/dxx-rebirth/dxx-rebirth/blob/e58cac874190823dfb308ce475361d7051b5dff0/similar/main/weapon.cpp#L649) begin their search at the currently active weapon and continue downward.

**Comment by vLKp** [comment]
Fixed in [Start ammunition-driven autoselect at 0](https://github.com/dxx-rebirth/dxx-rebirth/commit/9c5b5b3e3657acc506fd88d41ba278a4b785a3bd).

**Comment by vLKp** [comment]
@CDarrow: according to AFP, this affected 0.58.1 (and thus Retro).  It is more noticeable for secondary weapons, but affected both primaries and secondaries.
