### ISSUE TITLE
Damage does not force player out of menu/map

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#160]
In past releases, getting damaged forced the player out of menu/map mode so that he could defend himself.  This no longer happens.  It should be restored.

**Comment by zicodxx** [comment]
Yes, I removed this after multiple user requests. So it should be documented somewhere in the revision history and since this feature was requested initially, maybe we can make it a player controlled gameplay toggle.

**Comment by vLKp** [comment]
I see in the revision history that it was removed in [In Multiplayer when taking damage, the game will only leave menus when shield drop below 5](https://github.com/dxx-rebirth/dxx-rebirth/commit/8699ae6b63e3e1213e80fad8af7d01d60696fd73), but I never noticed it before.  When I remarked on it in the Rangers test game, none of the other users present corrected me (including the one who I asked to shoot me again to confirm it), so I think none of them knew about the change either.

**Comment by zicodxx** [comment]
I cannot remember anymore who asked me about this feature back in the day. It may still be somewhere in the forums but I'm not sure. We can certainly revert this as it just restores the original behavior of the game which is definitely in my favor. 
I see both ways making sense tho. Which is also why I'm pretty hesitant putting in new features in the past months as it's just impossible for me to decide anymore what kind of features will serve a single person, a small group or be cool with all the user base.

**Comment by zicodxx** [comment]
Okay, so I reverted back to the original behavior in b2864581198b2fea4fb828f7316a61764a355f88. I referenced both changes I made to this function but the first one I listed somehow  points to the wrong one. :/ But still the original behavior should be restored now and players will automatically leave menus and the map upon taking damage again.
