### ISSUE TITLE
Shield gauge wrong in demo playback

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#168]
So as stated in #167, I got some demos that report the shield wrong from the start. Those are all Descent 2 demos as I have not yet checked out how it looks in Descent 1 but I can do that later. I uploaded all the demos to http://dxx-rebirth.com/tmp/shieldbugdem.tar.gz.

Those usually have the issue that on start of the demo, the shields display at 0.
But there are 2 exceptions:
a) secret.dem: Reverts the shields from 100 to 0 soon as entering the secret level (confirmed in DOS game the shields should display as 100)
b) descent2.dem: The original Descent 2 demo included with the game. Starts out with 100 shields but soon as the player takes damage, it jumps down to 158. I can confirm in the original DOS game as well as release D2X-R 0.58.1 it should start with 163.

**Comment by vLKp** [comment]
[Poison objects on level load](/dxx-rebirth/dxx-rebirth/commit/3d246427e1008e28c837c571852381e8511f4523) fixes the issue for me with the built-in demo.  I expect Descent 1 was affected as well, since the relevant code is used in both games without any preprocessor guards.

**Comment by zicodxx** [comment]
I checked all my demos I have available - both D1 and D2 and I can't spot any incorrect shield gauges anymore. Thanks. :)
