### ISSUE TITLE
[matt-tracker] Bundled JsonCPP

### ISSUE THREAD

**Issue by Matt1360** [dxx-rebirth/dxx-rebirth#172]
Gotta get rid of this.  It should rely on the system package `jsoncpp` which is currently tested with 1.6.5.

**Comment by Matt1360** [comment]
Removed the bundled version.  Added the `jsoncpp` library alongside `curl`, but it doesn't do any testing for either library.  Totally just assumes they exist.

**Comment by zicodxx** [comment]
As the tracker has since been changed, I'll close this issue.
