### ISSUE TITLE
Host-authorative powerup spawning

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#174]
Okay, so I have this cooking for a while now and I would like to open this before I lay down the code base for it. This feature is specifically meant for 0.61 - not 0.60 as it is a pretty heavy change to how multiplayer will handle powerup repopulation.

This issue would fix #109 #139 and in part #102.

The idea:
Have the host repopulate the level with powerups that were consumed by firing (currently done by client), lost by player timing out or player collecting a 4 pack while not being able to hold 4 (i.e. inventory allows 3 or less).

Requirements:
* The host has to count all the powerups as soon as the level starts. Similar as it is done right now.
* Players should send their inventory to the host and relayed to other players regularly. Does not need to be a protected packet and could be sent rather frequently without raising the game traffic all too much. This packet should contain all weapons and items the player carries as well as items (afterburner, map, cloak, invul, etc) and last but not least energy and shield levels.
I'd like to add as much into this packet as possible as it could be used later to trigger (de)cloaking, invulnerability, death and respawn, etc. This doesn't need to be done now, tho. Important is that the host is informed about the inventory of the player.
Surely this implies trust in the honesty of the player. But when #102 is completely done, players would only be allowed to collect what the host dictates and then this packet could be used to determine if a player cheats.
* Regularly, the host will re-count the inventory and check it against the player inventories. If there is a discrepancy, the host will randomly respawn whatever is missing from the level.

Advantages:
* This function should keep the level inventory consistent, no matter what happens to the players.
* If a player times out, all other game participants know about their inventory, making sure the disconnecting player will drop all their loot.
* With the player status packets it will be easy to let the host decide - in a later commit - if a client is allowed to collect a powerup. This could be a possible feature for the future to prevent multiple players collecting the same item on high ping. 

Disadvantages and challenges:
* The code may get a little complex and has to be flexible enough to properly adjust to players starting inventory as well as players randomly connecting and disconnecting.
* Since the removal of a powerup may not be immediately accompanied by a status update packet, the host may need to wait a second or two before deciding if the powerup is valid to respawn. Otherwise the host may spawn powerups that a client just added to their inventory. However if we should later make the host decide what a client is able to collect, the inventory could be updated locally on host-side while allowing the player to collect, eliminating the need to wait for a status update.
* It would be of course desirable to not have these status packets and only let the host update a player inventory locally. But since fire packets are not protected nor we could accurately determine player shield and energy usages, some values computed by host locally would not accurately represent the client inventories. This will also be a challenge to determine if a player is cheating or not.

Again, this is a DRAFT I want to leave open for discussion. With the implementation of ordered packet loss protection, some of this is probably overkill. While it may be a good idea theoretically, the practical use may not be worth it. Instead just fixing loss during powerup collection (can collect < 4 from 4pack), respawning vulcan ammo, etc. may as well do the trick.

Thoughts?

**Comment by Mako88** [comment]
So, is this done now?

**Comment by zicodxx** [comment]
Actually, yes, I did implement everything as proposed in this draft. We may still fine-tune this later but as it stands, this can be closed.

**Comment by Mako88** [comment]
Can #109 and #102 be closed now?

**Comment by zicodxx** [comment]
I believe #109 may still be relevant. I am going to test this.
