### ISSUE TITLE
Vulcan ammo display overflow with Ammo rack

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#178]
During testing with powerup drops today I noticed that the ammo display for Vulcan can overflow if the player has the Ammo rack.

Instead of 40000 rounds, the HUD will display -25536.
This seems to happen at the point when VULCAN_AMMO_SCALE is applied and while a lot of small things changed between 0.58.1 and recent commits regarding that, I can for the life of me not figure out why this happens. I assume there is a signed type involved but even changing the ambiguous int casts involved here to strict unsigned didn't help me to fix this. what do I miss here?

**Comment by vLKp** [comment]
Using `f2i` converts to `signed int`.  Vulcan ammunition is a count, not a fix, so it should not be converted using signed fixed point math.  I will fix this.

**Comment by vLKp** [comment]
[Fix vulcan ammo display](/dxx-rebirth/dxx-rebirth/commit/c3003fbb229d21c722c318bc2d3eae71b9678693) should resolve this.
