### ISSUE TITLE
get_player_id handling dead players

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#182]
In the multiplayer, when a player dies, their object is changed to OBJ_GHOST.
This will trigger a - so far - harmless bug in  multi_do_reappear where get_player_id is used to identify the object that is OBJ_GHOST and turn it into OBJ_PLAYER again. 
I am putting this as a question as the bug message is harmless/false positive. I'm not 100% positive but there may be more triggers for that - depending on how the game proceeds - especially when players leave the level through the exit.

Should get_player_id also accept OBJ_GHOST aside OBJ_PLAYER? OBJ_GHOST is only used for dead players so it _should_ be safe to do that but maybe there's a better way to handle this.

**Comment by vLKp** [comment]
I think that would be fine.  Is it ever legal for `multi_do_reappear` to be given a non-ghost player?  If not, it would be simpler to have a `get_ghost_id` that works like `get_player_id`, other than checking for `OBJ_GHOST` instead of `OBJ_PLAYER`.

**Comment by zicodxx** [comment]
Since 779738fa8064d2886ee53c928555c78de4f76853 this is now fully fixed for me. Closing.
