### ISSUE TITLE
Selecting a 'Browse...' option in 'Sound Effects & Music' menu causes no action / infinite stack recursion on Mac OS X

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#183]
On either D1X or D2X, in 'Sound Effects & Music' I select one of the options to browse to a file path (e.g. Path for Level Music (Browse...)). If launched in the regular way it does nothing. If I debug it, I get an EXC_BAD_ACCESS, and the stack trace shows select_file_recursive calling itself indefinitely. This is when building on Mac OS X Yosemite, Xcode 7.2.1.

I suspect Clang is compiling the select_file_recursive template so it calls itself instead of the function instance at line 1768.

**Comment by vLKp** [comment]
Attaching a debugger should not change the code flow like that.

Problem confirmed here.  [Fix template/helper confusion](/dxx-rebirth/dxx-rebirth/commit/4b4077bab9fc468fbc748ebfd1bc50115a4570d4) resolved it for me.

**Comment by kreatordxx** [comment]
Fixed! Yes, it is strange that it didn't crash when I launched it from the Finder. I found a similar issue with the Omega cannon, it was causing very high recursion with the trace_segs function (which has since been fixed). Instead of crashing, it caused long pauses.
