### ISSUE TITLE
Final Mine Explosion too Fast

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#185]
It looks like the final explosion of the mine while exiting is played at double speed (This was tested in co-op, not singleplayer).

**Comment by zicodxx** [comment]
Should be fixed by https://github.com/dxx-rebirth/dxx-rebirth/commit/649475e3bc39ac9c4bad0d664094681425a73e84

**Comment by vLKp** [comment]
The [line zico removed](/dxx-rebirth/dxx-rebirth/commit/649475e3bc39ac9c4bad0d664094681425a73e84#diff-700f7d76ab41f05a34f7fda6aa600839L551), and [the corresponding line in `object_move_one`](/dxx-rebirth/dxx-rebirth/blob/aaaabfeb3102fd77f2339385f691606fdcddae84/similar/main/object.cpp#L1624) both date back to the initial import (other than one syntax change).  Was this a regression or just something that looked wrong relative to other explosions?

**Comment by zicodxx** [comment]
It's a regression but from which point it originates I cannot say. The original D1 source has the line as well but in the DOS game the explosion plays as fast as after my commit. 

I should have traced it back to when it first occurred but seeing what it does there, I assume this is a very old regression - presumably dating back to the introduction of the event system that now calls object_move_one() during the escape sequence. Another reason may be that the explosion was initialized with IMMORTAL_TIME. I will go down the old versions of the game and make sure which commit exactly introduced it.

**Comment by vLKp** [comment]
If this is not a recent regression (say, 0.58 or later), I am not concerned with when it broke.

**Comment by zicodxx** [comment]
There we go: I bisected to the point when the explosion changed its speed and it comes down to b77eb5424b062b390a39e61e0cdcc9ede24aa2e1. This is where you moved external_explosion into the Objects array. With this, external_explosion was processed by objects_move_one() and had its lifetime reduced there as well aside of do_endlevel_frame redundantly. All in all I would keep my initial fix for this as it is.

**Comment by vLKp** [comment]
That makes sense.  I agree, the initial fix is correct.  I only wanted to understand why your change was necessary, and your analysis fits perfectly.
