### ISSUE TITLE
The linked profile crashes when joining a multiplayer game on Windows

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#188]
Here is the full folder: https://www.dropbox.com/s/rq4kwifeant8gpy/Rebirth%20Beta.7z?dl=0

I attempted to get a backtrace with the latest debug, but gdb returned "no stack". If you go into game, switch to another player profile, then switch back, "entropy" can join without crashing. Otherwise, it'll crash when trying to enter a game.

**Comment by Mako88** [comment]
A tad more info on this (though not much), all of the gdb threads exit with code 3 which apparently is an unhandled exception. I'll continue to try and see if I can get a backtrace for this.

**Comment by Mako88** [comment]
stderr.txt and stdout.txt are both empty.

Here's the last part of the gamelog.txt:

`09:21:58 P#0: Clearing MData store/trace list
09:21:58 P#0: Clearing trace list for 0
09:21:58 P#0: Clearing trace list for 1
09:21:58 P#0: Clearing trace list for 2
09:21:58 P#0: Clearing trace list for 3
09:21:58 P#0: Clearing trace list for 4
09:21:58 P#0: Clearing trace list for 5
09:21:58 P#0: Clearing trace list for 6
09:21:58 P#0: Clearing trace list for 7
09:22:01 P#0: Clearing MData store/trace list
09:22:01 P#0: Clearing trace list for 0
09:22:01 P#0: Clearing trace list for 1
09:22:01 P#0: Clearing trace list for 2
09:22:01 P#0: Clearing trace list for 3
09:22:01 P#0: Clearing trace list for 4
09:22:01 P#0: Clearing trace list for 5
09:22:01 P#0: Clearing trace list for 6
09:22:01 P#0: Clearing trace list for 7
09:22:03 P#1: Clearing MData store/trace list
09:22:03 P#1: Clearing trace list for 0
09:22:03 P#1: Clearing trace list for 1
09:22:03 P#1: Clearing trace list for 2
09:22:03 P#1: Clearing trace list for 3
09:22:03 P#1: Clearing trace list for 4
09:22:03 P#1: Clearing trace list for 5
09:22:03 P#1: Clearing trace list for 6
09:22:03 P#1: Clearing trace list for 7`

**Comment by Mako88** [comment]
OK, it looks like the problem is that gdb can't get a stack on an unhandled exception.

Could we instead use gcc's backtrace in the debug builds? (This would also make it much easier for Windows users to provide backtraces in general).

References:
http://stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes
http://stackoverflow.com/questions/3355683/c-stack-trace-from-unhandled-exception

**Comment by Mako88** [comment]
HAHA!!! I found the issue!!!

In the d1x.ini file in the linked directory, the -player option is set. HOWEVER, it is set to "-player Entropy" with a capital E. If it is changed to "-player entropy" it works fine. Apparently somewhere in the code, the player profile that is chosen from command line isn't set to lowercase properly.

This also happened if I changed my own .ini file to include "-player Afp" (capital A). I got a runtime error when joining a netgame.

**Comment by vLKp** [comment]
You can use `catch throw` at the `(gdb)` prompt to cause the debugger to break when the exception is thrown, which should allow you to record the stack trace before the unwind happens.

I tested this a bit and the netgame joining code seems not to handle this well at all.  I ran into three different failure modes so far.  The failures I observed were:

1. Joining user hangs at 100% CPU with a black screen.  I reproduced this in a debugger, but it does not make much sense.  The game looks like it is running the expected processing loops, yet nothing is drawn and the game never sleeps.  This might happen if the objects for some segment end up cross-linked.  Failure \#2 is an example of cross-linking that was caught, but perhaps there are also failure modes that are not caught by an assertion.
1. Joining user aborts with an assertion failure after object 0 is linked to itself (`Objects._M_elems[0].next = 0`).
1. Joining user crashes with an exception `local_player_not_playing`.  This is probably the one that you saw.

Do I recall correctly that you said elsewhere that this is already broken in 0.58.1?

**Comment by Mako88** [comment]
I'm not sure if it's broken in 0.58.1 or not. I've only seen the 3rd issue that you posted above.

**Comment by vLKp** [comment]
The line which throws that exception is not present in 0.58.1.  The user will still fail to play, but the specific failure is different.

**Comment by vLKp** [comment]
As a quick workaround, I can modify the handling of `-pilot` to coerce the string to lowercase.  This will not address the internal consistency crashes I saw, but should prevent users from easily hitting them.

**Comment by Mako88** [comment]
I think that'd be a good idea :)
