### ISSUE TITLE
Moving the mouse while moving the camera in automap affects camera movement

### ISSUE THREAD

**Issue by Jayman2000** [dxx-rebirth/dxx-rebirth#189]
If you open the auto map, start moving the camera with the keyboard, and move the mouse, then the camera will move faster. This happens regardless of weather or not the mouse is enabled in the settings menu. If the -nomouse parameter is used, then the same thing will happen, except the camera will halt instead of moving faster.

Happens in both latest release and latest git version.

**Comment by zicodxx** [comment]
Thanks for the report, Jayman2000. I committed https://github.com/dxx-rebirth/dxx-rebirth/commit/a8ed0aaa9c83edc023b70793be721509fe718b70 which should fix the issue. :)
