### ISSUE TITLE
Change Control Boxes Don't Change Color

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#192]
In the Customize Keyboard (or Mouse, or Joystick, etc.) menu, the purple boxes are all the "selected" color. When you hover over them they don't change, so you can't see which control you're adjusting (primary or alternate). They should normally be a darker purple then change to the color they currently are when they're hovered.

**Comment by vLKp** [comment]
Confirmed.  [Pass color to gr_urect](/dxx-rebirth/dxx-rebirth/commit/35a4736df067da92eccbb560beb55cdb2320b42b) broke this by doubling the double step.
