### ISSUE TITLE
-Wshadow warnings when building with with gcc 4.x

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#197]
When building with the `-Wshadow` flag as now enabled by default, older gcc versions prior to 5.x report a lot of warnings of the form:

    CXX d1x . similar/main/ai.cpp
    In file included from common/main/wall.h:27:0,
                     from similar/main/ai.cpp:51:
    common/main/segment.h: In constructor 'dcx::visited_segment_mask_t<T, bits>::base_maskproxy_t::base_maskproxy_t(unsigned int)':  
    common/main/segment.h:318:36: warning: declaration of 'shift' shadows a member of 'this' [-Wshadow]
       base_maskproxy_t(unsigned shift) :
                                        ^

The issue is the local function parameter `shift` shadowing the method `visited_segment_mask_t::base_maskproxy_t::shift()`. However, gcc's warning behavior changed, and with gcc 5.0, this warning has been removed, as described in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57709.

I dunno if you want to fix the warning also for gcc 4.x (renaming either the function or the parameter is quite trivial), or go with modern gcc's consensus that this kind of identifier shadowing is not an issue to be concerned about.

**Comment by vLKp** [comment]
I doubt we will release before all distributions move up to gcc 5.x, but the fix is so easy that I see no reason not to do it.  Clearly, I only build tested it with gcc 5 before pushing it.  I had forgotten that gcc's `-Wshadow` had changed like that in 5.x or I would have tested older versions as well.
