### ISSUE TITLE
Compile issue with gcc-4.8 constexpr

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#202]
I'm working on getting the matt-tracker branch compiling for testing. I'm currently get this error:

```
common\maths\vecmat.cpp:26:22: error: redeclaration 'dcx::vmd_identity_matrix' differs in 'constexpr'
 constexpr vms_matrix vmd_identity_matrix = IDENTITY_MATRIX;
                      ^
In file included from common\include/vecmat.h:32:0,
                 from common\maths\vecmat.cpp:19:
common\include/fwd-vecmat.h:25:25: error: from previous declaration 'dcx::vmd_identity_matrix'
 extern const vms_matrix vmd_identity_matrix;
                         ^
scons: *** [common\maths\vecmat.o] Error 1
```

**Comment by vLKp** [comment]
Please do not copy from whatever console you used for that run.  It mangles whitespace horribly.  Instead, run the failed build with output redirected to a file, then post the contents of that file inside triple backticks.

**Comment by Matt1360** [comment]
Zico and I are supposed to work on this this weekend. I'm hoping to hit him
up tomorrow about it.

**Comment by Mako88** [comment]
@vLKp I'll do that from now on :)

@Matt1360 Yeah, he mentioned that. I just wanted to get it compiling since I'll be compiling the Windows builds when it's all done. Also, if I compile it, I can help test.

**Comment by vLKp** [comment]
I think this is an incorrect report.  I see the inconsistency in qualifiers when looking at unification/master, but it does not cause a compilation problem.  I see the qualifiers as consistent on matt-tracker.
```
$ git log --no-walk --oneline github/unification/master github/matt-tracker 
8fef6a0 (HEAD, github/unification/master) Pass const object_base to obj_unlink
dd0b11e (github/matt-tracker) Fix packet sizing
$ git show github/unification/master:common/maths/vecmat.cpp | cat -n | grep -m1 -C3 '   26'
    23	
    24	//#define USE_ISQRT 1
    25	
    26	constexpr vms_matrix vmd_identity_matrix = IDENTITY_MATRIX;
    27	
    28	//adds two vectors, fills in dest, returns ptr to dest
    29	//ok for dest to equal either source, but should use vm_vec_add2() if so
$ git show github/unification/master:common/include/fwd-vecmat.h | cat -n | grep -m1 -C3 '   26'
    23	struct vms_quaternion;
    24	
    25	extern const vms_matrix vmd_identity_matrix;
    26	
    27	#define IDENTITY_MATRIX { {f1_0,0,0}, {0,f1_0,0}, {0,0,f1_0} }
    28	
    29	vms_vector &vm_vec_add (vms_vector &dest, const vms_vector &src0, const vms_vector &src1);
$ git show github/matt-tracker:common/maths/vecmat.cpp | cat -n | grep -m1 -C3 '   26'
    23	
    24	//#define USE_ISQRT 1
    25	
    26	const vms_matrix vmd_identity_matrix = IDENTITY_MATRIX;
    27	
    28	//adds two vectors, fills in dest, returns ptr to dest
    29	//ok for dest to equal either source, but should use vm_vec_add2() if so
$ git show github/matt-tracker:common/include/fwd-vecmat.h | cat -n | grep -m1 -C3 '   26'
    23	
    24	extern const vms_matrix vmd_identity_matrix;
    25	
    26	#define IDENTITY_MATRIX { {f1_0,0,0}, {0,f1_0,0}, {0,0,f1_0} }
    27	
    28	vms_vector &vm_vec_add (vms_vector &dest, const vms_vector &src0, const vms_vector &src1);
    29	
```

**Comment by Mako88** [comment]
To verify that it wasn't an issue with my local repo, I deleted the git directory, and recreated. Switching to matt-tracker branch and trying to compile now results in this:

```
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr:
  File "C:\Users\John\dxx-rebirth\SConstruct", line 3702:
    d.init(substenv)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 3423:
    DXXProgram.static_archive_construction[self.user_settings.builddir] = DXXArchive(self.user_settings)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 3139:
    self.configure_environment()
  File "C:\Users\John\dxx-rebirth\SConstruct", line 3163:
    getattr(conf, k.name)()
  File "C:\Python27\Lib\site-packages\scons-2.4.1\SCons\SConf.py", line 669:
    ret = self.test(context, *args, **kw)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 411:
    most_recent_error = self._check_cxx_works(context)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 477:
    self._show_tool_version(context, CXX, 'C++ compiler')
  File "C:\Users\John\dxx-rebirth\SConstruct", line 436:
    v = StaticSubprocess.get_version_head(tool)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 75:
    v = _qcall('%s %s' % (cmd, '--version'), stderr=subprocess.PIPE)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 72:
    return _pcall(_shlex_split(args),stderr)
  File "C:\Users\John\dxx-rebirth\SConstruct", line 67:
    p = subprocess.Popen(args, executable=args[0], stdout=subprocess.PIPE, stderr=stderr, close_fds=True)
  File "C:\Python27\lib\subprocess.py", line 667:
    raise ValueError("close_fds is not supported on Windows "
```

**Comment by vLKp** [comment]
That looks much more reasonable.  That is [issue #173: Can't compile with scons on Windows](/dxx-rebirth/dxx-rebirth/issues/173), which I caused with [Cache scons subprocess calls](/dxx-rebirth/dxx-rebirth/commit/bb3f414128bcf5848350905e019978e3f8f31d98) in April 2015, you reported December 2015, and I fixed with [Remove close_fds=True from StaticSubprocess](/dxx-rebirth/dxx-rebirth/commit/0a2ef79242362685493d42696bcad4a144c17f92) in January 2016.  You may run into other issues that have since been fixed on mainline, since the matt-tracker branch is currently quite outdated (666 commits behind master):
```
$ git rev-list github/unification/master ^github/matt-tracker | wc
    666     666   27306
```

**Comment by vLKp** [comment]
The problem reported in the opening comment is likely caused by using gcc-4.8.  My SConstruct tests print out compiler version (among other things) to help identify build environment issues, but that was not posted here, so I am guessing.  I can reproduce on gcc-4.8, but not on gcc-4.9 or later, a similar looking error:
```c++
extern const int i;
constexpr int i = 5;

int f()
{
        return i;
}
```
```
$ gcc-4.8.3 -std=gnu++0x -c -o /dev/null a.cpp 
a.cpp:2:15: error: redeclaration 'i' differs in 'constexpr'
 constexpr int i = 5;
               ^
a.cpp:1:18: error: from previous declaration 'i'
 extern const int i;
                  ^
$ gcc-4.9.2 -std=gnu++0x -c -o /dev/null a.cpp 
$
```
I no longer keep gcc-4.8 installed on my development system nor test compiling with gcc-4.8.  I happened to have gcc-4.8.3 installed on another system which is not otherwise prepared for Rebirth development.  I can revert the specific change that caused the problem reported in the opening comment, but there may be other issues that arise when using gcc-4.8.  I can try to address them as they arise, but testing the fixes may be difficult if the failure cannot be isolated to a testcase easy to run on my installed gcc-4.8.

**Comment by vLKp** [comment]
I updated the title to reflect that there is an unresolved problem in `unification/master` with regard to gcc-4.8 (all platforms) and `constexpr` handling.  Separately, and not tracked, there is a problem on the `matt-tracker` branch failing to build when using a Windows machine to host the build.  Cross-compilation still works fine.  The `matt-tracker` branch problem would be resolved by updating to the latest `SConstruct` from `unification/master`, probably the next time Matt merges from `unification/master` to `matt-tracker`.

@Mako88: what is the status of the gcc-4.8 `constexpr` problem?  As described above, I no longer test with gcc-4.8 or keep it installed in my development environment.  If you want to keep using gcc-4.8, I can try to resolve compatibility issues as you or others report them.  If you want to upgrade to gcc-4.9 or later, I will declare gcc-4.8 unsupported.

**Comment by Mako88** [comment]
I've updated to gcc-4.9.3 so this shouldn't be a problem anymore.

As to getting the matt-tracker build working, I'll wait until either the branch is merged into master, or is updated from master. I'll go ahead and close this issue.
