### ISSUE TITLE
Cannot use chaos.hog

### ISSUE THREAD

**Issue by monreal** [dxx-rebirth/dxx-rebirth#203]
I was unable to start maps from chaos.hog (descent 1 multiplayer maps). I found a forum post describing the same problem [1] which also has a solution. Looks like this workaround was added to d2x-xl but not dxx-rebirth. Maybe you could also fix this?

[1] http://www.descentbb.net/viewtopic.php?f=34&t=10297&sid=86475d3b1dddccd1ff299b7e0017e935

**Comment by vLKp** [comment]
That forum thread suggests that something was changed, but does not describe the change nor link to a source control commit.  Could you point to their change or describe specifically what prevents you from using these maps?  I do not seem to have these maps installed, so I cannot test it.

**Comment by monreal** [comment]
There seems to be a bug regarding the parsing of .msn files. The chaos.msn has comments (";" sign followed by some text) which should not be interpreted. I worked around by editing the .msn file using a text editor, just removing the comments and the chaos maps work now.

**Comment by vLKp** [comment]
Yes, I understood that from the linked forum post by Diedel dated **Sat May 20, 2006 11:38 am**.

The parser already has special handling to remove comments in several cases.  Testing here with `Descent: The Enemy Within` runs fine, even though its mn2 file has several lines that start with semicolons.  I see some cases in the parser that might reject certain types of comments.  I can fix those, but unless you provide a specific example of a comment that causes a parsing failure, I may be working in an area that does not help you.

**Comment by monreal** [comment]
This is the msn file:
---
name = Total Chaos	;any name you want
type = anarchy		;can be "normal" or "anarchy".  Omitted means normal
num_levels = 5		;number of normal levels
chaos1.rdl		;level filename 1
chaos2.rdl		;level filename 2
chaos3.rdl		;level filename 3
chaos4.rdl		;level filename 4
chaos5.rdl		;level filename 5
---

The comment after "num_levels" seems to be the problem. Even after removing all other comments and just having the semi-colon after that line it won't load.

**Comment by vLKp** [comment]
Yes, that would fail with current code.  That is not the block I expected would be a problem, so it is not the one I would have fixed.

**Comment by vLKp** [comment]
[Allow trailing comments after num_levels and num_secrets](/dxx-rebirth/dxx-rebirth/commit/a230d24226a2ea40826eda56104accf5961dadd4) relaxes the parsing of `num_levels` and `num_secrets` in a way that should allow the unmodified `chaos.msn` to work.  Previously, any characters between the number and newline would cause it to be rejected.  Now, if the first non-white character after the number is either `;` or null, the line is permitted.
