### ISSUE TITLE
Max turn rate with keyboard is higher than max turn rate with mouse

### ISSUE THREAD

**Issue by JPLeBreton** [dxx-rebirth/dxx-rebirth#205]
My steps to repro:
1. set mouse turn and pitch sensitivity as high as possible in settings, leaving the keyboard settings at default
2. in-game, drag the mouse left or right to turn - on my system, it's quite sluggish, way moreso than I'd expect in any other FPS
3. press the left or right arrow keys to turn - on my system, I can turn at a speed that feels comfortable
4. observe: turn rate with keyboard is noticeably higher than turn rate with mouse, even at max mouse sensitivity
Expected behavior: even if there are gameplay limits on turn/pitch rate, user should at least be able to turn as quickly with mouse as they do with keyboard.

Config: running v0.58.1 in Arch Linux, from the AUR package. Standard USB mouse and keyboard setup. Let me know if any other info would be useful. Wonderful project!

**Comment by zicodxx** [comment]
Hello,

This issue has been a very nasty problem for many years. As opposed to other FPSes, the turn speed is locked to the same speed on all input devices. And of course this should still enable you to turn as fast as with the keyboard. But as you describe, that's not always the case. 

We have worked hard on this in the current development branch. If you are able, could you check out the current unification branch and test with it? It should already feel a lot better and if it doesn't immediately, you could try playing with the "Mouse overrun" sliders (you find those in the sensitivity menus). 

It would help me a lot if you could give me feedback on this. Thank you. :)

**Comment by JPLeBreton** [comment]
Just compiled this and tried it with mouse overrun turned all the way up, and it does indeed feel more responsive!

**Comment by Mako88** [comment]
Since the issue seems to have been resolved, I'm closing this. If you feel like it's not adequately resolved @JPLeBreton, feel free to comment and it can be reopened :)
