### ISSUE TITLE
OPL3 music addon isn't recognized

### ISSUE THREAD

**Issue by JPLeBreton** [dxx-rebirth/dxx-rebirth#206]
1. Download `d1xr-opl3-music.dxa` from the website
2. Copy it into `~/.d1x-rebirth` where my config and HOG/PIG files are
3. Launch game
4. Observe: still hearing default system MIDI music, even with "Built-in/Addon music" selected from settings menu.

Config: running v0.58.1 in Arch Linux, from the AUR package.

**Comment by zicodxx** [comment]
Could you maybe post the output of the game using the "-debug" argument? The output should be in the shell when you launch the game but it's also saved in gamelog.txt. Just launching the game and quitting it soon as you have the chance would be enough. 

Also just as a disclaimer: The OPL3 Soundtrack may sound very, very similar to the default MIDI playback you get via timidity. For a real feast for the ears, I recommend the SC-55 addon package. :)

**Comment by JPLeBreton** [comment]
I can definitely tell the difference in OPL2/3 vs MIDI, I specifically downloaded and installed the OPL3 pack to bathe my ears in delicious nostalgia :]

However, I believe I mistook the SC-55 pack for system MIDI. With the -debug switch I think I figured out what's happening: I installed d1x-rebirth from the Arch repositories, and it automatically includes the `d1xr-sc55-music.dxa` addon in `/usr/share/d1x-rebirth`, which stomps the OPL3 pack in my home directory. As the log says:
```PHYSFS: Added /home/jpl/.d1x-rebirth/d1xr-opl3-music.dxa to Search Path
PHYSFS: Added /usr/share/d1x-rebirth/d1xr-sc55-music.dxa to Search Path```
I'm assuming the order in which it reports those is significant.
Three options I can think of for how to fix this:
- Always load addons in the user's `~/.d1x-rebirth` _after_ addons in the user's `/usr/share/d1x-rebirth`.
- Create a user option in the settings UI to specifically choose MIDI vs SC-55 vs OPL3 packs, if more than one are available.
- Get the Arch package maintainer to not auto-include the SC55 pack.
It's up to you which of those are best.
I was able to work around this by renaming the SC55 pack in my /usr/share. If nobody else has ever had this problem before, I'm happy to let this go unfixed if you don't feel it's important.

**Comment by zicodxx** [comment]
Yep, there we have the problem. The Addons do overwrite each other (similar to mods work in the Elder Scrolls games). There have been thoughts and propositions to expand this but since this problem - so far - only affects music Addons and you could theoretically switch between them using the Jukebox (the DXA files are just ZIPs which you can extract) I never really put more work into this. 

But you are definitely right that the Arch package should not include the soundtrack Addon. I will fix that. :)
