### ISSUE TITLE
DXX-Rebirth not compiling with latest commit on Apple's Clang: Doesn't like -Wuseless-cast

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#216]
When I build using the latest commit on Mac OS X El Capitan, I get the error in SCons:
scons: *** C++ compiler works with blank $CXXFLAGS.  C++ compiler does not work with specified $CXXFLAGS.  See sconf.log for details.  Stop.
Looking in sconf.log the relevant line is:
error: unknown warning option '-Werror=useless-cast' [-Werror,-Wunknown-warning-option]
So it looks like Apple's Clang doesn't like the -Werror=useless-cast option.
[sconf.log.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/465810/sconf.log.txt)

**Comment by kreatordxx** [comment]
> Although Apple installed their compiler as g++, it seems not to understand options understood by every supported version of g++. I will add an SConf test to enable -Wuseless-cast only when the compiler actually understands it, rather than expecting it to be supported on all modern compilers.

Thanks vLKp!

> As an oddity, Apple's linker seems not to return a valid result when probed for its version. This does not hurt anything, but is somewhat annoying. Do you know if there is an option that can be passed to Apple's linker to make it print its version? For GNU binutils, ld --version works.

Yes, with 'cpp -v'. The version is Apple LLVM version 7.3.0 (clang-703.0.31).

**Comment by vLKp** [comment]
That is the version of `cpp`, not of `ld`.  In the GNU toolchain, `cpp` comes from the compiler (gcc), but `ld` is the linker (from binutils).  The compiler and linker can be upgraded independently, so the version of binutils is different from the version of the compiler.  For example, I get:

```
$ cpp --version
cpp (Gentoo Hardened 4.9.3 p1.5, pie-0.6.4) 4.9.3
$ ld --version
GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
```

If the Apple toolchain does not understand this distinction, that is fine.  The information is logged for me to better understand build reports, but does not affect the generated code.

[Test whether compiler handles -Wuseless-cast](/dxx-rebirth/dxx-rebirth/commit/baa8831bce117447d84ca97dd5097fcccebc39b5) should prevent SCons from using `-Wuseless-cast` with clang.

**Comment by kreatordxx** [comment]
When I type `ld --version` it just says unknown option. When I type `ld -v` I get

```
@(#)PROGRAM:ld  PROJECT:ld64-264.3.102
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 7.3.0

```

It passed the physfs check fine, so closing.

**Comment by vLKp** [comment]
I think I will leave the code as-is for now.  It is mainly to distinguish between GNU ld and GNU gold, so the inability to get good output on OS X does not matter.
