### ISSUE TITLE
Not building on Mac OS X: DarwinPlatformSettings instance has no attribute 'get_platform_objects'

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#218]
Hi,

When I build on Mac OS X using commit f11235147a658ffb560567e9d9edad61b5742d47, I get this output (truncated):
D1X-Rebirth.1: compiling on darwin for darwin into . with prefix list ('d1x', '')
AttributeError: DarwinPlatformSettings instance has no attribute 'get_platform_objects':
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 4095:
    main(register_program)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 4070:
    ''.join(['%s.%d:\n%s' % (d.PROGRAM_NAME, d.program_instance, d.init(substenv)) for d in dxx])
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3787:
    self.prepare_environment(archive)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3796:
    DXXCommon.prepare_environment(self)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3248:
    env = self.env
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 2123:
    d[name] = r = self.method(instance)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3375:
    platform_settings = self.platform_settings
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 2123:
    d[name] = r = self.method(instance)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3371:
    )(self, self.user_settings)
  File "/Users/christaylor/Programming/dxx-rebirth/SConstruct", line 3735:
    self.platform_objects = self.get_platform_objects()[:]

**Comment by vLKp** [comment]
Please apply the below patch and try again.  As best I can recall, `get_platform_objects` / `platform_objects` are only needed on `DXXProgram` for Windows to build the game-specific resources.  `DXXCommon` uses `get_platform_objects` for Windows (`common/arch/win32/messagebox.cpp`) and for OS X (`common/arch/cocoa/messagebox.mm`, `common/arch/cocoa/SDLMain.m`).

```diff
diff --git a/SConstruct b/SConstruct
index a434134..565c4d8 100644
--- a/SConstruct
+++ b/SConstruct
@@ -3020,6 +3020,7 @@ class DXXCommon(LazyObjectConstructor):
 	class _PlatformSettings:
 		tools = ('g++', 'gnulink')
 		ogllibs = ''
+		platform_objects = ()
 		def __init__(self,program,user_settings):
 			self.__program = program
 			self.user_settings = user_settings
@@ -3732,7 +3733,6 @@ class DXXProgram(DXXCommon):
 		def __init__(self,program,user_settings):
 			DXXCommon.DarwinPlatformSettings.__init__(self,program,user_settings)
 			user_settings.sharepath = ''
-			self.platform_objects = self.get_platform_objects()[:]
 		def adjust_environment(self,program,env):
 			DXXCommon.DarwinPlatformSettings.adjust_environment(self, program, env)
 			VERSION = '%s.%s' % (program.VERSION_MAJOR, program.VERSION_MINOR)
```

If this patch works for you, I will finalize and push it.

**Comment by kreatordxx** [comment]
Yes, for some reason the patch fails (probably some hidden whitespace when I copied it) but when I apply it by hand it works - starting on compiling the source.

**Comment by vLKp** [comment]
[Fix SCons OS X get_platform_objects build error](/dxx-rebirth/dxx-rebirth/commit/2ccb4e7066a1e0027d3af8ffe96d42e5c4ddd5ad) is based on my above patch.
