### ISSUE TITLE
Starting 'Titan Centrifuge' Freezes D2X-Rebirth

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#237]
When I play [Titan Centrifuge](https://github.com/dxx-rebirth/dxx-rebirth/files/517715/titan.zip) on **Release** build it freezes. When I debug it, it looks like it is forever trying to page in a texture (for a weapon), but because piggy_page_out_all is a no-op it never has enough cache to do it.

**Comment by vLKp** [comment]
That is interesting.  I disabled the paging support because it seemed like the game never needed to page out anything, so tracking all that was a waste of effort left over from when Descent handled its own paging on DOS.

**Comment by vLKp** [comment]
This may be the same as issue #221.

**Comment by vLKp** [comment]
[Revert "Disable piggy_bitmap_page_out_all"](/dxx-rebirth/dxx-rebirth/commit/b43dcc1a5229e036bf038d91331962fbb58f7f94) restores the use of `piggy_bitmap_page_out_all`, which should resolve this.

**Comment by kreatordxx** [comment]
Fixed.
