### ISSUE TITLE
Stutter With Blocky Filtered + Anistropic Filtering

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#242]
As the title says, when I play with blocky filtered rendering and anisotropic filtering, I get a stutter while flying around.

**Comment by vLKp** [comment]
I cannot reproduce this, and the description is insufficient for me to debug this through code inspection. You will need to fix this yourself or provide more detailed information.

**Comment by Mako88** [comment]
I no longer see this in tip. Closing.
