### ISSUE TITLE
Flare remains in doorway

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#243]
In the latest build when you shoot a flare to open a door, the flare will remain in the doorway hovering in mid-air after the door has opened.

**Comment by vLKp** [comment]
I cannot reproduce this on **Descent 2: Counterstrike** level 1 with the first door.  Under what circumstances did you see this?

0.58.1-d2x-7038-g7a18f60a941e

**Comment by Mako88** [comment]
I tested this in multi-player games (co-op and anarchy) in Descent 1.

**Comment by vLKp** [comment]
I can reproduce this in Descent 1, but not in Descent 2.  It appears that `Stuck_objects` is only initialized in Descent 2, and that the uninitialized all-zeroes values found in Descent 1 cause the problem.

The Descent 1 implementation of `remove_obsolete_stuck_objects` was buggy.  I replaced it with the Descent 2 version in [Unify D1/D2 remove_obsolete_stuck_objects](/dxx-rebirth/dxx-rebirth/commit/b1bdf4aa53ed0b01b0bffbc917c2169018e3ee32).  Unfortunately, one of the bugs in the Descent 1 version compensated for the failure to properly initialize `Stuck_objects` by mishandling objects stuck in wall 0.  I suspect replacing `remove_obsolete_stuck_objects` with a non-buggy version broke this.

**Comment by vLKp** [comment]
[Initialize Stuck_objects for D1](/dxx-rebirth/dxx-rebirth/commit/aae5279bfd88d0896e0c0d033236d1938e821df9) fixes this for me.
