### ISSUE TITLE
Add "Attempting to Connect" popup

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#245]
When connecting to a network game, if you select the game, there is no indication that it is trying to connect until you either join or it times out. Since the timeout is several seconds, it would be nice to have some visual feedback such as a popup saying it's attempting to connect.

**Comment by zicodxx** [comment]
As of 730879d733700ab2c42bb8b9d7c6217ac84c5d96, this is now present. Closing.
