### ISSUE TITLE
"Prepare for Descent..." Screen Takes a Few Seconds with Blocky Filtered

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#248]
This may be related to #242, although this happens with or without anisotropic filtering.

**Comment by vLKp** [comment]
I cannot reproduce this, and the description is insufficient for me to debug this through code inspection.  You will need to fix this yourself or provide more detailed information.

**Comment by Mako88** [comment]
When using blocky filtered setting, the Prepare For Descent screen takes ~4 seconds. Without it, it takes ~2. This is most likely just loading the textures and isn't a bug. Closing.
