### ISSUE TITLE
Ping number on-screen incorrect

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#250]
The ping in the pause menu is accurate, but the ping shown on the main HUD is a huge number that doesn't make any sense.

**Comment by Mako88** [comment]
I just realized I also commented this on #90. I don't think we really need a packet loss monitor, so I'm gonna close that and leave this open.

**Comment by zicodxx** [comment]
Fixed in 3db9a8d999f33bb3f18fd73d9dace4988601c7a0. I have no idea why the number was multiplied by 44. Either a copy/paste mistake or maybe I did some large-number testing and forgot to take it out. Either way, it's fixed now. Closing.
