### ISSUE TITLE
Omega cannon recharge bugs

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#262]
The omega cannon is special.  Normally, the omega cannon does not charge for ~1/3 of a second after firing stops.  However, there are two problems with the existing implementation.  Both are caused by using `int` to track the absolute last fire time.

The first problem is that, if (Last_omega_fire_time + 1/3 second) exceeds 0x80000000 (about 9.1 hours), truncation issues confuse the recharge rule into not applying, thus allowing the omega cannon to charge whenever energy is available, even while firing.

The second problem is that, if GameTime64 exceeds 0x8000000000000000 (about 4459701.8 years), a sanity check that attempted to compensate for the incorrect tracking of Last_omega_fire_time would confuse the recharge rule into deciding that the user had always fired recently, which would prevent the omega cannon from ever recharging.  The sanity check would reset Last_omega_fire_time when Last_omega_fire_time is in the future relative to GameTime64.  Unfortunately, Last_omega_fire_time is only an int, so the reset truncates off the high bits of GameTime64.  This truncation is harmless when GameTime64 is less than 0x80000000, causes the first problem when GameTime64 is not less than 0x80000000, but is positive, and causes the second problem when GameTime64 is negative.

These problems were mitigated in prior releases by three factors.  First, a hack resets GameTime64 when restoring from a saved game, so the affected game needs to run for ~9.1 hours (or ~4459701.8 years) without reloading.  Second, starting a new level resets GameTime64, so the game needs to stay on a single level for ~9.1 hours (or ~4459701.8 years).  Third, the omega cannon discharges faster than it can recharge, so even when the first bug allowed it to charge while firing, a player could still drain Omega_charge to zero by continuous firing.  However, it would take longer to drain due to the bug-induced concurrent recharge, and would not be subject to the 1/3 second wait normally imposed between depleting Omega_charge and recharge beginning.

**Comment by vLKp** [comment]
```c++
#include <cstdio>

int last_fire;
long t64;
/* The test program only shows the bug on 64-bit systems */
static_assert(sizeof(last_fire) == 4, "sizeof(int) != 4");
static_assert(sizeof(t64) == 8, "sizeof(long) != 8");

void frame(bool expect_recharge, const unsigned line)
/* clang does not support __builtin_LINE, so fake it with a macro
 */
#define frame(E)    frame(E, __LINE__)
{
		if (last_fire > t64)
		{
				printf(__FILE__ ":%u:%u:                        last_fire=%8x t64=%16lx: last_fire > t64, resetting\n", __LINE__, line, last_fire, t64);
				last_fire = t64;
		}
		const int time_bias = 0x5555;
		if (last_fire + time_bias > t64)
		{
				printf(__FILE__ ":%u:%u: %5sexpect_recharge=%i last_fire=%8x t64=%16lx: last_fire recent (%16lx), refusing to recharge\n", __LINE__, line, expect_recharge ? "BUG: " : "", expect_recharge, last_fire, t64, static_cast<long>(last_fire + time_bias));
				return;
		}
		printf(__FILE__ ":%u:%u: %5sexpect_recharge=%i last_fire=%8x t64=%16lx: last_fire old    (%16lx), recharging\n", __LINE__, line, expect_recharge ? "" : "BUG: ", expect_recharge, last_fire, t64, static_cast<long>(last_fire + time_bias));
}

int main(int, char **)
{
		frame(false);
		t64 = 0x7fff;
		frame(true);
		last_fire = t64 - 4;
		frame(false);
		t64 = 0x7fffaaab;
		frame(true);
		last_fire = t64;
		++t64;
		frame(false);
		t64 = 0x7ffffffffd;
		frame(true);
		last_fire = t64;
		++t64;
		frame(false);
		t64 += 0x10000;
		frame(true);
		t64 = 0x7fffffffffffff00;
		frame(true);
		last_fire = t64;
		frame(false);
		t64 = 0x8000000000000000;
		frame(true);
		t64 += 0x800000000;
		frame(true);
}
```

```
a.cpp:16:24:      expect_recharge=0 last_fire=       0 t64=               0: last_fire recent (            5555), refusing to recharge
a.cpp:19:26:      expect_recharge=1 last_fire=       0 t64=            7fff: last_fire old    (            5555), recharging
a.cpp:16:28:      expect_recharge=0 last_fire=    7ffb t64=            7fff: last_fire recent (            d550), refusing to recharge
a.cpp:19:30:      expect_recharge=1 last_fire=    7ffb t64=        7fffaaab: last_fire old    (            d550), recharging
a.cpp:19:33: BUG: expect_recharge=0 last_fire=7fffaaab t64=        7fffaaac: last_fire old    (ffffffff80000000), recharging
a.cpp:19:35:      expect_recharge=1 last_fire=7fffaaab t64=      7ffffffffd: last_fire old    (ffffffff80000000), recharging
a.cpp:19:38: BUG: expect_recharge=0 last_fire=fffffffd t64=      7ffffffffe: last_fire old    (            5552), recharging
a.cpp:19:40:      expect_recharge=1 last_fire=fffffffd t64=      800000fffe: last_fire old    (            5552), recharging
a.cpp:19:42:      expect_recharge=1 last_fire=fffffffd t64=7fffffffffffff00: last_fire old    (            5552), recharging
a.cpp:19:44: BUG: expect_recharge=0 last_fire=ffffff00 t64=7fffffffffffff00: last_fire old    (            5455), recharging
a.cpp:10:46:                        last_fire=ffffff00 t64=8000000000000000: last_fire > t64, resetting
a.cpp:16:46: BUG: expect_recharge=1 last_fire=       0 t64=8000000000000000: last_fire recent (            5555), refusing to recharge
a.cpp:10:48:                        last_fire=       0 t64=8000000800000000: last_fire > t64, resetting
a.cpp:16:48: BUG: expect_recharge=1 last_fire=       0 t64=8000000800000000: last_fire recent (            5555), refusing to recharge
```

**Comment by zicodxx** [comment]
I think the easiest fix would be to change Last_omega_fire_time to fix64 as well (which I should have done when introducing GameTime64) and rework it to be Next_omega_fire_time similar to the Next_laser/missile_fire_time which should react properly to a reset of GameTime64. 

In that regard, I wonder how I missed the Omega. It's possible that I wrote the GameTime64 implementation on base of Descent 1 first and copied it over which would have been a bad idea. In that case the Descent 2-exclusive Afterburner and/or Headlights may suffer from similar issues.

**Comment by vLKp** [comment]
That would be a quick fix, but I would like to fix this properly.  In particular, I want to get away from the hack of resetting it when it is in the future and instead reset it on game load.  I think that, since this counts down from a small maximum, my pending fix will resolve this cleanly and simply.

**Comment by vLKp** [comment]
[Track omega recharge delay as relative time](/dxx-rebirth/dxx-rebirth/commit/7064a56788b64b08e7e56456a86c93dfc28f5478) should resolve this.
