### ISSUE TITLE
Robot earthshaker megas are missing

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#273]
When a robot fires an earthshaker missile, no homing blue mega missiles are produced. This can be tested with the final level of Descent 2: Counterstrike. Also, when a robot is meant to fire the blue mega missile directly (like on Gradius 3D Level 6 approaching the red entrance - can provide if required), it doesn't fire anything.

It seems a `weapon_id_type::ROBOT_EARTHSHAKER_MEGA_ID` a.k.a `59` is missing.

**Comment by vLKp** [comment]
I concur.  I will whitelist this ID and add a print statement to record any other weapons that are suppressed due to missing ID handling.

**Comment by vLKp** [comment]
[Print warning for unhandled weapon types](/dxx-rebirth/dxx-rebirth/commit/e56160a0210ead85ea03146cd7c44c584392060a) should make any other missing identifiers obvious as users play.

[Add ID for robot earthshaker secondary missile](/dxx-rebirth/dxx-rebirth/commit/a129a0d570853a39abd338f897081d0be1d4ee3c) should fix this problem.

**Comment by kreatordxx** [comment]
Thanks, I can confirm it works as well.
