### ISSUE TITLE
Scons not finding physfs.h on Mac OS X Yosemite

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#28]
I ran Scons from the Terminal on Mac OS X Yosemite and get this error:

scons: *** Header physfs.h is missing or unusable.  See build/d1x-rebirth-opengl/sconf.log for details.  Stop.

In sconf.log it says (amongst the build commands) "fatal error: 'physfs.h' file not found".

I downloaded the PhysicsFS 2.0.3 tarball, ran CMake (version 3.1), chose the 'Unix Makefiles' option and ran 'make' then 'make install' as per the instructions. It reported no errors and said it put physfs.h in /usr/local/include/physfs.h and libphysfs.dylib in /usr/local/lib/libphysfs.dylib (confirmed in the Mac's Finder).

I tried running 'scons sconf_libphysfs 1' and 'scons sconf_libphysfs 2' and they gave the same result, as if it ignored my override.

**Comment by vLKp** [comment]
Your compiler should be searching **/usr/local/include** on its own.  Please post the full build command shown in sconf.log.

**Comment by kreatordxx** [comment]
I figured it out. I had to install the Apple command line tools, even though I'd installed Xcode from the App Store. This added /usr/include, so the compiler searched that and /usr/local/include. That would be worth noting in INSTALL.txt if we make one. I'll note it in my personal 'To Do' list.
