### ISSUE TITLE
Some Menus Take ~1 Second to Exit on Windows

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#285]
When compiled for Windows, some menus take a little bit to exit. The easiest place to see this is the main Options menu on D2. If you enter it, then press Esc. it will take almost a second before it actually closes. This issue seems worse on D2 than D1. Also I haven't noticed this on Linux.

**Comment by vLKp** [comment]
As you noted, this seems not to happen on Linux.  As such, I cannot debug it.  Can you provide any more details about this, such as the first bad commit, or where the game is paused during that one second?

**Comment by Mako88** [comment]
Testing this today, the issue is no longer there. Closing.
