### ISSUE TITLE
Compiler does not like overloading of '=' for ntstring (on Yosemite)

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#30]
I came across this compile error:
> Compiling d1x-rebirth . similar/main/config.cpp
> similar/main/config.cpp:105:27: error: no viable overloaded '='
>         GameCfg.CMLevelMusicPath = "descent.m3u";
>         ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
> common/include/ntstring.h:9:7: note: candidate function (the implicit copy
>       assignment operator) not viable: no known conversion from
>       'const char [12]' to 'const ntstring<1023>' for 1st argument
> class ntstring :
>       ^
> common/include/ntstring.h:9:7: note: candidate function (the implicit move
>       assignment operator) not viable: no known conversion from
>       'const char [12]' to 'ntstring<1023>' for 1st argument
> class ntstring :
>       ^
> 1 error generated.

Looks like Apple's Clang++ is a bit more fussy about type conversion or something. (I remember adding M3U support ages ago, so am more familiar with this code if it helps.)

**Comment by vLKp** [comment]
I think this is not a compiler issue.  It's just an OS X specific bug, since the offending line is guarded by `#if defined(__APPLE__) && defined(__MACH__)`, which is never set on non-OS X platforms.

**Comment by vLKp** [comment]
This should be fixed by f0b47829efa7e911544c0a2e147331ccf0693bb6.

**Comment by kreatordxx** [comment]
Thanks, I can confirm this is fixed.
