### ISSUE TITLE
Debugger breakpoint hit when client dropped from a multiplayer game

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#303]
Steps to reproduce (**master**):
1. Launch one instance of D2X-Rebirth
2. Host a multiplayer game (choose defaults)
3. Launch a second instance of D2X-Rebirth (e.g. launch with debugger in Xcode)
4. Manually join multiplayer game using 42425 or (some other number) for 'my port'
5. Host starts game
6. Host kicks other player (press F8, type "/kick: <player name>" and hit enter)
7. Second instance clears the 'you got kicked' message

Immediately I get the debugger breaking at this line multiple times:
`draw_weapon_info_sub(player_info, info_index, box, pic_x, pic_y, PRIMARY_WEAPON_NAMES_SHORT(weapon_num), text_x, text_y, multires_gauge_graphic);`
in similar/main/gauges.cpp.

The value of `weapon_num` is the poisoned value of `0xfd`.

Exactly the same thing happens if the second player is dropped due to timeout.

Note this occurs before commit 0c5a000328058e18791aabc22d055cd27b6d2f61 (not merged into **master** at time of posting).

**Comment by vLKp** [comment]
The debugger trap at step 7 is probably the `d_debugbreak` triggered by trying to name a weapon with an invalid type code.  I suggest printing the entire structure of the affected player when this happens.  I expect you will find that parts of it are garbage bytes.

**Comment by kreatordxx** [comment]
Whoops, it looks like this is actually two bugs, with one of them much simpler than I first thought. Rewriting the first description and posting a second bug report.
