### ISSUE TITLE
Bald guy easter egg crashes D1X-Rebirth (applicable to Mac D1 full version data)

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#315]
Playing D1X-Rebirth with the full version Mac data, I hit ALT-B during a briefing screen. Instead of showing Dravis wearing a silly hat, it crashes D1X-Rebirth.

This was reported by @roncli.

**Comment by vLKp** [comment]
Is this a regression relative to 0.58.1?  Briefing memory management has been cleaned up a bit, but briefings are comparatively lightly touched.

**Comment by kreatordxx** [comment]
Actually, I wonder if this ever worked with D1X-Rebirth. When I try with 0.57.3 it crashes or skips the rest of the briefing. 0.55 was the first one to have this feature, but I can't get the source to compile.
