### ISSUE TITLE
Error upon compiling current master

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#316]
I was updating to 986e8f01a892efbd2512fd5d94a9f8e66a01d58b this morning and I noticed that as of right now, I am unable to compile master using scons without further arguments:
```
In file included from common/include/physfs-serial.h:11:0,
                 from similar/main/fuelcen.cpp:44:
common/include/serial.h: In instantiation of ‘serial::detail::sign_extend_type<extended_signed_type, wrapped_type> serial::sign_extend(wrapped_type&) [with extended_signed_type = int; wrapped_type = const short unsigned int]’:
similar/main/fuelcen.cpp:830:1:   required from here
common/include/serial.h:184:19: error: useless cast to type ‘const short unsigned int&’ [-Werror=useless-cast]
  using base_type::base_type;
                   ^~~~~~~~~
common/include/serial.h:339:11: note: synthesized method ‘serial::detail::sign_extend_type<int, const short unsigned int>::sign_extend_type(const short unsigned int&)’ first required here 
  return {t};
           ^
common/include/serial.h: In instantiation of ‘serial::detail::sign_extend_type<extended_signed_type, wrapped_type> serial::sign_extend(wrapped_type&) [with extended_signed_type = int; wrapped_type = short unsigned int]’:
similar/main/fuelcen.cpp:830:1:   required from here
common/include/serial.h:184:19: error: useless cast to type ‘short unsigned int&’ [-Werror=useless-cast]
  using base_type::base_type;
                   ^~~~~~~~~
common/include/serial.h:339:11: note: synthesized method ‘serial::detail::sign_extend_type<int, short unsigned int>::sign_extend_type(short unsigned int&)’ first required here 
  return {t};
```

**Comment by vLKp** [comment]
I edited your report to use \``` instead of \` to quote the error.  Using a bare \` causes Github to flow all text together in one long blob.  Using \``` preserves the original whitespace and newlines.

As for the problem report itself - the code works for me as is.  I can build [0.59.100-142-g38b3381](/dxx-rebirth/dxx-rebirth/commit/38b33819a562d641a2ec566633f5280562ac41f6) with no warnings and no errors using `x86_64-pc-linux-gnu-g++-5.4.0`.

Does the below patch make a difference for you?  The code builds for me with and without it.

```diff
--- a/common/include/serial.h
+++ b/common/include/serial.h
@@ -336,7 +336,7 @@ using pad = detail::pad_type<amount, value>;
 template <typename extended_signed_type, typename wrapped_type>
 static inline detail::sign_extend_type<extended_signed_type, wrapped_type> sign_extend(wrapped_type &t)
 {
-	return {t};
+	return t;
 }
 
 #define DEFINE_SERIAL_UDT_TO_MESSAGE(TYPE, NAME, MEMBERLIST)	\
```

**Comment by vLKp** [comment]
Are you trying to use gcc-6.x?  There is a [known regression in gcc-6.x](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70844) that produces output consistent with your error report.  This is not the first time that gcc 6.x has had a regression relative to 5.x that affected my code.

**Comment by zicodxx** [comment]
Thank you for the commit. I was indeed using gcc 6.3.1 and it seems that was the issue. Your commit seemed to have fixed that one. 

Sorry for reporting back so late. I got a new workload and will keep me occupied until the end of the month. :(
