### ISSUE TITLE
Mac Beta?

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#325]
I see we're up to BETA 1 (i.e. second beta), is it worth me providing a Mac OS X package for this or wait until the next beta release? I sorted out the Mac framework issues a while ago (a framework is a directory containing the library executable and headers).

Most Mac users won't build from source AFAIK.

**Comment by Mako88** [comment]
I'm hoping Beta 2 will be here within a week-ish, so I'd say hold off till then.

**Comment by vLKp** [comment]
Beta 2 seems to be a bit late.  The multiplayer protocol was most recently changed in [Add experimental MP-aware mouselook](/dxx-rebirth/dxx-rebirth/commit/d5ed019014e8eb4ad1602da3f0eff34a7facfab8).  A beta built off the latest code would not be able to play with the beta that zico released last year.

**Comment by Mako88** [comment]
Starting this evening I will be releasing weekly builds for people to try out. I'd like to know what your thoughts might be on how to handle Mac builds @kreatordxx? I doubt that there will be a stable release for a while, so this is something we'll have to figure out :)

**Comment by kreatordxx** [comment]
I'm fairly busy for the next couple of weekends so I might provide start providing builds after that.

**Comment by Thorworx** [comment]
fwiw, I'm definitely interested in any Mac beta builds.
Currently still running v0.58.1

**Comment by Havner** [comment]
I've managed to build latest git on OSX if that is of interest to anyone. It required one simple fix (pull request provided). I've also found 2 bugs that are not there in windows nightly. One reported, for the other I need to make some screenshots.

**Comment by kreatordxx** [comment]
Sounds good, I thought there would be more fixes required (haven't tested yet).

**Comment by kreatordxx** [comment]
Just tried to build the latest master then and I get this error:

```
CXX dxx . common/arch/cocoa/messagebox.mm
In file included from common/arch/cocoa/messagebox.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:48:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:12:9: fatal error: 
      'CoreGraphics/CGBase.h' file not found
#import <CoreGraphics/CGBase.h>
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [common/arch/cocoa/messagebox.o] Error 1
scons: building terminated because of errors.

```

This was after upgrading to Mac OS X 10.12.

**Comment by Havner** [comment]
I’m still on 10.11. Works fine there.

Have you updated XCode and all it’s surroindings (launched it once after the update). Once in my life I has a situation where after updating OSX XCode from Mac App Store did not realize there was a new bersion. I had to remove it and reinstall to get new one.

Somehow I doubt that Apple would start removing cocoa headers. If they did it must be mentioned somewhere in the docs.

**Comment by kreatordxx** [comment]
Yes I'm using Xcode Version 9.2 (9C40b).

**Comment by Havner** [comment]
Clarification. When I wrote I was on 10.11 I was actually on 10.12.6 (Sierra). And it worked fine for me.

Few days ago I upgraded to 10.13.2 (High Sierra).

Again, for _anything_ to work properly I had to completely remove XCode (even though this time it really was the newest version, 9.2). I installed it again from AppStore. Launched it once, it installed some additional stuff. I did "xcode-select --install" afterwards (as always), but this time it said everything is already installed.

And with such a setup I managed to compile dxx properly. Again, all SDL deps from MacPorts.

**Comment by Havner** [comment]
```
         name /usr/lib/dyld (offset 12)
         name /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (offset 24)
         name /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (offset 24)
         name /opt/local/lib/libSDL_mixer-1.2.0.dylib (offset 24)
         name /opt/local/lib/libSDL-1.2.0.dylib (offset 24)
         name /opt/local/lib/libphysfs.1.dylib (offset 24)
         name /usr/lib/libSystem.B.dylib (offset 24)
         name /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (offset 24)
         name /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (offset 24)
         name /usr/lib/libc++.1.dylib (offset 24)
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
         name /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (offset 24)
         name /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (offset 24)
         name /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (offset 24)
         name /usr/lib/libobjc.A.dylib (offset 24)

```

**Comment by kreatordxx** [comment]
Thanks @Havner, I'll try that.

**Comment by kreatordxx** [comment]
I ran `xcode-select --install` and it worked! Was I the one that wrote that into INSTALL.markdown? I believe I was :P

**Comment by kreatordxx** [comment]
If I make a Mac beta, which checkout should I use if I sync with a Windows / Linux beta? Or shall I use current **master**?

**Comment by kreatordxx** [comment]
Just answered my own question: checked out [the website](http://www.dxx-rebirth.com/download-dxx-rebirth/) and made a build for BETA 1 and for the latest weekly build (8 November). Emailed these to @zicodxx just then.

**Comment by Mako88** [comment]
I'm replying to this to let @kreatordxx know that beta 2 was just released: https://github.com/dxx-rebirth/dxx-rebirth/releases/tag/0.60.0-beta2

If you could make a Mac build of that tag and send it to me, I'll get it up on the website. Zico is currently on a hiatus, so sending it to me will get it published sooner :)

**Comment by MaddTheSane** [comment]
I'm getting the beta to compile on my Mac: It ran into issues with the physfs header. I had to pass `-D__EMX__=0 -Dsun=0` to the CPPFLAGS, otherwise Clang bails:

    /opt/local/include/physfs.h:232:29: error: '__EMX__' is not defined, evaluates to 0 [-Werror,-Wundef]

**Comment by Mako88** [comment]
@MaddTheSane That's a bug in the physfs.h file as far as I know. You can fix it by modifying the line:
`#elif ((__GNUC__ >= 3) && (!__EMX__) && (!sun))`

And replacing it with
`#elif ((__GNUC__ >= 3) && (!defined __EMX__) && (!defined sun))`

**Comment by kreatordxx** [comment]
Here it is:
[dxx-rebirth_v0.60BETA2-mac.dmg.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/1945396/dxx-rebirth_v0.60BETA2-mac.dmg.zip)

It may be unzipped before publishing (adds 2 MB).

**Comment by Mako88** [comment]
This has finally been added. I'm sorry it took so long!

I'll close this issue and open a new one when beta 3 (or RC 1, or whatever) comes out :)
