### ISSUE TITLE
Boss Looping Sound Doesn't Play when Saved Game Loaded

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#326]
When loading a saved game for a level with a boss, the boss has to teleport again before the looping sound is played again. This happened with the original too.

It seems the intention was for the boss to play the looping sound after it has teleported at least once. I would argue this should be the case for if the boss teleported before the loaded state was saved. However, since this would change game semantics slightly, posting an issue.

**Comment by vLKp** [comment]
I agree with your argument.  In my opinion, saving and restoring should have no observable effects on the game play.  Any place where the results differ if the player saves, quits, and later loads are likely an indication of a bug.
