### ISSUE TITLE
High FPS bug

### ISSUE THREAD

**Issue by Keith94** [dxx-rebirth/dxx-rebirth#339]
>At very high FPS (> 150), some robots with movable joints may twist those erratically after a player hit and consecutively take a few moments longer to recover. This bug was already present in the original engine.

Has this issue been addressed or is it being tracked currently? Also are there other FPS bugs to be aware of?

**Comment by Mako88** [comment]
That was issue #275 and has been fixed. The open github issues are a good way to track all known bugs, so as far as I'm aware there are no other FPS bugs currently. :)

**Comment by Keith94** [comment]
Good to know, thanks. :)
