### ISSUE TITLE
Could not set 800x600x32 opengl video mode

### ISSUE THREAD

**Issue by mysterywave** [dxx-rebirth/dxx-rebirth#342]
I tried to run the game after compiling, but I keep getting this error. 

```
Type ./d1x-rebirth -help' for a list of command-line options.

D1X-Rebirth v0.58.1  Feb 19 2017 15:39:10
This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
Copyright (c) 1994 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 2005-2011 Christian Beckhaeuser

Using SDL_mixer library
sdl-joystick: found 0 joysticks

Error: Could not set 800x600x32 opengl video mode: Couldn't find matching GLX visual
```

I really want to play this game, but it won't work! Any idea at all as to what this could be? :/

**Comment by vLKp** [comment]
Rebirth delegates to SDL for some aspects of graphics, including this.  The error message you quoted says that there was no matching GLX visual.  This error message is set by SDL, not by Rebirth.  What GLX visuals do you have available?  Does OpenGL work for other games on this system?  Does `glxgears` run without diagnostics?  Are you able to run Rebirth in a window?  What is the output of `xrandr -q ; glxinfo`?

Also, please note that 0.58.x is very old.  0.58.1 was released more than 4 years ago.  All new development occurs on `master`.

**Comment by vLKp** [comment]
Issue is likely with local configuration, not a code issue.  No response from reporter in just under 2 months.  Closing as NEEDINFO.

OP: if this is still an issue for you, please reopen and address the questions I posed above.

**Comment by ukos-git** [comment]
@vLKp I have the same issue and could provide info if you are willing to reopen the issue.

The error is occuring in `ogl_init_window` on [similar/arch/ogl/gr.cpp:368](https://github.com/dxx-rebirth/dxx-rebirth/blob/master/similar/arch/ogl/gr.cpp#L368) when calling `SDL_SetVideoMode`

```
similar/arch/ogl/gr.cpp:368: ogl_init_window: error: Could not set 1920x1080x32 opengl video mode: Couldn't find matching GLX visual
```

I compiled from current master on ubuntu 17.10 (kernel 4.13)

I use an amd graphics card (with amdgpu driver):
```
$lspci | grep -i VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460] (rev cf)
```
 glxgears is working just fine:
```
$ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
348 frames in 5.0 seconds = 69.470 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 456 requests (35 known processed) with 0 events remaining.
```

**Comment by vLKp** [comment]
I have no objection to reopening this.  Could you answer the remaining questions I posed to the original reporter?

* What GLX visuals do you have available?
* Does OpenGL work for other games on this system?
  * Of those OpenGL games that work, do any of them use SDL?  (This question is not stated above, but should have been.)
* What is the output of `xrandr -q ; glxinfo`?

**Comment by ukos-git** [comment]
eduke32 is running like a flaw using sdl2. Should I search for another game?

I have only tested d1. It worked previously on the same system but I think I never had it running on the new tv screen. Maybe the old screen setting is confusing the launcher. Other recent update regarding graphics is the change to wayland.

Here is some output:

[the output of glxinfo](https://pastebin.com/Gtw53EZ0)

```
$ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
365 frames in 5.0 seconds = 72.796 FPS
300 frames in 5.0 seconds = 59.998 FPS
```
```
$ xrandr
Screen 0: minimum 320 x 200, current 7680 x 2160, maximum 8192 x 8192
XWAYLAND0 connected 3840x2160+1920+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     59.98*+
XWAYLAND1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     59.96*+
XWAYLAND4 connected 1920x1080+5760+0 (normal left inverted right x axis y axis) 1080mm x 610mm
   1920x1080     59.96*+
```
```
$ apt list --installed | grep sdl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libsdl-mixer1.2/artful,now 1.2.12-14 amd64 [installed]
libsdl-mixer1.2-dev/artful,now 1.2.12-14 amd64 [installed]
libsdl-net1.2/artful,now 1.2.8-5 amd64 [installed,automatic]
libsdl-sound1.2/artful,now 1.0.3-8 amd64 [installed,automatic]
libsdl1.2-dev/artful,now 1.2.15+dfsg2-0.1 amd64 [installed]
libsdl1.2debian/artful,now 1.2.15+dfsg2-0.1 amd64 [installed]
libsdl2-2.0-0/artful,now 2.0.6+dfsg1-3ubuntu1 amd64 [installed]
libsdl2-dev/artful,now 2.0.6+dfsg1-3ubuntu1 amd64 [installed]
libsdl2-mixer-2.0-0/artful,now 2.0.1+dfsg1-3 amd64 [installed,automatic]
libsdl2-mixer-dev/artful,now 2.0.1+dfsg1-3 amd64 [installed]
libsdl2-ttf-2.0-0/artful,now 2.0.14+dfsg1-2 amd64 [installed,automatic]

```

```
$ ./d1x-rebirth-debug
PHYSFS: failed to append canonical directory "~/.d1x-rebirth/data" to search path from relative name "data": "File not found"

Type '/media/games/exec/dxx-rebirth/d1x-rebirth/d1x-rebirth -help' for a list of command-line options.

D1X-Rebirth v0.59.100 0.59.100-719-g8838b46e65c8  Oct 22 2017 16:06:54
This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
Copyright (C) 1994, 1995 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 2005-2013 Christian Beckhaeuser
D1X-Rebirth built with PhysFS 2.0.3; loaded with PhysFS 2.0.3
D1X-Rebirth built with libSDL 1.2.15; loaded with libSDL 1.2.15
D1X-Rebirth built with SDL_mixer 1.2.12; loaded with SDL_mixer 1.2.12
Getting settings from DESCENT.CFG...
Using SDL_mixer library v1.2.12
sdl-joystick: 1 joysticks
sdl-joystick 0: Logitech Logitech Cordless RumblePad 2
sdl-joystick: 4 axes
sdl-joystick: 12 buttons
sdl-joystick: 1 hats
sdl-joystick: 4 axes (total)
sdl-joystick: 16 buttons (total)
Going into graphics mode...
similar/arch/ogl/gr.cpp:368: ogl_init_window: error: Could not set 1920x1080x32 opengl video mode: Couldn't find matching GLX visual

./d1x-rebirth-debug: line 3:  6583 Aborted                 (core dumped) /media/games/exec/dxx-rebirth/d1x-rebirth/d1x-rebirth -use_players_dir -debug -verbose -safelog -hogdir /media/games/data/d1x-rebirth

```

**Comment by vLKp** [comment]
As I noted above, Rebirth delegates to SDL for its graphics work.  Rebirth uses SDL-1.x, not SDL-2.x as eduke does.  I don't see anything in that output that suggests an explanation for the problem, nor anything that suggests any code change to Rebirth that could resolve your problem.  The abort at the end is expected when you hit a call to `Error`; failing to set the video mode causes such a call.

Some initial Google searches suggest that GLX and Wayland are not drop-in compatible.  I don't have a Wayland environment to test that suggestion, nor to debug any problems associated with using Rebirth+SDL+Wayland.

I suggest you seek support from someone more familiar with GLX/Wayland.  If you can describe a code change that would mitigate this problem for other users, I will look at including it in the main code base.  Other than that, there is nothing I can do to help you at this time.  Sorry.

**Comment by vLKp** [comment]
No further response from either reporter.  No indication that this is a game bug, nor an issue that the game can work around.  Closing.

As above, if anyone has specific suggestions on what to investigate in the game, or specific changes to make to the game, please reopen.
