### ISSUE TITLE
[D2X nightly] Crash on starting a new Vertigo game

### ISSUE THREAD

**Issue by Havner** [dxx-rebirth/dxx-rebirth#343]
Latest nightly (the one including thief bot update, have not tried earlier ones) crashes for me when starting a new Vertigo game.
1. Start new game
2. Select vertigo
3. Briefings start
4. Crash
```
similar/main/titles.cpp:1282: load_briefing_screen: error: Error loading briefing screen <arcan01.pcx>, PCX load error: Error opening file. (1)
```
Dropping in BETA1 binaries makes everything work fine again.

**Comment by vLKp** [comment]
Confirmed broken by [Simplify get_message_num](/dxx-rebirth/dxx-rebirth/commit/1335af4b5127688e1d8654a1e42f066ce452d8b3).  [Fix crash loading Vertigo briefing](/dxx-rebirth/dxx-rebirth/commit/7c0cdd6c518602bb3539e6528000ef69100ddf87) fixes this for me.  Please sync to that commit (or later) and retest.

**Comment by Havner** [comment]
Confirmed fixed. Thank you.
