### ISSUE TITLE
Broken save game icons (mini screenshots) after 8aadb4be5b5336290f74c9205da7f4297be40e3c

### ISSUE THREAD

**Issue by Havner** [dxx-rebirth/dxx-rebirth#354]
When saving a game and then loading it back the mini screenshot icons (on the savegame list screen) are complete white. Sometimes they flicker with some random data.

**Comment by Havner** [comment]
![screen shot 2017-11-06 at 00 37 26](https://user-images.githubusercontent.com/6246347/32420456-d8caaf8a-c28a-11e7-9188-df831ce8adab.png)

Not necessarily white, sometime brown. But always garbage.

**Comment by vLKp** [comment]
First bad commit is [Use fill_n instead of inline loop to write scanline](/dxx-rebirth/dxx-rebirth/commit/8aadb4be5b5336290f74c9205da7f4297be40e3c).

[Fix savegame thumbnail previews](/dxx-rebirth/dxx-rebirth/commit/ff49e949d4bd1d588bc5ce306b94f19fa96751c1) fixes this for me.

**Comment by Havner** [comment]
Confirmed fixed.
