### ISSUE TITLE
Mac OS X Build Error in similar/main/weapon.cpp

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#368]
I just built the latest git commit e08ea9f29ae2fc74f9fec194648154cb37a4d00a and I get this error:
```
similar/main/weapon.cpp:829:29: error: lambda capture 'weapon_index' is not used
      [-Werror,-Wunused-lambda-capture]
        const auto want_switch = [weapon_index, weapon_order, &secondary_ammo, &Secondary_weapon]{
                                  ^

```

**Comment by vLKp** [comment]
[Fix clang build of similar/main/weapon.cpp](/dxx-rebirth/dxx-rebirth/commit/64690c3ce88098eb7411bac8bf57663f80c81997) should resolve this.

**Comment by kreatordxx** [comment]
Thanks, now it compiles past this file.
