### ISSUE TITLE
Mac OS X Build Error in d2x-rebirth/main/escort.cpp

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#369]
I built the latest commit f869a16e35e2e5e72014e0b154ea26005f00e0a3 and it fails with this error:
```
CXX d2x . d2x-rebirth/main/escort.cpp
d2x-rebirth/main/escort.cpp:374:30: error: format string is not a string literal
      [-Werror,-Wformat-nonliteral]
    vsnprintf(buf, sizeof(buf), fmt, vl);
                                ^~~
1 error generated.

```

**Comment by vLKp** [comment]
This is strange.  That has been there for a while.  It should not suddenly break for you.  (If it were to fail, it should have failed in any build after Mar 27, including the one you did yesterday.)  Arguably, it should not break at all.  Using a non-literal format for `snprintf` is rare and usually wrong.  Using it for `vsnprintf` is entirely normal.  I can try to suppress this by adding an `__attribute__((format(printf)))` to advise clang that the format will be checked by the caller, but I don't know if that will work.

**Comment by vLKp** [comment]
[Mark buddy_message_* functions as printf format](/dxx-rebirth/dxx-rebirth/commit/25d623fac524863add9a739d3bc865581c1335fa) should fix this.

**Comment by kreatordxx** [comment]
Clang does produce some strange warnings sometimes, it was probably just because I updated Xcode (now have Clang Apple LLVM version 9.1.0 (clang-902.0.39.1)).

Fixed - closing.
