### ISSUE TITLE
Clang ICE while compiling similar/main/net_udp.cpp

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#37]
This was first seen on Linux with clang v3.4 and has now been [reported by btb](https://github.com/dxx-rebirth/dxx-rebirth/pull/35) as affecting clang v6 on OS X.  The [call stack](https://github.com/dxx-rebirth/dxx-rebirth/pull/35#issuecomment-73350066) in both cases shows a problem generating one of the template forwarding functions.  This seems to be because clang attempts to resolve a trailing return decltype on a function it has not yet instantiated, leading to a null pointer dereference.  As a workaround, I previously wrote a change to derive the return type from elsewhere in the hierarchy.  The patch was set aside because it made the code ugly and at the time only an already outdated clang was known to be affected.

**Comment by vLKp** [comment]
@kreatordxx @btb, would one of you mind reporting this ICE to Apple so it can be fixed for the next release?

**Comment by btb** [comment]
I have reported it, #19755642 - not that you can do much with that number.

**Comment by vLKp** [comment]
Thanks.  I take it the bug tracking system for that report requires some sort of Apple-specific account to read?

**Comment by btb** [comment]
More than that, even when you sign in, you can only see the bugs you reported yourself.

**Comment by vLKp** [comment]
I see.  Thanks for reporting this to Apple.

Commit a64bce8e265da40644cbc1f660f80de2f38b3af0 fixed this for Linux/clang-3.4.  From the call stack, I expect it will fix the crash on OS X also.  If this commit works for you, I will resolve the ticket as fixed.

**Comment by btb** [comment]
This does fix it for me, thanks.

**Comment by vLKp** [comment]
@btb: did Apple ever address this?  We will carry the workaround regardless.
