### ISSUE TITLE
Beta 2: FPS issues

### ISSUE THREAD

**Issue by roncli** [dxx-rebirth/dxx-rebirth#378]
On Windows, I am experiencing an FPS hovering between 185 and 190, dependent on how much is getting rendered.  It almost seems like something happened with the FPS counter that is preventing it from going the full 200.

It also sounds like I'm not alone, I was talking to @Mako88 earlier about it and he mentioned there were people reporting this as well.

I haven't tried a whole lot of things to see what happens, please let me know if you want me to try anything.

**Comment by vLKp** [comment]
On release builds, I got up to 196 FPS in spot testing.  In debug builds, which have a much looser cap, I got near 984 FPS at maximum.

All game actions should be scaled such that FPS is irrelevant.  Aside from the reporting difference, are there any gameplay problems?  When did this change?

**Comment by roncli** [comment]
If it's not nearly constantly 200, then something changed with the frame
rate between 0.58.1 and 0.60 beta 2.  My guess is the method of calculating
the timing between frames changed somewhere.  If I get a chance I can look
at it closer since I'm somewhat familiar with how it worked in 0.58.1.

I don't know exactly when it changed, as I don't keep up with the weekly
builds. This is a report from testing that @Mako88 requested specifically
for beta 2, not something I've meticulously tested and observed over time.

I know in 0.58.1 higher frame rate improved multiplayer performance since
multiplayer things are sent in the frame they happen and not between
frames.  I imagine that hasn't changed for 0.60.  In single player it
theoretically shouldn't be an issue.

**Comment by derhass** [comment]
Well, one thing which did change and which could influence this is the GL synchronization code. You can try if running the game with `-gl_syncmethod 0` does change the behavior you observe. Note that even if the default `SYNC_GL_FENCE_SLEEP` mode is the "culprit", it would still be working exactly as intended. One thing we could consider is using `SYNC_GL_NONE` by default when vsync is not activated.

However, this is all a moot point. If (and that's a very big if)  lower frametimes in the order of single milliseconds or fractions thereof actually improve multiplayer gameplay in any observable way, then the 200fps cap in release builds should simply be increased.

**Comment by derhass** [comment]
> I dug into the code a bit. The GL synchronization code I don't think will change anything (and indeed it did not for my teseting).

Yeah, I can confirm this.  With disabled VSync (which I otherwise never do), I get constant 200fps with 0.58.1, but 193-196 with more current versions, and the `-gl_syncmethod` has no influence on this. SInce I contributed the sync code, this means I'm probably not responsible for this effect... :)

> Really the only way to figure THAT out would be to start going back to older builds to see where the FPS loss began. 

That's what `git bisect` is for, and due to binary search, it  will be quite efficient. Since I can reproduce the problem, I will try to do that later, and see where it ends up.

**Comment by derhass** [comment]
OK, I did some bisecting. Unfortunately, there are many intermediate versions which just didn't build (with gcc-6.3 from debian stable), so I had to hack around a bit. Furthermore, the unification brach branched off before 0.58.1, so 0.58.1 is not a true ancestor to the current versions. However, I did end up with something:

```
a04aa340c50456630cd8ba52774702c8c751e94f is the first bad commit
commit a04aa340c50456630cd8ba52774702c8c751e94f
Author: zico <zico@dxx-rebirth.com>
Date:   Mon Dec 9 16:28:34 2013 +0100

    Keep multi frame running during game idle events to decrease delay on packet forwarding
```

This is the first commit after which the constant 200fps goes down. BUT... it is not going down to the ~194 I see with recent versions, but it is going down to ~150fps for me, so I guess this behavior was later adjusted. I'm trying to biscet also the 150 -> 194 fps change...

**Comment by derhass** [comment]
OK, now I also found the 150 -> 194 fps change:

```
commit ff331732bac421edc4d7c81547c176b2ab119f6a
Author: zico <zico@dxx-rebirth.com>
Date:   Mon Aug 29 16:04:46 2016 +0200

    Re-enabled timer_delay2 for general menu handlers and adjusted them to sleep according to set FPS and not sleep at all for Multiplayer since calc_frame_time() is active in that case. Modified sleeping towards 1ms in calc_frame_time() to allow for more precise target FPS and be able to relay packets in multiplayer with less delay.
```

So to me, both changes all seem intentional and benign. 

> I know in 0.58.1 higher frame rate improved multiplayer performance since
multiplayer things are sent in the frame they happen and not between
frames.  I imagine that hasn't changed for 0.60.

In contrast to 0.58.1, the game will also handle multi-player packets during the wait enforced by the FPS limiter, so the issue you suspect here is probably just not really there. To me, this looks like a cosmetic issue.

There is still one thing I wonder: Maybe it would be a good idea to also call `multi_do_frame()` in the wait loop of `SYNC_GL_FENCE_SLEEP` wait loop. When playing without vsync, it would probably not make a big difference, but with vsync enabled, it could have some relevant benefits in multiplayer.

**Comment by roncli** [comment]
I will try to build from that commit and the parent commit and see if that's actually what's causing the FPS.  For the record, it's 200 (not 150) to 185-190 on my machine, and it sounds like it's machine dependent.

**Comment by derhass** [comment]
> For the record, it's 200 (not 150) to 185-190 on my machine, and it sounds like it's machine dependent.

Well, as I said, identified  3 different behaviors, which transition 200 -> ~150-166 -> ~193 on my machine.

> There is still one thing I wonder: Maybe it would be a good idea to also call multi_do_frame() in the wait loop of SYNC_GL_FENCE_SLEEP. When playing without vsync, it would probably not make a big difference, but with vsync enabled, it could have some relevant benefits in multiplayer.

I did prepare this and created pull request #382 with my suggested change.

**Comment by roncli** [comment]
Ah, got it.

It looks like what's happening is that something in calc_frame_time takes a significant fraction of a millisecond and that is throwing off FPS timing.  Therefore, the proper fix will be to fix the timing, which can be found in PR #383. :)

**Comment by vLKp** [comment]
roncli wrote:
> I wouldn't think moving from C to C++ would've caused this, but I wouldn't rule that out without testing.

On its own, I wouldn't expect that to be a problem.  However, the move to C++ did enable me to write quite a few other changes that would have been much more trouble to write in straight C.  Some of those changes could be responsible.

derhass wrote:
> Unfortunately, there are many intermediate versions which just didn't build (with gcc-6.3 from debian stable)

I adjust the code for newer gcc versions as I get to them, but if you need to go into history, gcc-4.9 or gcc-5 is probably a better choice.

**Comment by roncli** [comment]
> On its own, I wouldn't expect that to be a problem. However, the move to C++ did enable me to write quite a few other changes that would have been much more trouble to write in straight C. Some of those changes could be responsible.

Fortunately derhass was able to rule that out. :D
