### ISSUE TITLE
Crash: Unhandled argument "-psn_0_1831359" while processing <command line>

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#387]
### Environment
Commit c4417aafb1fff5ab5b703a340a24d741649bc389.

#### Operating System Environment

* Mac OS X
  * [x] Mac OS X 10.13

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description
When DXX-Rebirth is double clicked in the Finder, I get the error message "similar/misc/args.cpp:478: Unhandled argument "-psn_0_1831359" while processing \<command line\>".

#### Regression status

After running `git bisect` the commit c4417aafb1fff5ab5b703a340a24d741649bc389 was identified to be the cause. This is pull request #376.

### Steps to Reproduce
1. Launch D1X-Rebirth or D2X-Rebirth from the Finder.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

What would be the best way to handle this argument?

**Comment by vLKp** [comment]
As I read the code, when the OS X specific logic detects a Finder launch, it is supposed to discard all command line arguments.  If you get this error, that suggests `main` is passing through the Finder arguments to the common code.  If so, then I think the fix is to understand why SDLMain.m is passing arguments it ought to be discarding and change it not to pass them.

**Comment by vLKp** [comment]
Assigning to @kreatordxx since this is OS X specific and no one else on the core team has a Mac with which to test.  Per my comment above, I think the right fix is to understand how this argument reaches the core code and prevent that from happening, so that the core code needs no changes.

**Comment by kreatordxx** [comment]
Actually, I think the best fix would be to modify `PHYSFSX_init`, in particular the Mac OS X specific code - so that it explicitly adds the base directory to the search path, rather than `''`.

When I wrote the Mac code, I was relying on `SHAREPATH` being set to `''` and using `chdir` to change to the application directory. This no longer appears to work, and in hindsight is a bit hackish. I'm not sure why it works when DXX-Rebirth is tricked into thinking it's not a finder launch in SDL_main.m, I will need to investigate further. Ran out of time so just putting my 2c here for now.

**Comment by kreatordxx** [comment]
Update: It looks like I will need to ship DXX-Rebirth with PhysicsFS 3 so that `PHYSFS_getBaseDir()` will work properly. BETA 2 was shipped with PhysicsFS 2.

**Comment by vLKp** [comment]
The opening comment and the title say the ticket is about Mac Rebirth rejecting the Finder-generated command line argument.  Your more recent comments discuss Mac Rebirth reacting badly to Finder starting the program with an unhelpful current working directory.  Aside from the connection that Finder is making life difficult, I don't understand how the first problem and the second problem relate.  I thought the first problem killed the program before the second problem could matter.

The base directory is already added to the search path, although the current code then removes it soon after.  Would it be sufficient to make the removal conditional on `!defined(__APPLE__)`?

https://github.com/dxx-rebirth/dxx-rebirth/blob/0b026b628243f7305745ae344117626a8a20ce24/similar/misc/physfsx.cpp#L196-L199

----

If you do not want to add a blank `SHAREPATH` to the PHYSFS search path, the below patch should work.  I have not tested it to see if it breaks anything.

```diff
diff --git a/SConstruct b/SConstruct
index 860375850..b5fb80938 100644
--- a/SConstruct
+++ b/SConstruct
@@ -4508,7 +4508,10 @@ class DXXProgram(DXXCommon):
 		env = self.env
 		env.MergeFlags(archive.configure_added_environment_flags)
 		self.create_special_target_nodes(archive)
-		env.__dxx_CPPDEFINE_SHAREPATH = [('SHAREPATH', self._quote_cppdefine(self.user_settings.sharepath, f=str))]
+		sharepath = self.user_settings.sharepath
+		# Must use [] here, not (), since it is concatenated with other
+		# lists.
+		env.__dxx_CPPDEFINE_SHAREPATH = [('SHAREPATH', self._quote_cppdefine(sharepath, f=str))] if sharepath else []
 		env.Append(
 			CPPDEFINES = [
 				self.env_CPPDEFINES,
diff --git a/similar/main/inferno.cpp b/similar/main/inferno.cpp
index 4c2e623ad..41c497066 100644
--- a/similar/main/inferno.cpp
+++ b/similar/main/inferno.cpp
@@ -426,8 +426,14 @@ static int main(int argc, char *argv[])
 #if defined(__unix__) && !defined(__APPLE__)
 #define DXX_HOGFILE_PROGRAM_DATA_DIRECTORY	\
 			      "\t$HOME/.d" DXX_NAME_NUMBER "x-rebirth\n"	\
+					DXX_HOGFILE_SHAREPATH_INDENTED
+#ifdef SHAREPATH
+#define DXX_HOGFILE_SHAREPATH_INDENTED	\
 			      "\t" SHAREPATH "\n"
 #else
+#define DXX_HOGFILE_SHAREPATH_INDENTED
+#endif
+#else
 #define DXX_HOGFILE_PROGRAM_DATA_DIRECTORY	\
 				  "\tDirectory containing D" DXX_NAME_NUMBER "X\n"
 #endif
diff --git a/similar/misc/physfsx.cpp b/similar/misc/physfsx.cpp
index aa9e9cac9..66b0d41d8 100644
--- a/similar/misc/physfsx.cpp
+++ b/similar/misc/physfsx.cpp
@@ -213,7 +213,7 @@ bool PHYSFSX_init(int argc, char *argv[])
 		con_printf(CON_DEBUG, "PHYSFS: append argument hog directory \"%s\" to search path", p);
 		PHYSFS_addToSearchPath(p, 1);
 	}
-#if defined(__unix__)
+#ifdef SHAREPATH
 	else if (!CGameArg.SysNoHogDir)
 	{
 		con_puts(CON_DEBUG, "PHYSFS: append sharepath directory \"" SHAREPATH "\" to search path");
```

**Comment by kreatordxx** [comment]
How about checking for a `SHAREPATH` of `"."` and if it's that, add the base directory to the search path? That way DXX-Rebirth could be built on Linux with a `SHAREPATH` of `"."` and that would mean add the base directory, rather than the current directory (which could be whatever the user is working on at the time).

This would still only apply when `SysHogDir` is empty and `SysNoHogDir` is false. Before SCons, `SHAREPATH` was set to `"."` for Mac and this worked.

**Comment by vLKp** [comment]
> Pull request #376 is the cause of this crash

What crash?  You still have not shown a backtrace or identified a faulting function.  In the case of unhandled arguments, the program should exit gracefully after reporting the argument as unhandled.  If the program is aborting due to an unhandled argument, that is a bug.  If the program is exiting gracefully due to an unhandled argument, that is not a crash.

> How about checking for a `SHAREPATH` of `"."` and if it's that, add the base directory to the search path?

It would be more flexible to define a separate mechanism rather than overloading `SHAREPATH`.  Although PhysFS tries hard to guess a directory based on heuristics (`argv[0]`, `/proc/self/exe`), in the general case, there is no guaranteed way to get a "base directory" on Linux.

Instead of overloading `SHAREPATH`, I could add something like:

```c++
#if DXX_SEARCH_PHYSFS_BASE_DIRECTORY
    if (const auto d = PHYSFS_getBaseDir())
        PHYSFS_addToSearchPath(d, 0);
#endif
```

> Before SCons, `SHAREPATH` was set to `"."` for Mac and this worked.

`SHAREPATH` can still be set to `"."` on the Mac and likely will work, due to the hack in `PHYSFSX_init`.

https://github.com/dxx-rebirth/dxx-rebirth/blob/0b026b628243f7305745ae344117626a8a20ce24/similar/misc/physfsx.cpp#L104
https://github.com/dxx-rebirth/dxx-rebirth/blob/0b026b628243f7305745ae344117626a8a20ce24/similar/misc/physfsx.cpp#L126

**Comment by kreatordxx** [comment]
> If the program is exiting gracefully due to an unhandled argument, that is not a crash.

Yes it is exiting due to an unhandled argument - on the Mac this gives an alert message rather than the crash log.

> `SHAREPATH` can still be set to `"."` on the Mac and likely will work, due to the hack in `PHYSFSX_init`.

OK I might investigate doing this, because it will result in less changes to the code.
