### ISSUE TITLE
Folder support in the new game screen

### ISSUE THREAD

**Issue by jcotton42** [dxx-rebirth/dxx-rebirth#392]
It would be nice for the New Game level list to understand folders, so that instead of having one massive list the levels could be categorized into groups by the folder structure.

**Comment by vLKp** [comment]
The New Game list does understand directories.  When searching for missions, it will recursively explore discovered directories and add missions found in those subdirectories.  Is this feature not working for you?  What directory structure did you use where it did not work?

**Comment by jcotton42** [comment]
I meant something like this from D2X-XL. The top-level screen ![top-level screen](https://user-images.githubusercontent.com/5257450/42073003-09934ec8-7b32-11e8-8627-886dc6c09e26.png) shows the subdirs of the missions folder. 
Going into the folder ![Going into the folder](https://user-images.githubusercontent.com/5257450/42073024-1a8387ca-7b32-11e8-8ac2-382f356980e7.png) shows only the missions inside that folder

Sorry about taking so long to reply, the spam filter on my email is overly sensitive.

**Comment by vLKp** [comment]
Two weeks is fine.  I don't retire tickets very aggressively and people are always welcome to reopen them if they were closed due to unresponsiveness.

That request makes sense.  I'll look into it.

**Comment by vLKp** [comment]
[Retain directory structure in New Game dialog](/dxx-rebirth/dxx-rebirth/commit/d97afc2ad50027cf3acf5acde3f573c4b5589464) is an initial implementation of this.  Feedback welcome.

**Comment by jcotton42** [comment]
Are you still doing weekly builds? I noticed the latest one is from April, and when I tried to cross-compile Rebirth using the MinGW compiler it fell on its face.

**Comment by vLKp** [comment]
I have never done weekly builds.  @Mako88 did nightly builds that later became weekly builds, and more recently irregularly scheduled(?) builds.  I am not aware of any change of plans from them being weekly, but I am also not aware of any more recent than the April build you found.

Cross-compiling to Windows works for me in [tip](/dxx-rebirth/dxx-rebirth/commit/d97afc2ad50027cf3acf5acde3f573c4b5589464).  There were some problems with it recently (#393), but those are fixed now.  If it still fails for you, please file a separate issue and we can work through the problem(s).

**Comment by vLKp** [comment]
This is implemented and has received no negative feedback (or any feedback) to date.  Closing.

If the current implementation is insufficient, please reopen and explain what needs to change.
