### ISSUE TITLE
SDL2: Mouse can hit edge of screen during play

### ISSUE THREAD

**Issue by heftig** [dxx-rebirth/dxx-rebirth#397]
### Environment

c65020bf041a52806b90d0bd527570dad64f6bfa

#### Operating System Environment

* [x] Arch

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description

During play, the mouse cursor can (invisibly) hit the edge of the screen, preventing further movement. SDL1 prevents this be moving the cursor to the center of the screen after every frame; this is noticeable when opening the menu using ESC. SDL2 seems to be missing this behavior.

#### Regression status

Only happens when SDL2 is used.

### Steps to Reproduce

`scons sdl2=True`

- Start a new game and attempt to spin in circles using the mouse.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player

**Comment by vLKp** [comment]
Confirmed.  Grabbing the mouse implicitly handled this in SDL1.  SDL2 mouse grabs keep the mouse in the window, but does not prevent the problem you reported.  An extra call to opt in to alternate mouse motion handling is required.

[SDL2: set relative mouse mode when grabbing the mouse](/dxx-rebirth/dxx-rebirth/commit/25ab07bcc5aac160f1f72d5d10e8513df4df9d98) fixes this for me.

**Comment by vLKp** [comment]
Proposed fix worked for me and confirmed working by another user (though not yet confirmed or rejected by the original reporter).  Closing.

@heftig: please reopen if the cited commit does not resolve the problem.
