### ISSUE TITLE
d1x-rebirth - cannot pass exit door

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#40]
During a Mulitplayer test I noticed I cannot pass the opened EXIT door in d1x-rebirth. d2x-rebirth works fine. Also I can shoot through but attempting to pass it with the player ship blocks as if the door was closed. It also triggers the HUD message that the door is locked.

**Comment by vLKp** [comment]
Confirmed.  For __Descent: First Strike__ level 1, the exit door is `Walls[6]`, starts with `->flags` of `WALL_DOOR_LOCKED` and changes to `WALL_DOOR_OPENED | WALL_DOOR_LOCKED` when the reactor blows.  The exit code checks for `->flags & WALL_DOOR_LOCKED` first, which triggers the lock message even when the door is open.

**Comment by vLKp** [comment]
This was broken in fd01d4c6737e1352ce3727d9f52b5c2ba658c386 by moving
```c++
	if (likely(type == WALL_DOOR) && unlikely(w.state == WALL_DOOR_OPENING))
		return WID_TRANSPARENT_WALL;
```
above
```c++
	if (unlikely(flags & WALL_DOOR_OPENED))
		return WID_TRANSILLUSORY_WALL;
```
Desent 1 exit doors have the confusing state of `type == WALL_DOOR, flags == WALL_DOOR_OPENED | WALL_DOOR_LOCKED, state == WALL_DOOR_OPENING`.  In Descent 2, exit doors briefly have that state as they open, then change to have `state == WALL_DOOR_OPEN`.
