### ISSUE TITLE
"too many blown bitmaps" after long time in level in MP coop

### ISSUE THREAD

**Issue by josefjahn** [dxx-rebirth/dxx-rebirth#404]
### Environment

https://www.dxx-rebirth.com/download/dxx/user/afuturepilot/dxx-rebirth_v0.60-beta-2-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent: First Strike Missions 1 and 4 tested in multiplayer coop. 

### Description

Game crashes with the error "too many blown bitmaps"

#### Regression status

Unknown

### Steps to Reproduce

Create a multiplayer coop game with default settings, start the mission, and then leave the game running for an hour or two
 
* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [X] Multiplayer cooperative

(Other modes not tested)

* Players affected by issue:
  * [X] Game host
  * [ ] Game guests

[2018-09-02-16-52-18 x86 P3464 D1X-Rebirth v0.59.100 0.59.100-851-g48b31d84f344.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/2349423/2018-09-02-16-52-18.x86.P3464.D1X-Rebirth.v0.59.100.0.59.100-851-g48b31d84f344.zip)

**Comment by vLKp** [comment]
This is likely not directly about time.  The only site that can abort with that exception runs in response to multiplayer game synchronization.  You probably crashed because something triggered the game to begin synchronization.

This appears to be a duplicate of #402, which is itself a duplicate of a forum post from several months ago.  [Improve error handling/reporting for excessive blown bitmaps](/dxx-rebirth/dxx-rebirth/commit/cec95741ab22ebc7e06fdeb264fa61ef1511ebe4) fixed this problem in May.  The build you used is quite old.  Please update to a newer commit.

**Comment by josefjahn** [comment]
Sorry for the duplicate then! I shall try this with the latest daily and report back.

**Comment by vLKp** [comment]
No need to apologize.  Of the three reports, yours is the first to include the exact error message in the subject line.  In affected builds, only one location can generate that error.  In corrected builds, there are no sites that can generate the error.  Thus, it was easy to recognize that the report was a duplicate.

I think the latest daily snapshot for Windows is quite out of date.  @Mako88 said he would resume posting them, but does not appear to have done so yet.  You will likely need to build the code locally if you want something new enough to contain the fix.

**Comment by josefjahn** [comment]
Roger that. And I read your response just as I came back to the last windows snapshot crashing ;)
Unfortunately I am not yet able to build on Windows myself, but the linux/raspi build does compile. 

I think since you're already having this bug, and most likely already fixed it, I'm closing this one.
