### ISSUE TITLE
 0.60 beta 2 - Can't launch d1x nor d2x

### ISSUE THREAD

**Issue by enderandrew** [dxx-rebirth/dxx-rebirth#406]
### Environment

https://www.dxx-rebirth.com/download/dxx/user/afuturepilot/dxx-rebirth_v0.60-weekly-04-14-18-win.zip

#### Operating System Environment

* Microsoft Windows
  * [x] Microsoft Windows 10

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

#### Game environment

Doesn't launch to get to any particular portion of the game

### Description

Neither d1x-rebirth.exe nor d2x-rebirth.exe will launch. Compatibility options in Windows 10 don't help either.

This is what appears in the Windows Event Viewer:

Faulting application name: d1x-rebirth.exe, version: 0.0.0.0, time stamp: 0x5ad29161
Faulting module name: ntdll.dll, version: 10.0.17754.1, time stamp: 0xcee84e63
Exception code: 0xc0000005
Fault offset: 0x0004f1e5
Faulting process id: 0xa794
Faulting application start time: 0x01d44e2b8914dff8
Faulting application path: D:\Games\D1X-Rebirth\d1x-rebirth.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: f8874862-b2e4-4eab-a92b-6240c46a87fe
Faulting package full name: 
Faulting package-relative application ID:

#### Regression status

d1x/d2x-rebirth_v0.58.1-win however launches just fine.

### Steps to Reproduce

Attempt to launch

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

**Comment by enderandrew** [comment]
No output when attempting to launch via command window.

Nothing in stderr.txt nor stdout.txt.

**Comment by vLKp** [comment]
Thank you for providing the Windows Event Viewer data.  As I read that, it is blaming a system library (ntdll.dll) for an invalid memory access.  Unfortunately, there is nothing I can do about it with the information provided.  Such crashes in ntdll.dll are usually an indication of memory corruption elsewhere, which only became fatal when ntdll.dll tried to use the corrupted memory.  Unless you can trace the memory corruption to its source, I cannot fix the source (and the source may not even be under my control, if it comes from some other library on your system, such as your graphics driver).  At this point, all I can offer is that other people have run the game without this problem, from that build.  Presumably, some of them are on Windows 10.

Have you ever run that build successfully on any Window 10 machine?  If so, how do the systems differ?  Can you reboot into a different version of Windows and test whether the game runs there?

\[This response cross-posted to the [thread you posted on the Rebirth forum](https://forum.dxx-rebirth.com/showthread.php?tid=1084).  There's no need to post so many places.  I read them all.]

**Comment by vLKp** [comment]
No response from reporter after one week.  Not reproducible locally.  No indication in the original report that this is a Rebirth bug, rather than a system problem.  There is nothing I can do with the information available.  Closing.

Please reopen if you can provide actionable information.
