### ISSUE TITLE
Pausing movie causes segfault

### ISSUE THREAD

**Issue by Jayman2000** [dxx-rebirth/dxx-rebirth#410]
### Environment

git commit fe77949a824e23e7237fd5994a06f6ab072ee271
#### Operating System Environment

* Ubuntu
  * [x] Ubuntu 18.04 LTS (Bionic Beaver)

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

#### Game environment

Descent I and II : the Definitive Collection version of Descent 2 (and Vertigo)
### Description

Pausing the intro cut scene causes an unavoidable segfault. 
#### Regression status

Does not happen in the Ubuntu package for d2x-rebirth (version 0.58.1-1.1). Does happen in git version fe77949a824e23e7237fd5994a06f6ab072ee271.
### Steps to Reproduce

1. Run d2x-rebirth.
2. Press the Pause key while the intro is still playing.
3. Press any key.
#### Expected behavior
The movie unpauses.
#### Observed behavior
The game skips the rest of the movie, going straight to the Descent II logo. Once the "Select Pilot" screen appears, the game closes. Here is the full terminal output:
```
jayman@Jason-Desktop-Linux:~/.local/opt/dxx-rebirth/d2x-rebirth$ ./d2x-rebirth 

Type './d2x-rebirth -help' for a list of command-line options.

D2X-Rebirth v0.59.100 0.60.0-beta2-182-gfe77949a824e  Vertigo Enhanced  Oct  9 2018 14:31:34
This is a MODIFIED version of Descent 2, based on Full Version v1.2.
Copyright (C) 1994-1996 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 1999 Peter Hawkins, 2002 Bradley Bell, 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
Using SDL_mixer library v1.2.12
sdl-joystick: 2 joysticks
sdl-joystick 0: Razer Razer Hydra
sdl-joystick: 5 axes
sdl-joystick: 10 buttons
sdl-joystick: 1 hats
sdl-joystick: 5 axes (total)
sdl-joystick: 14 buttons (total)
sdl-joystick 1: Logitech Gamepad F710
sdl-joystick: 6 axes
sdl-joystick: 11 buttons
sdl-joystick: 1 hats
sdl-joystick: 11 axes (total)
sdl-joystick: 29 buttons (total)
DXX-Rebirth: OpenGL: disabling automatic GL sync since VSync is turned off
Segmentation fault (core dumped)
jayman@Jason-Desktop-Linux:~/.local/opt/dxx-rebirth/d2x-rebirth$ 
```

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

**Comment by vLKp** [comment]
Confirmed.  The movie code assumes that when the topmost window is closed, that window must have been the movie window, and that the movie data can now be freed.  However, if the movie is paused, a new topmost window is created to tell the user that the movie is paused.  When that topmost pause window is deleted, the movie code frees the movie data, even though the movie is not done.  Corruption ensues, ultimately leading to a crash.

I can reproduce the problem in the cited commit.  I cannot reproduce the problem after applying the fix in [Fix crash after pausing movie](/dxx-rebirth/dxx-rebirth/commit/787d95241cba4a2ddc625e5886626564b5358710).  Please test whether this is sufficient for you as well.

**Comment by Jayman2000** [comment]
[That commit](https://github.com/dxx-rebirth/dxx-rebirth/commit/787d95241cba4a2ddc625e5886626564b5358710) fixed the issue.
