### ISSUE TITLE
d2x-rebirth crashes when the .mvl files are present

### ISSUE THREAD

**Issue by jwrdegoede** [dxx-rebirth/dxx-rebirth#413]
Hello,

With d2x-rebirth build on Linux from the stable-0.60.x branch, commit b43a351aa90d125a034e68e8b5762ea2dd8bcb93 it crashes when I place the mvl files from the gog descent2 version in my $HOME/.d2x-rebirth directory (where I also have the 6 pig files, and descen2.hog,ham,s11,s22).

This is with d2x build with SDL-1.2 and no special options, I've tried both opengl=0 and opengl=1 builds.

If I remove the .mvl files everything is fine, if I have them in place I get the following error:

/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::const_reference = const unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Here is a backtrace of the crash under gdb:

(gdb) bt
#0  0x00007ffff761b53f in raise () from /lib64/libc.so.6
#1  0x00007ffff7605895 in abort () from /lib64/libc.so.6
#2  0x00000000004ed903 in std::__replacement_assert (__condition=0x4ff380 "__builtin_expect(__n < this->size(), true)", __function=<synthetic pointer>, __line=950, __file=0x500520 "/usr/include/c++/8/bits/stl_vector.h")
    at /usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2391
#3  std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:950
#4  mvefile_get_next_segment_major (movie=<optimized out>) at d2x-rebirth/libmve/mvelib.cpp:128
#5  0x00000000004eda39 in mvefile_get_next_segment (movie=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:948
#6  0x00000000004edf89 in mve_play_next_chunk (movie=movie@entry=0x11af590) at d2x-rebirth/libmve/mvelib.cpp:234
#7  0x00000000004ef4f3 in MVE_rmPrepMovie (pMovie=std::unique_ptr<MVESTREAM> = {...}, src=<optimized out>, x=x@entry=-1, y=y@entry=-1) at d2x-rebirth/libmve/mveplay.cpp:722
#8  0x00000000004f3e6f in RunMovie (filename=<optimized out>, must_have=<optimized out>, hires_flag=<optimized out>, dy=-1, dx=-1) at /usr/include/c++/8/bits/unique_ptr.h:342
#9  0x00000000004f42ef in PlayMovie (subtitles=subtitles@entry=0x507a1f "intro.tex", filename=filename@entry=0x507a15 "intro.mve", must_have=must_have@entry=1) at d2x-rebirth/main/movie.cpp:179
#10 0x00000000004cb783 in d2x::show_titles () at similar/main/titles.cpp:262
#11 0x00000000004176af in d2x::main (argv_gd$=<optimized out>, argc_gc$None=<optimized out>) at similar/main/inferno.cpp:544
#12 main (argc_gc$None=<optimized out>, argv_gd$=<optimized out>) at similar/main/inferno.cpp:699

Regards,

Hans

**Comment by jwrdegoede** [comment]
p.s. This is on Fedora 29 x86_64 with gcc-8.2.1

**Comment by vLKp** [comment]
Confirmed, but only if assertions or libstdc++ debugging are enabled.  [Fix off-by-one in mvelib processing](/dxx-rebirth/dxx-rebirth/commit/8db88cb2b56d683a1aa8c5ba4201eda20d28b23f) fixes this for me.  Please reopen if this does not resolve the problem for you.

**Comment by jwrdegoede** [comment]
I can confirm that the "Fix off-by-one in mvelib processing" commit fixes this for me.

Thank you for the quick fix.
