### ISSUE TITLE
Regression: OpenGL: artifacts in font rendering when using "smooth" filter

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#415]
### Environment

Self compiled, git commit `3a6bfb8dd621fe469064db5379151f15fdae967f`

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [x] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Affects any font rendering.

### Description

All OpenGL font rendering (menus, weapon text, player names, everything)  is broken when using the _smooth_ texture filter mode. The border of each glyph is visible with strange colors, as in the following screenshot:

![artifacts_crop](https://user-images.githubusercontent.com/1835702/54575403-46316180-49f4-11e9-8779-ce03e4f4771a.png)

(This screenshot was on NVIDIA 418.43 on a Geforce GTX1060).

#### Regression status

I bisected the issue and ended up with:
```
7bcbaae2306d2faa309324f72d2f4cf172c8b50b is the first bad commit
commit 7bcbaae2306d2faa309324f72d2f4cf172c8b50b
Author: Kp <kp@valhallalegends.com>
Date:   Sat Feb 2 18:36:39 2019 +0000

Tighten protection against grs_bitmap bm_data confusion
      
Bitmaps based on grs_main_bitmap own their data.  Bitmaps based on
grs_bitmap do not.  Adjust prototypes to prevent initializing a
grs_main_bitmap with data it will not own.

:040000 040000 24ef68b74d787201428af87c80994d19f4247ed7 937358d3d3c62827921a0d52453dad254bea90f1 M      common
:040000 040000 51d4d6d3a3a8b05a13b9f8ff1bf115d070943eca 3ce45dffa0808f5004fbcf55a81d3a2a4f7ef2fc M      similar
```

### Steps to Reproduce

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

(it is harder to see in d2x, especially due to the higher resolution menu fonts, but still there)

* Game modes affected:
  * all

**Comment by vLKp** [comment]
Confirmed.  I will try to resolve this soon.

**Comment by vLKp** [comment]
Thank you for bisecting this.  Code inspection of the commit you identified led me to the bug.

[Fix bogus borders due to fill_n length/value transposition](/dxx-rebirth/dxx-rebirth/commit/9bed4f6d78b91617dc3fdae8dd89f95f7a18d248) fixes this for me.  `memset` and `std::fill_n` use different orders for the length and value parameters and I failed to swap the order when I switched functions in the commit you identified.

Please reopen if this does not resolve the problem for you.
