### ISSUE TITLE
D1X-Rebirth crash during Descent 1 campaign briefing screens

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#420]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)

* [x] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

This problem occurs when playing the briefing of the Descent: First Strike campaign in D1X-Rebirth, namely when progressing to the second text block in the second briefing screen (office). D1X-Rebirth crashes with 
```
similar/2d/pcx.cpp:79: PCXHeader_read_n: error: reading at 0
```
caused by titles.cpp line 1329 calling pcx_read_bitmap which is passed an empty filename.

#### Regression status

According to git bisect, the issue was introduced in commit f8769b980594f6454dac449381dac504e042b8aa which does show changes in the function causing the issue.
I am not exactly sure, yet why exactly this causes an issue, but maybe you can help out a bit @vLKp.

### Steps to Reproduce

To reproduce, simply start the game, select Descent: First Strike and advance through the briefing as normal. When advancing text in the office scene, the game will crash.

* Engines affected:
  * [x] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by Dainslaif** [comment]
This does not happen to me using the latest public build on Windows 7, so it might be an OS-specific bug.

**Comment by vLKp** [comment]
I would start by tracing, in both a good build and a bad one, every write to `br->background`.  Collect for each of those two commits the file/line number of every change, and what value was written in each time.

**Comment by zicodxx** [comment]
I made a bit of progress in the investigation of this bug and I know what causes it, but I am not entirely sure why.
In load_briefing_screen, fname2 is declared as
```
auto &fname2 = br->background_name;
```
A few lines below, fname is copied into fname2 by 
```
snprintf(fname2, sizeof(fname2), "%s", fname);
```
After this happens, fname, fname2 and br->background_name are suddenly empty. I believe this may be because (correct me if I'm wrong) fname2 is a direct reference to br->background name while at the same time fname is already a reference to that as the failing function call comes from init_new_page calling 
```
load_briefing_screen(*grd_curcanv, br, br->background_name);
```
If I turn fname2 into char[16] as it was before and later copying that into background_name after the code decides if it's valid to add the h.pcx suffix to it using strncpy (which was the entire point in having fname2 to begin with), the issue is solved. 

I am pretty sure there is probably a better solution, that doesn't defeat half the point of the original commit that caused the issue, but it's not jumping at me right now.

**Comment by vLKp** [comment]
The standard says it is undefined to overlap the input and output buffers of `snprintf`, so yes, this code is wrong in [current master](/dxx-rebirth/dxx-rebirth/commit/65cd43e7d085bae1e3211fa1ecfaa6894f9cd1df) - for that one path.  Everywhere else, the buffer pointed at by `fname` is distinct from the buffer `br->background_name`, so those paths work fine.  There weren't any comments describing why `fname2` needed to be separate and I missed that there was one path that relied on a lack of aliasing.  I made it an alias so that I could eliminate a `strncpy` that reloaded `br->background_name` from `fname2` after all the other processing.  You'll probably resurrect a gcc-9 `-Wstringop-truncation` warning if you restore that `strncpy`, so be sure to test gcc-9 after fixing this.

If you'd prefer, I can try to solve this without reintroducing the gcc-9 issue.

**Comment by vLKp** [comment]
Please pull and retest.

**Comment by zicodxx** [comment]
@vLKp Thank you for checking this in. It actually fixes the issue for me. I tested it with both gcc 8.3.0 and 9.1.0 and weirdly enough, none of them brought up the warning you mentioned. At least not in titles.cpp - I did get that warning for gamepal.cpp (line 85 and 104). So that seems to look okay and I guess we can close this one. Thanks for the help, I appreciate it. :)

**Comment by vLKp** [comment]
Current code should build cleanly with gcc-9.  If it doesn't, please file an issue for me to investigate.
