### ISSUE TITLE
Crash: Loading old save file crashes D2X-Rebirth

### ISSUE THREAD

**Issue by Dainslaif** [dxx-rebirth/dxx-rebirth#421]
### Environment

Using current public build: https://www.dxx-rebirth.com/download/dxx/weekly/dxx-rebirth_20190523-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [x] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent 2: Counterstrike
Level: Omega System 3: Iwihml
descent2.hog size: 7418 KB (default hog file from Steam installation)

### Description

I have a save file from when I was playing through on the v0.60 Beta 2 build, whenever I open it up, the game crashes with the following exception;

"similar/main/ai.cpp:4830: invalid index used in array subscript: base=0000000000000000 size=350 index=65534"

#### Regression status

I am unsure if the crash existed prior to the current builds, I don't believe I've ever used that save file before as I had others that were farther along in the game.

### Steps to Reproduce

Unzip the attached badsave.zip file and place in the D2X folder. 
Create a new Pilot named badsave (or rename the save to an existing pilot) and try loading it.
Game immediately crashes.

I've also included the elog file, as instructed.
[badsave.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3214407/badsave.zip)

Playing through with cheats or creating a new save on Level 23 does not reproduce the issue.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
Based on the description, you have an active guidebot that is trying to reach an object that it cannot reach.  The original game defined `-2` to mean unreachable object, `-1` to mean no object, and non-negative numbers to refer to the corresponding object.  Your crash is because the newer validation only allows `-1` and non-negative numbers, but not `-2`.  This validation is too strict for this particular case, at least as long as the guidebot uses `-2`.  I will relax the check.

**Comment by vLKp** [comment]
Please update to a build that includes the above commit and try again.

As a workaround in the interim, load your save game with an older build, change the guidebot's goal to something it can reach, save, and switch back to the newer build.  If you choose this path, take care not to save while the guidebot has an unreachable goal.

If the problem persists after update, please reopen.
