### ISSUE TITLE
Addon- OPL3 Music causes no music

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#423]
OS: Windows 7 32 bit and 64 bit; Windows 10 64 Bit

D1x-Rebirth v0.61 v0.60 Beta 2 Build 5/23/2019:
*Descent does not play MIDI built in music, as well as addon opl3 music but works with Jukebox. Game does not crash, still has SFX runs at 200 FPS 
D2x-Rebirth v0.61 v0.60 Beta 2 Build 5/23/2019
*Descent 2 does not play opl3 addon music but works with Jukebox. When I remove the opl3 addon, MIDI built in plays. Game does not crash still has SFX

Myself and a fellow Descenter are experiencing the same exact issues. Both worked on v0.58.1
[gamelog.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3218322/gamelog.txt)

**Comment by zicodxx** [comment]
That one's on me. I forgot to include the DLLs needed for both OGG and FLAC playback. That should be fixed by next build on Thursday (May 30th)

**Comment by zicodxx** [comment]
The updated builds of today (2019/05/30) contain all necessary libraries to enable OGG and FLAC playback again.
