### ISSUE TITLE
Descent 1 Coop Loading Saved game bug Blue Boxes unable to shoot

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#424]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

Game environment: Descent First Strike 

Description: When loading a saved coop game on D1, Got blue boxes and red x's on cockpit and couldnt shoot. Flares failed to work as well. Secondaries show random numbers on how many I have
![coop d1 beta](https://user-images.githubusercontent.com/33588668/58364827-80e5c900-7e7f-11e9-891e-3f355a40acd1.jpg)

Steps to Reproduce: Save a coop game and load the saved game with cockpit on

* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [X] Multiplayer cooperative

* Players affected by issue:
  * [] Game host
  * [X] Game guests
[gamelog.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3219132/gamelog.txt)

**Comment by vLKp** [comment]
This works fine for me.  Please confirm which commit was used to build your game and, if the problem is present in a build from this month or newer, attach a savegame showing the issue.

**Comment by vLKp** [comment]
No response from reporter.  Unable to reproduce.  Closing.

Please reopen if you can reproduce this.
