### ISSUE TITLE
Runtime bug: Wrong object type in get_robot_id

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#429]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [ ] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

This happened with the current revision https://github.com/dxx-rebirth/dxx-rebirth/commit/e6716643327d7474fdb357bf6ddb9ed112d5b204 during playing Descent 2: Counterstrike Level 5. I only saw it in the logs after finishing my playsession, the following messages appeared in stdout:

```
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfc438 has type 4, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e16ff8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e092d8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e17568 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e027e8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e04fc8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e125a8 has type 7, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0aa68 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1cc68 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0c938 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e19d48 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e199a8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0e298 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e089c8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e08458 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfea48 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1ca98 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0d248 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e07978 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dff6f8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e10c48 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1c8c8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e16178 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1d008 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e04c28 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e01968 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0db58 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1c188 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e17ad8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfe878 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e13f08 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e10508 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfede8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e10e18 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e094a8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e18788 has type 7, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e15fa8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e111b8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e183e8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e080b8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e05198 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfec18 has type 7, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e09678 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e07ee8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e02448 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7dfe6a8 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e10fe8 has type 8, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0b548 has type 7, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e154c8 has type 1, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e08288 has type 1, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e0ae08 has type 5, expected 2
similar/main/ai.cpp:2886: BUG: object 0x5639f7e1ad98 has type 5, expected 2
```
Due to the circumstances of me only seeing it after finishing the session, I cannot really say where exactly in the level this happened and a quick replay of the level (with invulnerability cheat) I could not reproduce it, but it's possible that I just avoided the situation leading to the issue in the first place. This is also why I posted the entire list and not just a snippet of it - maybe it'll help to find the problem.

Since it's hard to reproduce, it makes it really hard for me to run a bisect on it, but considering the nature of this issue, I wouldn't be surprised that this is something potentially present in the original game already and now just popping up due to more verbose outputs.

### Steps to Reproduce

As said above, it's hard to reproduce, but this is what I did to first hit the issue:
1) Start D2X-Rebirth
2) Load a savegame of level 5
3) Potentially play through the secret level located near the player initial spawn (I doubt this is necessary to reproduce it, but I did this first when hitting this issue)
4) Play through the entirety of level 5

Sorry I cannot provide more info about this right now. I'll try and see if I can isolate it more.

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
It was present in the original game, but only became readily observable when [Warn on invalid object ID access](/dxx-rebirth/dxx-rebirth/commit/9f26e2211e71036a155aad9a7ca3ff92d7b49c3c) added the diagnostic message.  In this case, it's fully reproducible whenever you trigger `make_nearby_robot_snipe` with a non-robot `object` in the searched area.  It's easy to fix, and the above commit should do so.

Please reopen if you see this specific diagnostic from `make_nearby_robot_snipe` again.
