### ISSUE TITLE
MIDI output

### ISSUE THREAD

**Issue by nyov** [dxx-rebirth/dxx-rebirth#430]
On a debian Linux build of d2x-rebirth (D2X-Rebirth v0.58.1),
I can see that it is linked against `libfluidsynth.so.1`, and is using fluidsynth for mixing the midi output (through SDL_mixer?).  
However I was wondering how I could use an external MIDI server, with a custom soundfont.

This works for me on the original game in DOS (well, dosbox), setting the Music Card to 'General MIDI' and then running fluidsynth or timidity in server mode.

I couldn't find any possibility to have dxx output raw midi to a MIDI port, any chance this is possible? Much appreciated.

**Comment by nyov** [comment]
After a lot more searching, I found an SDL-mixer fork at https://github.com/WohlSoft/SDL-Mixer-X, which supports more MIDI options.
But that seemed cumbersome, because recompiling and different header name, etc.
Then, more searching led me to the older blog-post at https://duganchen.ca/playing-sdl_mixer-games-with-soundfonts/ which suggested modern SDL_mixer might recognize some options passed along as environment variables, though it didn't work for me.

Finally, some [SDL_mixer source-foo suggested](https://github.com/SDL-mirror/SDL_mixer/blob/master/music.c#L1072-L1073), that this should still work, but now needed some enforcing.

Finally, the command-line to use a custom soundfont with the SDL_mixer (which works for me) is this:  
```SDL_FORCE_SOUNDFONTS=1 SDL_SOUNDFONTS="/usr/share/sounds/sf2/SGM-V2.01.sf2" d2x-rebirth```
(provided the soundfont exists, of course).

Hope this might help someone else. Now closing this.

P.S. For those like me, who prefer the midi soundtrack to the CD audio, I find these are good ones for some variety: SGM-V2.01.sf2, TimGM6mb.sf2, GeneralUser-GS-v1.471.sf2 (search them).

**Comment by meyertime** [comment]
I hate to bump this old issue, but I'm trying to get MIDI playback in rebirth through fluidsynth now as well.  I'm on Arch Linux using [the AUR package](https://aur.archlinux.org/packages/d1x-rebirth/).

I'm wondering if you might have any insight into my issue since you got it working at one time.  Even if I pass the arguments you mentioned that work for you, there's no music.  In the console output, I see lines like:

```
Music descent.hmp could not be loaded: Module format not recognized
```

**Comment by nyov** [comment]
I just found some time to test this. Since I've never tried this with `d1x-rebirth`.
Looking at a debian package for d1, I can see that it is linked against fluidsynth (`ldd /usr/games/d1x-rebirth | grep fluid`) here (which I assume is used by SDL_mixer to render the MIDI), so I downloaded the D1 shareware/demo data and gave it a try.
I copied all the d1 data, specifically all the files that start like `DESCENT.*`, to `~/.d1x-rebirth/`.

And it seems to work just fine (there's a definitive difference to listen to the music rendered with different soundfont banks.), with basically the same startup commands as I used for D2.
```sh
#!/bin/sh

export SDL_FORCE_SOUNDFONTS=1
export SDL_SOUNDFONTS="/usr/share/sounds/sf2/GeneralUser-GS-v1.471.sf2"

exec /usr/games/d1x-rebirth
```
There is no `descent.hmp` in my D1 data - so either you're referring to D2 or you're trying to load D1 data with the D2-binary?
The MIDI is played through SDL_mixer, so having normal ALSA/pulseaudio set up should work fine.
For completeness sake, the startup log looks like this
```
Type /usr/games/d1x-rebirth -help' for a list of command-line options.

D1X-Rebirth v0.58.1  Aug  2 2020 09:16:13
This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
Copyright (c) 1994 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 2005-2011 Christian Beckhaeuser

Using SDL_mixer library
sdl-joystick: found 0 joysticks
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
```
Hope it helps. Sorry for the delay.

**Comment by nyov** [comment]
I guess it's easily possible that modern SDL_mixer removed some MIDI support code. I don't see why dxx would change too much in that regard.
If you just need a timidity config, try this:
```
# /etc/timidity/timidity.cfg
opt EFresamp=l
opt EFchorus=s
soundfont /usr/share/sounds/sf2/GeneralUser-GS-v1.471.sf2
#soundfont /usr/share/sounds/sf2/SGM-V2.01.sf2
```
In my experience, timidity usually did a better job and sounds better than fluidsynth (could be outdated info, though).
