### ISSUE TITLE
Runtime bug: Ship rocking effect is way too strong when blowing up reactor

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#431]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

Upon blowing up the reactor, the ship rocking effect is incredibly strong, even at reasonably low FPS (60), making escaping after destruction nearly impossible. 

#### Regression status

Looking at the changelog, this was incredibly easy to nail down to commit 644d6fa51350c0b2a407655b871f30b5b1f54a1a.

### Steps to Reproduce

1) Launch the game
2) blow up reactor

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [X] Multiplayer competitive
    * [X] Anarchy
    * [X] Team Anarchy
    * [X] Robo-Anarchy
    * [X] Capture the Flag
    * [X] Bounty
  * [X] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [X] Game guests

**Comment by vLKp** [comment]
I tried escaping on Rookie with that rocking effect.  It's difficult, but not that bad.  Even so, I will grant that this is a change from that commit.  I used `std::max` where I should have used `std::min`.

This should be fixed by the above commit.
