### ISSUE TITLE
Runtime bug: D2X-Rebirth can drop armed bomb in Singleplayer upon death

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#433]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [X] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

Upon the player death in Descent 2 Singleplayer, if the player has proximity bombs, an armed/active bomb may be dropped upon death.

#### Regression status

This is a regression introduced by the commit https://github.com/dxx-rebirth/dxx-rebirth/commit/829e95b6f818f82c1f90502f8a3a7002479b3802#diff-acb1ca5fb4a118ddf752dcea2ab440de and it doesn't look like if this change was intentional.

While it doesn't sound that big of a deal, I think this change should be reverted.
You can drop armed proximity bombs in (non-HOARD) Multiplayer - which makes sense, since another player may trigger them accidentally trying to collect the player loot. 

However, this doesn't happen in Singleplayer (as bots do not care for player loot), making this armed bomb a lost cause (unless you get lucky with the bot AI). I guess this is why the original code only allows to drop armed Smart bombs in Singleplayer since those will eventually explode and have a good chance to send homing projectiles towards enemies still lingering around in the area. So those seem to make more sense in the Singleplayer scenario.

### Steps to Reproduce

1) Start a singleplayer game
2) get yourself a bunch of proximity bombs
3) kill the player
4) you might observe armed/active proximity bombs in the player spew (these should only be present in non-HOARD Multiplayer modes)

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
Confirmed, that change was wrong, as you describe.  I will fix it.

**Comment by vLKp** [comment]
The above commit should resolve this.
