### ISSUE TITLE
Runtime bug: D1 Final boss doesn't teleport anymore (unless severely provoqued)

### ISSUE THREAD

**Issue by TheMiracleMatter** [dxx-rebirth/dxx-rebirth#434]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

All in the title, the behavior of the D1 boss is now much different: It used to teleport randomly between one of the four large sections of his room (referring to original level 27 of Descent: first strike) when in idle every 15-30 seconds (I don't remember exactly how much). I loved the element of surprise that brought the random teleportation and made the fight a lot better. Now with the newer builds (this one is the one I used [https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20190621-win.zip](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20190621-win.zip)), the final boss just sits there in the first room it spawned in eternally. When I shoot at it, it starts getting cloaked but unless I'm really aggressive and insistant (using an invulnerability orb), it doesn't even teleport and it just "uncloaks" a mere second after I stop firing and move out of the way. The final boss feels anemic/lazy/limp now.

#### Regression status

I know and clearly remember that it wasn't like that in the old 0.58.1 D1X-Rebirth (The latest one going all the way back to 2013). I haven't tried the 2019/05/30 release thought or any other commit... I may if I find the time soon enough.

### Steps to Reproduce

Simple. Just get to the red key door of level 27 and open it (hold it open). The loud living audio loop of the final boss is always heard coming from the same section of the room (the front-right one close to the red door which is also where the starting position of the boss is in SDLdevil... and it never changes. The boss will not teleport ever. You can verify that by peeking into the room section the audio loop is spacially coming from (and risk a very swift death by mega missiles). You may need to take an invulnerability orb to be able to continue attacking him long enough to finally get him to teleport otherwise he always sits there.

In the old version, you should hear very audible changes in intensity and direction of the living boss audio loop a few times every minute signalling his random teleportation between the four sections. (Easily observable from any hiding spot within the room).

* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [?] Multiplayer cooperative
(I don't know if Co-op is affected but I see no reason why it wouldn't be)

**Comment by vLKp** [comment]
Thank you for the report.  Without a specific commit that introduced this regression, I will need to spend some time debugging this.  It will likely be at least a few days before I can work on this.

**Comment by TheMiracleMatter** [comment]
Yeah, I'm sorry about that. However, I did try today two other versions available on the website: The newest one released yesterday and the oldest one of this year (released 2019/05/30) and the problem is exactly the same.

**Comment by vLKp** [comment]
I think I'm seeing the same problem, but I'm not sure.  I started a game on `Descent: First Strike` level 27, enabled the red key and an extra-long-lasting invulnerability through the developer menu, and went in.  I am getting pounded by missile fire from various spawned in robots, and the boss throws Mega missiles when it sees me.  It does teleport on its own, even though I'm not firing on it.  However, if I park in a quadrant where it can't see me, it doesn't seem to teleport to me ever.  I have to go peek at it, then it teleports.  Does that match what you see?

**Comment by vLKp** [comment]
I see a possible explanation.  In `do_d1_boss_stuff`, there is this check near the top:
https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/ai.cpp#L2494-L2495
This was added in [Fix D2 emulation of D1 boss teleport handling](/dxx-rebirth/dxx-rebirth/commit/8291391b7f9f54f711e5d6b3df43c94732e35ba2) (0.59.100-699-g8291391b7).  The change seems strange since this changes the semantics of the D1 boss in a D1 game.  I need to examine that area to see why this seemed like the right thing to do, because I did not intend to cause the change you reported.

**Comment by vLKp** [comment]
The above commit restricts the new rule to the D2 engine playing D2 levels.  When using the D1 engine, or when using the D2 engine to play a D1 level, boss robots should now teleport without regard to the test quoted above.

Please reopen if you continue to see problems in a build with this change, or if you believe this change is the wrong solution.

**Comment by TheMiracleMatter** [comment]
Nah, this change sounds good to me. Thank you for the swift fix ! When is the next release on dxx-rebirth.com ?

Also, I know of few very minor bugs (downright trivial) that barely affects gameplay. I don't want to bother you with more than the strict minimum but I wonder if actually you're in the position that no bug is too small to be bothered with.

**Comment by vLKp** [comment]
Recently, releases are built by @zicodxx.  For the last few weeks, zico has been posting new snapshot builds on Thursdays.

Some bugs may be too small to fix, but I'd like to know about the details before I decide not to fix them.  At nothing else, they should be mentioned in a document of known issues.  Go ahead and file reports for the ones you know, and we can discuss in those ticket(s) whether to document or fix.
