### ISSUE TITLE
Runtime bug: Player names not displaying in Multiplayer

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#435]
### Environment

The issue related to a build of the game compiled from the following commit ff9cff4fea8820c425fefd21ce68cc092e4dd457

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

In Multiplayer games, player names (your own as well as the names of other players) will not display in the player selection when forming the game, on the HUD during the game, kill messages ("was killed by ") and potentially other places.

#### Regression status

As stated above, the bug manifests in ff9cff4fea8820c425fefd21ce68cc092e4dd457.
Further investigation led me to a commit where the issue was apparently not present: 7e01a658c66ef13048d2035fc00f9062e21b1140.
Bisecting the issue blames the following commit:  0c7de10512101ee70ae3acae30e8a5d469565489

It took me a while to find this, so I didn't have the chance to investigate further, yet. :(

### Steps to Reproduce

1) Start the game
2) Select MULTIPLAYER and HOST a game
3) Upon the screen where you can select players, you will only see your rank but not the name of your player
4) press enter to start the game
5) on the HUD you should see your name and kill count/score (depending on mode), but you'll only see the latter - not the name itself

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [X] Multiplayer competitive
    * [X] Anarchy
    * [X] Team Anarchy
    * [X] Robo-Anarchy
    * [X] Capture the Flag
    * [X] Bounty
  * [X] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [X] Game guests

**Comment by vLKp** [comment]
The above commit should resolve this.  I think the actual first bad commit was [Reset definedness of per-game globals on new game](/dxx-rebirth/dxx-rebirth/commit/bea95ce1df86f643d0409896e93165ad3fea2583), since that introduced reinitialization of per-game globals.

Please reopen if the problem persists for you.
