### ISSUE TITLE
Runtime bug: (minor) Guide-Bot starts talking in certain layout before release

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#438]
### Environment
dxx-rebirth/dxx-rebirth, commit 98ad2402bfac4217b62929016bd97b0bff14c52a

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

On a custom campaign, minimal reproducable level copy available here: https://mega.nz/#!kdF00CKI!aA9PqYcKciV1qjMxXxpMDj4jmp6bVpv1Clbq5vH5W8E

DESCENT2.HOG: 7595079 bytes

### Description

Minor bug: The Guide-Bot announces "cannot reach blue key" before being released. This only seems to happen on a specific layout, and most levels are not affected.

#### Regression status

The issue does not occur on DOS,  Descent 2 version v1.2, nor in Rebirth v0.58, but does occur in v0.61 20190530 and v0.61 20190724.

### Steps to Reproduce

1. Start the given level.
2. Try to move around a bit in the starting room.
3. Approach and release the Guide-Bot.

Expected behavior: Guide-Bot states "cannot reach blue key" after step 3.
Actual behavior: Guide-Bot states "cannot reach blue key" after either step 1 or 2.

The issue seems to occur every time this is attempted.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
I am unable to retrieve the level from that URL.  Is an affected level (even if not minimal) hosted elsewhere, such as DMDB?

The guidebot is supposed to keep quiet until freed.  If it had too large a cage, it might become confused and activate early.  I can check that easily with a demonstration level.

**Comment by ziplantil** [comment]
It's not on DMDB, since it is from a work-in-progress level set, but I can try another file upload site. The guidebot cage is a 20x20x20 cube with the guidebot breakable door on face 4 (1-based, face 3 0-based), it being the only connected side.

**Comment by vLKp** [comment]
That sounds reasonable.  I have not intentionally changed the guidebot activation rules, and the logic is a bit convoluted.  It can talk if:

1. it was previously permitted to talk
  https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/d2x-rebirth/main/escort.cpp#L236-L237
2. For every side in its current segment, it is not prohibited by one of two tests:
    https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/d2x-rebirth/main/escort.cpp#L243
    1. If that side is a wall, and it is a blastable wall, and it is still closed, then the guidebot cannot speak.  If any of these statements is false, skip this side and look for some other reason not to speak.
      https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/d2x-rebirth/main/escort.cpp#L246-L249
    2. That side is attached to another segment, and that segment satisfies (i).  Again, if it fails any of these tests, move on and look for some other reason not to speak.
      https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/d2x-rebirth/main/escort.cpp#L257-L264

If the search visits all six sides and has found no reason to silence the guidebot, then it is permitted to speak.  Testing for a blastable wall on sides that are not connected to anything seems wrong, but would not explain your problem.  Similarly, if you had a bogus `wall_num` on some side other than the exit door, that might cause the guidebot to remain silent too long, but that is not the problem you reported.

The only place in the code that enables the buddy to talk is finishing this function, so I think this function must be misbehaving on your level.  So far, I don't see a way that it could misbehave with the description you gave.

**Comment by ziplantil** [comment]
The logic seems reasonable, and based on that alone, there should be no way for the bug to occur, but it seems to occur anyway. I'd be eager to share the level, but I would need to know a way (such as a file sharing site that you are able to access) that would allow you to download it as well.

**Comment by vLKp** [comment]
It is probably small enough that you could pack it in a zip and attach it to this ticket.

**Comment by ziplantil** [comment]
That is a good point, I completely forgot that was a feature.
[lvl02min.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3438663/lvl02min.zip)

**Comment by vLKp** [comment]
Your level reproduces the problem for me.  It looks like the guidebot has always been at least somewhat wrong, but was historically silently wrong.  The game assigns the guidebot a goal on level start, even though a caged guidebot can never do anything useful.  Prior to the bad commit, the guidebot could not report its status, so you didn't notice this.

I think the reason this happens in your level, but not in most levels, is that the guidebot's first objective is the Blue Key, and your Blue Key is behind a forcefield.  This makes the key findable, but not reachable.  In unaffected levels, the first objective is defended by robots, but not blocked by a wall, so the guidebot knows how to reach it.  It can't go there because the blastable door used for its cage confines it, but the goal pathfinding code doesn't consider blastable doors to be a barrier.

**Comment by vLKp** [comment]
The above commit fixes the issue for me.  Please reopen if this is still a problem for you.
