### ISSUE TITLE
Runtime bug: 65535 displaying lives on demo playback

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#444]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

The issue presents itself all the time during demo playback. The display of lives is always set to 65535. 

#### Regression status

I could trace the issue back all the way to 0080a8b7c784685036efecd92c0daa55208ceaa6 and further to 3f164f494d11a4da71a965f515856e5da0cc1f52 where the number displayed is even larger.

The nature of this issue is fairly straight forward: newdemo.cpp sets player lives to 0 which is unobtainable in the regular game (1 is the lowest number - if player dies with this value, the game is over). The HUD elements however represent the lives value as extra lives, and consequently subtract 1 from it:
> const uint16_t lives = get_local_player().lives - 1
(in gauges.cpp)

Since this is now represented by an unsigned value, setting lives to 0 in newdemo causes the value to roll over.

The reason I have not checked in a fix, is because I am not 100% sure how it should be addressed proper:
While the error stems from a change in gauges.cpp, making the value uint16_t specifically instead of just throwing Players[Player_num].lives-1 into gr_printf, I feel like it would be correct to fix this in newdemo.cpp and set plr.lives to 1 instead of 0 in newdemo_start_playback.
Do you agree, @vLKp ?

### Steps to Reproduce

1) Play back any demo 
2) Observe lives counter

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by vLKp** [comment]
If the demo system doesn't track lives properly, I'd say just hide the lives-remaining counter when playing a demo.  It's better to show nothing than to show wrong information, and setting `plr.lives` to `1` during demo startup will make the gauge always show `0` lives instead of whatever the pilot saw when recording the demo.

**Comment by vLKp** [comment]
[Hide lives-remaining count during demo playback](/dxx-rebirth/dxx-rebirth/commit/4504f3602a4df16836736a87ebfb15fc19500f90) should address this.
