### ISSUE TITLE
Runtime bug: Descent 2: CounterStrike final boss death does not trigger escape

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#448]
### Environment

This issue is present in all versions of D2X-Rebirth with commit 215252b8caf33b0b4e9a7e8574ff36e597b4ca4b and onwards.

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

In Descent 2: Counterstrike, after you defeat the final boss (level 24), the game is supposed to do two things: Fade the screen to black and then trigger the escape (i.e. the ending movie) without the player actively needing to seek the exit. This behavior is broken. After the boss dies, the player can fly around in the level as usual. There is also no countdown or mine rocking (which I think may be normal considering the expected behavior).

#### Regression status

This issue was introduced in part in 215252b8caf33b0b4e9a7e8574ff36e597b4ca4b where the game would not trigger the outro movie anymore. 

Please note that the fade to black was broken/missing before that, which - if I remember correctly - is related to the fact that Rebirth never supported palette fading (as used in the menus) properly. I thought I had a fade to white in the past using the same function that blinds the player as when hit via a flash missile, but I am not sure if that was lost or if I never got around to check that in. However I think to stay closer to the original, a similar but stronger effect used when you pick up a cloak could be used here to simulate a fade-out. I could play around with that, but I think the issue of the ending movie not triggering should be addressed first.

### Steps to Reproduce

1) Start Descent 2: Counterstrike in level 24 (you can use FREESPACE Cheat to get there)
2) Make your way to the final boss and defeat it (I attached a savegame that spawns you right in front of the boss door with all equipment you need)
[save_1.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/files/3554685/save_1.tar.gz)
You can see the ending movie will not be triggered and you have to seek the exit on your own.

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by ziplantil** [comment]
The fadeout is part of readding the fade transitions in general, for which I have an unfinished branch [/ziplantil/dxx-rebirth/tree/fadetransition](fadetransition), which is plagued by various issues. It's probably enough for now to just have the exit sequence itself by directly triggered by killing the boss.

**Comment by vLKp** [comment]
`Final_boss_countdown_time` was not written back, so unless `FrameTime` jumped from full to done in a single step, the countdown never made progress.  This is fixed in [Write back Final_boss_countdown_time on every update](/dxx-rebirth/dxx-rebirth/commit/275c4297fedcdf7eddb1b32218155e96db366fbe).

Fixing the fade sounds nice, but I'd like to track that in a separate ticket, since it is cosmetic and this report is about a serious gameplay bug.
