### ISSUE TITLE
Runtime bug: Savegames created with newer commits cause issues if loaded in older commits.

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#449]
### Environment

The issue is mostly present in commits older than bfeca84bb86ab75365f18d60c17e18f36dbfaf1d, but since it is actively caused by this commit and present in all subsequent versions newer than that, I find it worthy of note.

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

I was able to reproduce the issue with the Descent 1: First Strike final boss with the savegame provided here https://github.com/dxx-rebirth/dxx-rebirth/issues/443#issuecomment-523998362 as well as the Descent 2: Coutnerstrike final boss in my savegame attached 
[save_1.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/files/3554722/save_1.tar.gz)

### Description

This issue was first reported by @Neurochild247 in https://github.com/dxx-rebirth/dxx-rebirth/issues/443 and it states that in savegames created with newer versions of Rebirth, you cannot harm bosses in older versions. I was able to reproduce this effect and isolate it to commit bfeca84bb86ab75365f18d60c17e18f36dbfaf1d. Each savegame created in this commit onwards will work in newer versions just fine. But going back in the commit history will make you unable to hurt bosses as shots pass right through them.

### Steps to Reproduce

1) Check out bfeca84bb86ab75365f18d60c17e18f36dbfaf1d
2) Start Descent 1 First Strike or Descent 2 Counterstrike and make your way to the final bosses. 
3) Save the game. 
(Alternatively you can just use one of the provided savegames).
4) Check out a commit older than bfeca84bb86ab75365f18d60c17e18f36dbfaf1d and compile the game.
5) Load your savegame and try to damage the boss (Note: The Descent 2 final boss will still REFLECT if you do not hit its weak spot, but hitting its weak spot itself is impossible - shots will pass through it).

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by vLKp** [comment]
This is probably because older versions try to treat signature as globally unique, but the newer ones treat it only as locally unique.

**Comment by vLKp** [comment]
Other than reverting the signature commit, I don't see a good way to fix this.  In my opinion, the globally unique signature design was not a good one, which is why I switched to locally unique signatures.  My first choice for dealing with this would be to prohibit old builds from loading affected saves, but as discussed in #451, the loader doesn't have a good way to do that because no one ever coded it to reject versions newer than what it understands.  Allowing old builds to load new saves has always been a best-effort basis (and has previously required several workarounds for places where the loader wrongly used `int32` for object numbers).  My preference is to release-note that old builds should not be used with boss-level saves, then close this without a code change.  However, if you can find a code change to fix this that does not require reverting to globally unique signatures, I'm open to considering it.

**Comment by vLKp** [comment]
The release note was added several months ago.  There has been no further activity, and no proposed fixes other than reverting the change I wish to keep.  I see no reason to keep this issue open.  If you disagree, please reopen.
