### ISSUE TITLE
Game crashes with exit .txb if no end of exit tunnel face found

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#450]
### Environment
6629711b59e92ed7c35096a70ce63f0c845d7175

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
An example of a mission matching the description below: [exitless.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3555388/exitless.zip)

### Description
The game crashes if a .txb is present for an exit sequence, but there is no "end of exit tunnel" face present in the level.

#### Regression status
Does not happen on DOS (which does not support D2X exit sequences to begin with), nor in Rebirth v0.58.

### Steps to Reproduce
1. Try to open the attached level.

Instead of the level opening as would be expected, the game crashes with the following message:

```
---------------------------
Rebirth - Fatal Error
---------------------------
Rebirth encountered a fatal error.  Please report this to the developers.

Include in your report:
* The exception message text:
  "similar/main/endlevel.cpp:1523: invalid index used in array subscript: base=007cda60 size=9000 index=65535"
* The level(s) played this session, including download URLs for any add-on missions
* The contents of the text file:
  [temp directory here]\2019-08-29-11-53-55 x86 P10432 D2X-Rebirth v0.61.elog

Dump file generation is not enabled in this build.

To the extent possible, provide steps to reproduce, starting from the game main menu.
---------------------------
OK   
---------------------------
```

The log:
[2019-08-29-11-53-55 x86 P10432 D2X-Rebirth v0.61.elog.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3555403/2019-08-29-11-53-55.x86.P10432.D2X-Rebirth.v0.61.elog.txt)

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
I'll try to fix this over the weekend.  The crash is an uncaught exception when the code tries to treat `segment_none` (`0xffff`) as a valid segment index.

**Comment by vLKp** [comment]
The above commit lets your test level load for me.  Please report if you encounter any other problems with exit data.
