### ISSUE TITLE
Runtime issue: Rotating markers conflicts with marker camera view

### ISSUE THREAD

**Issue by flpduarte** [dxx-rebirth/dxx-rebirth#456]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20190917-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent 2 v. 1.2
Any campaign.
Size of descent2.hog: 7,107,354 bytes

### Description
Since dxx-rebirth v. 0.60 update, markers placed in the game now appear rotating randomly. Sometimes a marker does keep still, but in general markers rotate about a random axis: X, Y, Z or a combination of them. 

While this effect does not affect single player experience, it does affect multiplayer when we activate the option Marker Camera Views. Me and a friend usually play Anarchy with marker views activated, however since markers rotate, views from the marker also rotate, making it impossible to use the markers as a spy.

I looked for an option in the game to disable the marker rotating effect, but haven't found any. So I'm not sure if this effect is intentional or not. Since a similar issue has not been posted yet, I decided to submit this description.

#### Regression status

This issue was not present in Rebirth version 0.58.1. I have observed this issue exists since commit d6b2ab5, but I have not checked earlier commits to find out when exactly it appeared.

### Steps to Reproduce
Simply place markers anywhere in any level by pressing F4, then Enter. Marker description is not necessary.

Expected behaviour: Marker placed; marker does not move.
Observed behaviour: Placed marker rotate about a random axis.
Frequency of the problem: always present.

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [X] Multiplayer competitive
    * [X] Anarchy
    * [X] Team Anarchy
    * [X] Robo-Anarchy
    * [X] Capture the Flag
    * [X] Bounty
  * [X] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [X] Game guests

**Comment by vLKp** [comment]
This was introduced in [Fix retail bug that prevented marker spinning](/dxx-rebirth/dxx-rebirth/commit/0df57f5b0f86c80979000389d68b23403afd52eb), and aggravated in [Vary marker spin](/dxx-rebirth/dxx-rebirth/commit/fe77949a824e23e7237fd5994a06f6ab072ee271), which also added the release note documenting that markers now spin.  In my opinion, it is a bug in _retail_ that markers did not spin, since they were given a spin rate, but their movement type was set to `MT_NONE`, which ignores spin rate.

https://github.com/dxx-rebirth/dxx-rebirth/blob/12b57e84e6f2c90e011d45848c4e485762f994f5/similar/main/object.cpp#L2165-L2169

That said, your complaint about the inability to use them as a fixed camera is valid and should be addressed.  The simple fix would be to disable spinning in games where marker cameras are enabled.  Does the below patch address your problem?

```diff
diff --git a/similar/main/object.cpp b/similar/main/object.cpp
index 2ed3caca3..8a626bb7e 100644
--- a/similar/main/object.cpp
+++ b/similar/main/object.cpp
@@ -2322,11 +2322,17 @@ imobjptridx_t drop_marker_object(const vms_vector &pos, const vmsegptridx_t segn
 {
 	Assert(Marker_model_num != -1);
 	auto &Polygon_models = LevelSharedPolygonModelState.Polygon_models;
-	const auto &&obj = obj_create(OBJ_MARKER, marker_num, segnum, pos, &orient, Polygon_models[Marker_model_num].rad, CT_NONE, MT_SPINNING, RT_POLYOBJ);
+	const movement_type_t movement_type =
+		((Game_mode & GM_MULTI) && !(Game_mode & GM_MULTI_COOP) && Netgame.Allow_marker_view)
+		? MT_NONE
+		: MT_SPINNING;
+	const auto &&obj = obj_create(OBJ_MARKER, marker_num, segnum, pos, &orient, Polygon_models[Marker_model_num].rad, CT_NONE, movement_type, RT_POLYOBJ);
 	if (obj != object_none) {
 		auto &o = *obj;
 		o.rtype.pobj_info.model_num = Marker_model_num;
 
+		if (movement_type == MT_SPINNING)
+		{
 		constexpr fix scale = F1_0 / 2;
 		const auto oi = obj.get_unchecked_index();
 		auto &spin_vec = o.mtype.spin_rate;
@@ -2337,6 +2343,7 @@ imobjptridx_t drop_marker_object(const vms_vector &pos, const vmsegptridx_t segn
 			vm_vec_scale_add2(spin_vec, o.orient.uvec, (oi & 16) ? scale : -scale);
 		if (oi & 4)
 			vm_vec_scale_add2(spin_vec, o.orient.rvec, (oi & 32) ? scale : -scale);
+		}
 
 		//	MK, 10/16/95: Using lifeleft to make it flash, thus able to trim lightlevel from all objects.
 		o.lifeleft = IMMORTAL_TIME - 1;
```

**Comment by flpduarte** [comment]
Hello. It looks like the patch you showed does solve the problem. The rotating markes indeed only affect multiplayer games where markers are allowed to be used as cameras; in all other game modes, the marker animation does not affect gameplay.

I didn't know the markers had the ability to be allowed to spin, but in the end the retail version just kept them still. Maybe at the time the game designers thought spinning markers would be a good idea, but in the end they changed their mind... who knows.

Anyway, thank you for the clarification. I intend to contribute with dxx-rebirth in the future, but I am still trying to understand the source code first and to compile it at my PC first.

**Comment by vLKp** [comment]
The above commit adds the proposed patch to `master`.  Closing.  Please reopen if you feel further changes are required.

> I am still trying to understand the source code and to compile it at my PC first.

If the instructions in the documentation are not sufficient, please file an issue to have the instructions improved.
