### ISSUE TITLE
Runtime bug: Smelter II (Vertigo bot) never fires

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#458]
### Environment

9d22103d45cf5236537c96cff187e7dd6c7b033e

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
Descent 2: Vertigo, or any level using Vertigo assets.

### Description
Smelter II (Vertigo-exclusive bot) never fires at the player; presumably this also affects other bots using the "Vertigo Fireball" weapon.

#### Regression status
Does not happen on an earlier version of v0.61, does not happen on v0.58, does not happen in the original game.

### Steps to Reproduce
1. Open D2X-Rebirth
2. Play Descent 2: Vertigo, level 13
3. Go left of the starting room and up at the first point where possible, passing through a grate door
4. Head towards the curved tunnel, in which an E-Bandit and a Smelter II awaits.
5. Approach Smelter II.
6. Observe.

Expected result: When a Smelter II (Vertigo-specific bot) is in front of you, it fires at you with Phoenix-like shots.
The result I get: The Smelter II stares at me, makes sounds, but never fires.

The problem seems to occur every time when tested in singleplayer.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

Potentially also Robo-Anarchy and co-op, but has not been tested there.

**Comment by vLKp** [comment]
Confirmed.  This should be fixed by the above commit.  Only weapon types on a whitelist can be fired, and this one was not on the list.  The game should have printed a warning to the gamelog when it suppressed the shot:

```
similar/main/laser.cpp:732: BUG: unexpected weapon id 64 fired by parent 15 (type 2) in segment 334
```

Please reopen if the problem persists.
