### ISSUE TITLE
d1x crashes with shareware data

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#46]
D1x from current unification head does not work with the shareware game data from the dxx-rebirth website (http://www.dxx-rebirth.com/download/dxx/content/descent-pc-shareware.zip). The game crashes after the intro screens, before the main menu appears:

> D1X-Rebirth v0.58.1 0.58.1-d2x-4758-g24580789  Mar 19 2015 21:27:30
[...]load_polygon_model:667: error: Model <laser1-1.pof> references 1 textures but specifies 0.
zsh: abort      ./d1x-rebirth/d1x-rebirth -hogdir ./shareware

**Comment by vLKp** [comment]
Confirmed.  First bad commit is 68be3baeca7af9f24609f05b464c44228e9ac5b6.

**Comment by vLKp** [comment]
Fixed in 3a37b41192ae20e618741457c3c01138a84ac33a.
