### ISSUE TITLE
Runtime bug: Matcens refuse to spawn robots if we have killed too many dropped robots

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#466]
### Environment
93d3793b306cebb50be1dc86f974204d5d877ac0

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
Any mission, but I have included a minimal example which consistently reproduces this issue. Assets do not matter, since this is a game logic issue.

The level: [matcenus.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3816129/matcenus.zip)

### Description
Matcens refuse to spawn robots when we have killed dropped robots (i.e. robots that have been "dropped" by killing a robot), as it believes it has no free slots.

The failing check is https://github.com/dxx-rebirth/dxx-rebirth/blob/b19149c7b3005e639c38abc608bca8c3176a0dac/similar/main/fuelcen.cpp#L402

Let's for instance assume the example level I have attached; it has 1 robot, but it drops 7 robots when killed. Thus `accumulated_robots` is set to 1 on level start, since there is only one robot in the level. However, that value is not incremented when robots are dropped (the original game does not increment it either in that case), so it will stay as 1, while `num_kills_level` will reach up to 8 (1+7). 

Now, when we subtract these two unsigned values from each other (`1 - 8`), the result will be a very large number (in this case, probably `2^32 - 7` or `4294967289`), which will obviously always be greater than `Gamesave_num_org_robots + Num_extry_robots`, and hence nothing will spawn. In the original game and earlier versions, `accumulated_robots` (then called `num_robots_level`) was a signed value, so the first value would be negative instead, passing the check and thus letting robots spawn.

#### Regression status
The bug is present ever since a24de0c003ce43a623c3b2960ac38d1e915fdfbc, which converted `short num_robots_level` to `unsigned accumulated_robots`.

### Steps to Reproduce
1. Open level (here assuming you open the attached case study level)
2. Kill the medium hulk; it will drop 7 class 1 drones.
3. Kill the class 1 drones.
4. Hit the control panel on the matcen wall

Expected result: class 2 drones spawn (they do, if you do not kill the medium hulk or at the very least the class 1 drones it drops)
Actual result: the matcen lights up, but nothing ever spawns

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
Nice find.  I think the right solution here would be fixing the counter so that no underflow occurs.

**Comment by vLKp** [comment]
I confirm the reported problem is visible with the demonstration level, and greatly appreciate such a simple demonstration level and the associated explanation.  With the commit above, the demonstration level now works correctly.
