### ISSUE TITLE
Runtime crash: Crash if Vertigo bots present after exit sequence plays

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#467]
### Environment

93d3793b306cebb50be1dc86f974204d5d877ac0

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
Any custom level set with more than one level, using D2 exit sequences (not the movies, but with exit.ham etc.; such custom missions are currently few and far between, if they exist at all) and Vertigo or other V-HAM robots. I have included a minimal example here: [exitd2v2.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3821925/exitd2v2.zip)

### Description
This issue is tightly linked to #460, and is caused by the same reasons, but happens more often. If a level with Vertigo bots or other V-HAM robots follows a level with a D2 real-time exit sequence, the game will crash the moment it would try to render one of those robots, since the models are unloaded.

This issue can be fixed by reloading V-HAM robots and their assets on level load.

#### Regression status
Same as #460: 
> The problem is likely present in all Rebirth and D2X versions ever since the D2X version that reintroduces D2 exit sequence support. 

### Steps to Reproduce
1. Open level
2. Open exit door
3. Fly through exit
4. Watch exit sequence
5. Proceed to level 2

Expected result: Vertigo bot renders, game plays fine.
Actual result: Game crashes.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by ziplantil** [comment]
I will try to implement some kind of fix for this some time next week, probably by just reloading all V-HAM models at level load, perhaps only if the exit sequence was played before

**Comment by vLKp** [comment]
According to the opening comment in pull #479, this should be fixed now.  Please reopen if you still see problems.
