### ISSUE TITLE
Runtime bug: Mission list incorrectly sorted

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#472]
### Environment

2019-10-18 Nightly Build (https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20191018-win.zip)

#### Operating System Environment

Microsoft Windows 10

#### CPU environment

x86\_64 (64-bit Intel/AMD)

#### Game environment

Only tested with Descent 1

### Description

The mission list appears to be incorrectly sorted; I'm not entirely sure, but my hypothesis is that the missions are being sorted case-sensitively by the filename of the .msn file rather than by anything that would make more sense.

#### Regression status

Problem was not present in v0.59.1; unsure about any newer versions.

### Steps to Reproduce

Unsure, but if the above hypothesis is correct, having two missions where the one that should be sorted first starts with a lowercase letter should reproduce the issue.

**Comment by vLKp** [comment]
Missions should be sorted case-insensitively by mission name.  Do you have an example of missions that sort contrary to what you believe to be correct?

**Comment by AlumiuN** [comment]
OK, it currently appears that my mission list is being sorted by mission filename (with case sensitivity) instead.

![2019-11-15 04-11-10](https://user-images.githubusercontent.com/10217377/68916477-f4cbb300-07ca-11ea-94d6-53148cd5528b.png)

The names of the .MSN files are in order for those with the exception of BBBROX, which appears at the bottom of the Bs, I suspect because its filename is "Bbbrox.msn" rather than being allcaps.

**Comment by vLKp** [comment]
`BYEBYE` is in `BYEBYE.MSN`, and `BBBROX` is in `Bbbrox.msn`, correct?

**Comment by AlumiuN** [comment]
> `BYEBYE` is in `BYEBYE.MSN`, and `BBBROX` is in `Bbbrox.msn`, correct?

Correct.

**Comment by vLKp** [comment]
I created in my `~/.d2x-rebirth/missions` directory two MSN files:
```
BYEBYE.msn
Bbbrox.msn
```
I gave them the suggested names:
```
$ grep name BYEBYE.msn Bbbrox.msn
BYEBYE.msn:name = BYEBYE
Bbbrox.msn:name = BBBROX
```
I started `d2x-rebirth` built from [current master](/dxx-rebirth/dxx-rebirth/commit/93d3793b306cebb50be1dc86f974204d5d877ac0) and chose `New game`.  The entries were presented in the correct order.

I cannot reproduce this with the information given.  Please provide the offending missions or steps to reproduce the problem from a clean install.

**Comment by AlumiuN** [comment]
OK, just did a quick test with a clean install, and it sorts the missions correctly (i.e. by mission name) if they're in the root missions directory, but sorts them incorrectly if they're in a subdirectory.

**Comment by vLKp** [comment]
Confirmed when the missions are in a subdirectory.  The above commit fixes the problem for me.  Thank you for the report.  Please reopen if you still see problems with that commit included.

Note that, although not discussed in this report, it occurred to me while working on this that I ought to follow the model used by most file/directory browsing tools and sort all directories to the top of the list (though I still place directories below the built-in missions), so directory `Z` comes before mission `A`.  That is implemented in a separate commit.

**Comment by AlumiuN** [comment]
Awesome, thanks (and good thinking on the directory sorting). I can't figure out how to compile Rebirth myself, but I can wait for the next release :)

**Comment by vLKp** [comment]
> I can't figure out how to compile Rebirth myself, but I can wait for the next release :)

If you want to compile it for yourself, please see [INSTALL.markdown](/dxx-rebirth/dxx-rebirth/blob/master/INSTALL.markdown).  I've received reports before that this is insufficiently detailed, but the reports were themselves insufficiently detailed for me to improve the instructions. :)  If these instructions aren't good enough, please file an issue describing what is unclear or what went wrong, and I will try to help you through it and improve the documentation for the next person.
