### ISSUE TITLE
Runtime bug: Missions with filenames longer than 8 characters (without the extension) fail to load as saved games, or in network games on clients

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#491]
### Environment

Latest commit (47a3df9)

#### Operating System Environment

Windows 10

#### Game environment

Currently tested under Descent 2 with a specific HOG (see attached files)

### Description

Missions with filenames of longer than 8 characters will fail to load on network clients or from a saved game if the mission is not loaded freshly beforehand, as they will receive an empty string for the mission name. I'm almost entirely certain this is the result of Netgame.mission_name and the relevant string in saved games only being 8 characters long.

Here's a HOG that causes it - [thieftes2.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/4044535/thieftes2.zip)

#### Regression status

Unsure

### Steps to Reproduce

Have one player host a game using any suitable long-named HOG, then have another player attempt to join it.

**Comment by AlumiuN** [comment]
Having done some testing, the issue appears to be symptomatic on the server side at [this line in similar/main/net_udp.cpp](https://github.com/dxx-rebirth/dxx-rebirth/blob/47a3df9fab7b006b4004b6ce9b379060e77dd63b/similar/main/net_udp.cpp#L3948); normally it works fine but for some reason when presented with the HOG above it doesn't copy anything, leaving Netgame.mission_name empty (the method I used to verify this was the good old "slap a couple of printfs in the right place").

**Comment by vLKp** [comment]
The above commit fixes loading deeply nested missions for me for demos and for single player.  It should address multiplayer too.  Please reopen if you still see problems.

**Comment by AlumiuN** [comment]
I get an error when attempting to compile:

```similar\main\menu.cpp: In function 'dcx::window_event_result select_file_handler(listbox*, const dcx::d_event&, {anonymous}::browser*)':
similar\main\menu.cpp:1784:14: error: cannot convert 'std::array<char, 260>' to 'char*'
     snprintf(newpath, sizeof(char)*PATH_MAX, "%s:%s", text, sep);```

**Comment by vLKp** [comment]
Yes.  That is in a Windows-only path, so the code built for me without updating that.  [Fix Windows build break](/dxx-rebirth/dxx-rebirth/commit/4b48e0cd14b0918c547c5952b3c486b16355ee4b) adds the `.data()` and converts the size parameter.
