### ISSUE TITLE
Mouse clicks ignored New Game -> Mission Select

### ISSUE THREAD

**Issue by Q3BFG10K** [dxx-rebirth/dxx-rebirth#498]
I use D2X to play 1, 2 and Vertigo. 

When try to use mouse clicks to change between them, it frequently ignores the click and does nothing. Other times it jumps to the wrong option and frequently ignores the middle one (2).

The other menus work fine with the mouse.

0.58.1 didn't have this issue.

Win10-64 1909.  a645fd2,

**Comment by vLKp** [comment]
That is a very wide commit range (8916 commits).  Can you narrow it down any?

**Comment by Q3BFG10K** [comment]
I'm just using the latest download link from the main site:
 
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200301-win.zip

**Comment by vLKp** [comment]
I understand that, but you are reporting that, sometime in a six and a half year period, this broke.  I never noticed the break because I use keyboard navigation for menus.  Finding the first known bad commit often makes fixing regressions much easier, which is why the issue filing template requests that information.  A six year range is infeasible to search when the problem is a subjective user interface error, so without a first-bad commit, this will need to be approached some other way.

**Comment by Q3BFG10K** [comment]
I've never used anything later than 0.58.1.

Which template are you referring to? When I submitted my issue I got a blank text box, just like every other github project I've reported bugs for,

**Comment by vLKp** [comment]
> Which template are you referring to?

Click the button labelled "New Issue."  You are taken to [New Issue](https://github.com/dxx-rebirth/dxx-rebirth/issues/new/choose), where you are presented with three list items:
- Failure to build
- Runtime crash
- Runtime bug

There is a link near the bottom for opening a blank issue.  If you chose "Get Started" on **Runtime bug**, you would be taken to [Issue: Runtime bug](https://github.com/dxx-rebirth/dxx-rebirth/issues/new?assignees=vLKp&labels=bug&template=03-runtime-bug.md&title=Runtime+bug%3A+), which would prompt you for quite a bit of information.

**Comment by vLKp** [comment]
The above commit resolves the issue for me.  The click location was correct, but the corresponding index was miscalculated.  The lines were measured as if they were drawn in a much smaller font than was used on screen, so clicking on line 3 would select line 7.  Depending on where you clicked, your effective location might be outside the box entirely, where it would be rejected.

Please reopen if you still see problems in a build with this fix.
