### ISSUE TITLE
Unification: Multiplayer Item Inconsistencies

### ISSUE THREAD

**Issue by Matt1360** [dxx-rebirth/dxx-rebirth#50]
The favourite bug of Mr. @zicodxx I'm sure :)

It seems related to #49, in the following way:

Two players are in, A and B (A is the host, although appears irrelevant).  Both players are full of loot.
A kills B.
B doesn't respawn right away.
A collects some of B's goodies, and a few other goodies that were already in the map.

Now B is watching this in their view, from the death-cam.  B notices that A made the "sluuurp" sound of picking up the goodies... But the goodies never disappeared.

B now respawns, and we've duped **some** items.  That's what's a bit terrifying.  Sometimes shields will stay, sometimes missiles, it seems to be unpredictable.

[Screenshot 1](https://reenigne.ca/screenshots/1426918307.png) - from A's perspective (blue).
[Screenshot 2](https://reenigne.ca/screenshots/1426918345.png) - from B's perspective (red).
[Screenshot 3](https://reenigne.ca/screenshots/1426918409.png) - from A again.

Notice that A only has 2 smarts, and is sitting in one from B's perspective.  Also, the missing spreadfire (which could be covered by the dialog, but I assure you it's not).

I'm not sure where to look here, I know @zicodxx spent a lot of time on this, and probably knows this code much better than I could figure it out over a weekend.

**Comment by zicodxx** [comment]
As far as I can tell, this issue might be related to map_objnum_local_to_remote. The object mapping does not work with playernum_t consistently and I suppose this is where the problem might come from.  @kp can you take a quick look into that? I fear trying to turn ALL related variables into playernum_t as that may lead me way all over the source.

**Comment by vLKp** [comment]
I will look into it.  I suspect that kp does not have an appropriate development environment for this. :wink:

**Comment by Matt1360** [comment]
I still intend to do work on these few issues, but I am swamped with unrelated work, sorry.

**Comment by zicodxx** [comment]
@vLKp Damnit - now I start adding syntax errors in comments. Thanks for looking into it. :)

**Comment by Mako88** [comment]
I believe this can be marked as fixed now, right? :)

**Comment by zicodxx** [comment]
Absolutely correct. :)
Bug is fixed in 74b66a7f5a6411a829beb962f18b9230f0e86af4.
