### ISSUE TITLE
Reshade support

### ISSUE THREAD

**Issue by bencun** [dxx-rebirth/dxx-rebirth#500]
So, I've been looking around injecting Reshade into Dxx since I thought it would make a nice addition to the game: MXAO for ambient occlusion, bloom shaders for lasers, lights, explosions, etc, SMAA, vibrance, maybe even those fancy real-time raytracing shaders from Marty McFly.

Reshade 3.4.1 works semi-properly, depth buffer is detected but normals aren't displayed properly.
Same goes for 4.x up to 4.5.4 - this version detects the depth buffer including the normals 100% accurately so for example MXAO works like a charm - but everything else doesn't work properly: Finesharp shader shows some green square artifacts and most of other shaders seem to have no effect to the image being rendered when activated - some even cause the screen to go completely white or black when activated.

Just wanted to get this somewhere out in the open - I'm not capable of fixing this kind of stuff myself since I'm not a game dev/OpenGL dev but I'm opening this issue in hope that maybe some part of the rendering process could be modified easily to allow for Reshade to be injected properly. I'm also very much aware that this is potentially a Reshade-specific issue but these versions mostly work properly with other OpenGL games out there: stuff like Jedi Knight 2 etc. so I thought some part of the rendering process might be preventing proper injection and maybe one day someone can take a look at it.

Also, gotta use the opportunity to thank everyone for developing and maintaining this port. Awesome work.

**Comment by derhass** [comment]
> Reshade 3.4.1 works semi-properly, depth buffer is detected but normals aren't displayed properly.
> Same goes for 4.x up to 4.5.4 - this version detects the depth buffer including the normals 100% accurately so for example MXAO works like a charm - but everything else doesn't work properly

That is absurd. dxx-rebirth doesn't render any normals, it is not even using the GL lighting at all - all lighting is calculated per-vertex on the CPU, no normal data is ever passed on to the GPU, and the GL is only used for rasterizing textured triangles - exactly as the first customer-grade 3D accelerators worked in the mid-90s. Depth and color buffer is everything which you can get here.

**Comment by bencun** [comment]
Well that's definitely absurd - I most definitely get access to the complete depth buffer with Reshade 4.5.4. With Reshade 3.x even Finesharp works as well as SMAA and Vibrance (MagicBloom does not on the other hand) but depth buffer normals seem corrupted.

Could it be that injected Reshade DLL is somehow forcing the game to be rendered on the GPU since it's obviously wrapping the calls to the OpenGL functions?

**Comment by derhass** [comment]
Well, one can approximate geometry normals from the depth buffer alone, but it is very limited and leads to artifacts at the edges of objects.

**Comment by derhass** [comment]
> Could it be that injected Reshade DLL is somehow forcing the game to be rendered on the GPU since it's obviously wrapping the calls to the OpenGL functions?

No. Thats not how things work. The game _is_ rendered on the GPU, just one triangle a time. However, that shouldn't be a big deal, I guess modern versions of reshade are just not properly dealing with pre-historic GL 1.1 dxx-rebirth uses.

**Comment by bencun** [comment]
> Well, one can approximate geometry normals from the depth buffer alone, but it is very limited and leads to artifacts at the edges of objects.

Ahhh this explains everything as that's exactly what happens. Here's the 50/50 screenshot of normals and depth buffer from Reshade 3.4.1 where I've got complete access to it (many shaders aside from SMAA also render properly):

![d1x-rebirth 2020-04-04 00-34-19](https://user-images.githubusercontent.com/15714548/78410328-41921800-760c-11ea-89c4-b7743a7bf56a.png)

However, Reshade 4.5.4 doesn't render any shaders besides from MXAO, even the DisplayDepth shader isn't displaying anything although MXAO obviously works and Reshade has access to the depth buffer.

**Comment by bencun** [comment]
Furthermore, Reshade 4.2.1 works great with Jedi Knight 2 - which I believe also uses OpenGL 1.1

**Comment by derhass** [comment]
> However, Reshade 4.5.4 doesn't render any shaders besides from MXAO, even the DisplayDepth shader isn't displaying anything although MXAO obviously works and Reshade has access to the depth buffer.

Seriously, thats a Reshade bug then. There is nothing dxx-rebirth should do differently in this case. The final framebuffer is availabe to it, if it screws up the shader injection, we can't fix that.

**Comment by bencun** [comment]
Great, thank you very much for your input on this, I did suspect that it's probably Reshade-related but it was worth checking it out with you as I would've enjoyed tweaking shaders for Desecent.
I also had an opportunity to learn some more about graphics :) Cheers!

**Comment by derhass** [comment]
Well, I'm not any official dxx-rebirth dev. I made a few contributions (some regarding OpenGL), though.

**Comment by vLKp** [comment]
In principle, I am interested in upgrading Rebirth to use a more modern OpenGL.  In practice, I haven't had the time.  I'm a general purpose programmer, and my understanding of the current setup is that there's no simple path forward.  Switching to a modern OpenGL would be done as one big change, not as a series of small changes I could publish as they were finished.

**Comment by derhass** [comment]
> Switching to a modern OpenGL would be done as one big change, not as a series of small changes I could publish as they were finished.

Well, that depends on how small you want the changes to be. For example, one could start by switching to VBOs before (and independent of) switching to shaders. But yeah, it will still tend to be a series of few bigger changes. One main issue is that the current approach of rendering so many small chunks separately doesn't really make sense any more and does not map well to modern GL at all. One would to have the to redesign the whole way the mine an bot rendering works.

**Comment by vLKp** [comment]
That's what I expected from my reading on it.  This would be my first time writing code that uses OpenGL (of any generation).  At least that means I don't have any bad habits to unlearn first.  I've worked on the edges of Rebirth's OpenGL code for a long time, but I've never tried to change how it works.

I'm not set on any particular limits for how big/small a change is.  My main goal is that any given commit in the conversion sequence should produce a game that is playable without major bugs, meaning that any commits that do break things need to go on a branch and be squashed down at the end.  As a separate but related problem, I think I need to commit to using SDL2 before I can do any serious work on an OpenGL update.  We're now down to one [SDL2-specific Rebirth ticket](.?q=is%3Aissue+is%3Aopen+label%3Asdl2) (issue #474), which helps.
