### ISSUE TITLE
Runtime bug: Title screen logos fail to load

### ISSUE THREAD

**Issue by Jayman2000** [dxx-rebirth/dxx-rebirth#510]
### Environment

Commit 511a3d6b9c3e69c810c71b1f0d9ccc09cca69f79
#### Operating System Environment

Kubuntu 20.04
#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

#### Game environment

descent.hog: 6856701 bytes
descent2.hog: 7595079 bytes
### Description

When starting Descent 1, the Interplay logo, the Parallax logo, and the Descent logo are shown before the pilot select screen. When starting Descent 2, the Descent 2 logo is shown before the pilot select screen. In DXX-Rebirth these logos are no longer shown.
#### Regression status

I cannot reproduce this bug in DXX-Rebirth v0.58.1.
### Steps to Reproduce

1. Start D1X-Rebirth or D2X-Rebirth.
2. If you're running D2X-Rebirth, skip the intro movie or wait for it to finish.

#### Expected behavior
In D1X-Rebirth, the Interplay logo is displayed. After a few seconds, the Parallax Software logo is displayed. After a few more seconds, the Descent logo is displayed. After a few more seconds, the select pilot screen is displayed.

In D2X-Rebirth, the Descent 2 logo is displayed. After a few seconds, the select pilot screen is displayed.

#### Observed behavior:
The select pilot screen is displayed immediately.

D1X-Rebirth log:
```
Type 'd1x-rebirth-git -help' for a list of command-line options.

D1X-Rebirth v0.61 0.60.0-beta2-764-g511a3d6b9c3e  May 27 2020 17:25:49
This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
Copyright (C) 1994, 1995 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
Using SDL_mixer library v1.2.12
sdl-joystick: 0 joysticks
similar/2d/pcx.cpp:235: failed to open "plogo1.pcx"
similar/main/titles.cpp:188: error: loading briefing screen <plogo1.pcx> failed: PCX load error: Error opening file. (1)
similar/2d/pcx.cpp:235: failed to open "ogo.pcx"
similar/main/titles.cpp:188: error: loading briefing screen <ogo.pcx> failed: PCX load error: Error opening file. (1)
similar/2d/pcx.cpp:235: failed to open "escent.pcx"
similar/main/titles.cpp:188: error: loading briefing screen <escent.pcx> failed: PCX load error: Error opening file. (1)
similar/2d/pcx.cpp:235: failed to open "arning.pcx"
similar/main/titles.cpp:188: error: loading briefing screen <arning.pcx> failed: PCX load error: Error opening file. (1)
```

D2X-Rebirth:
```
Type 'd2x-rebirth-git -help' for a list of command-line options.

D2X-Rebirth v0.61 0.60.0-beta2-764-g511a3d6b9c3e  Vertigo Enhanced  May 27 2020 17:26:03
This is a MODIFIED version of Descent 2, based on Full Version v1.2.
Copyright (C) 1994-1996 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 1999 Peter Hawkins, 2002 Bradley Bell, 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
Using SDL_mixer library v1.2.12
sdl-joystick: 0 joysticks
similar/2d/pcx.cpp:235: failed to open "escentb.pcx"
similar/main/titles.cpp:188: error: loading briefing screen <escentb.pcx> failed: PCX load error: Error opening file. (1)
```
This happens every time.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

**Comment by AlumiuN** [comment]
I can confirm this also happens under Windows 10.

**Comment by vLKp** [comment]
Confirmed.  This does not happen in developer builds, which is why I did not notice it.  It affects non-developer builds on all platforms.  The above commit fixes it for me.  Please reopen if you still see problems.
