### ISSUE TITLE
Allow background input

### ISSUE THREAD

**Issue by floraline** [dxx-rebirth/dxx-rebirth#511]
Currently the game does not accept input from gamepads while in the background. This prevents me from playing the game. Setting [SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS](https://wiki.libsdl.org/SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS) would fix this.

**Comment by vLKp** [comment]
Why is your game in the background while you are playing it?  Wouldn't that make it impossible to see where you are going?

**Comment by floraline** [comment]
Sorry, I meant not the active focused window. I use accessibility software that takes focus.

**Comment by vLKp** [comment]
Changing Rebirth seems like the wrong solution to this problem.  If your accessibility software is changing the focused window, won't most games misbehave?  It seems like the right fix would be to configure the accessibility software not to take focus away from the active application.

**Comment by vLKp** [comment]
As I read the SDL documentation, all hints are already settable via environment variables.  Is that not sufficient in this case?

<https://wiki.libsdl.org/CategoryHints>:
```
The convention for naming hints is SDL_HINT_X, where "SDL_X" is the environment variable that can be used to override the default. 
```

**Comment by vLKp** [comment]
No response from original requester.  I proposed above an alternate solution that should work with no code changes, and no downsides.  Closing.

OP: if you believe that my proposed solution is not functional, please reopen for further discussion.
