### ISSUE TITLE
Runtime crash: Complicated and unlikely scenario involving D1 one-shot triggers leads to a level crashing

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#515]
Tested on 096a678, Win10, 32-bit EXE.

When a D1 level is exited via a standard exit, check_trigger will still run through the routine for processing the one-shot-ness of the trigger in question, meaning that if the level being entered has a one-shot trigger with the same number as the exit trigger from the previous level, the seg and side arguments passed into check_trigger are no longer relevant but will still be used.
The one level that I've found where this happens is [Descend Again](https://www.enspiar.com/dmdb/viewMission.php?id=200) level 6->7, and it causes a crash as a result.

**Comment by vLKp** [comment]
That is definitely an obscure situation.  Did you find this via code inspection and seek out a level where it happens, or get the crash in the level and debug from there?

Either way, this warrants fixing.

**Comment by AlumiuN** [comment]
I got the crash while playing the level and debugged from there.

**Comment by AlumiuN** [comment]
After a quick look at the original D1 source, I think slapping everything in that block after `t.flags &= ~TRIGGER_ON;` inside an `if (IS_CHILD(seg->children[side]))` block is probably the way to stop it crashing while maintaining the behaviour of D1.

**Comment by vLKp** [comment]
Your edit seems correct.  I cannot find any indication that TRIGGER_ON is meaningful, and when I removed it locally, the game still built.  I see that D2 has a trigger flag `TF_DISABLED`, which suggests that the trigger disabling logic in D1 was not working and that `TF_DISABLED` was how they fixed it.

**Comment by vLKp** [comment]
I pushed an alternative fix of removing the offending code.  More detailed discussion is included in the pull request (#518).  I believe that fix will resolve this crash, so I am closing this issue.  If you still see problems, please reopen.
