### ISSUE TITLE
Runtime bug: Wrong savefile slot is auto-picked when load/save menu is opened

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#524]
### Environment
4f26a205ead1ccf7bbf1b777a50379bc9f5243c8

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
Applies to any mission.

### Description
When opening the save/load menu in-game, the slot picked initially is off by one (at least if a file is present on the previous slot, too).

It is correct if the file last loaded or saved is in the first slot, but if it is in the second slot, the first slot is picked instead; if in the third, the second one is picked instead, etc. This can easily lead to users accidentally saving over the wrong file slot.

#### Regression status
Not a bug from the original game, not present in Rebirth 0.58.1 or 0.60.0-beta2-373-g7e362f943342 (7e362f9).

### Steps to Reproduce
Expected:
1. Start a game.
2. Open save menu
3. Save to file slot 2 (to make sure slot is not empty).
4. Open save menu again
5. Save to file slot 3.
6. Open load or save menu
7. Slot 3 is selected/highlighted

Actual:
1. Start a game.
2. Open save menu
3. Save to file slot 2 (to make sure slot is not empty).
4. Open save menu again
5. Save to file slot 3.
6. Open load or save menu
7. Slot 2 is selected/highlighted instead

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by AlumiuN** [comment]
I can confirm this is replicable, with a small addendum: the save menu always displays the problem, even after saving once, however the load menu seems to only do so after saving the second time.

**Comment by vLKp** [comment]
The above commit resolves the issue for me.  Please sync, test, and report back.

**Comment by ziplantil** [comment]
Issue seems fixed for me too, closing.
