### ISSUE TITLE
Runtime bug: Hoard mode broken (no green orb after kill)

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#526]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200630-win.zip

(BTW: latest downloadable version for Windows seems to have the exact same hash code in the version line under the main menu. That's why I didn't test with the latest version)

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Bug does not depend on level.

### Description

The hoard mode seems to be broken: Killed players won't drop a green orb but receive one uppon respawn.

#### Regression status

Unknown. In the original game this was different (killed player dropped green orb).

### Steps to Reproduce

Expected behaviour:
- Player A kills player B
- Player B drops a green orb which can be picked up by player A

Observed behaviour:
- Player A kills player B
- No green orb is droped so no orb can be picked up
- Player B respawns and has an orb on board (left upper corner)

* Engines affected:
  * [ ] D1X-Rebirth  <- not tested
  * [X] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [X] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
    * [X] Hoard
    * [X] Team Hoard
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [X] Game guests

**Comment by vLKp** [comment]
Confirmed.  The above commit fixes the reported issues for me in regular Hoard mode.  I did not test Team Hoard, but I expect it to be fixed too.  Please sync and test.

**Comment by snytek** [comment]
Great! 
As I don't compile myself I have to wait for an official release end of month. Or is there a quicker way to get a compiled version to test the fix?

**Comment by vLKp** [comment]
I do not provide snapshot builds.  You can wait for @zicodxx or @Mako88 to post one, or you can make one yourself.  I like to think that the instructions for creating personal builds are sufficient that you can follow them without any domain knowledge.  If you decide to try that, and get stuck, please file an issue about the documentation.  It _should_ be good enough for you, and if it is not, I want to make it better.

**Comment by vLKp** [comment]
I think there is nothing further for me to do here.  Closing.  Please reopen if you still see a problem in a build with the above commit.
