### ISSUE TITLE
Runtime bug: Demos recorded with Rebirth result in looping powerup pick-up sounds, even in vanilla Descent 2

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#528]
Tested on 81a9334, Win10, 32-bit EXE; thanks to Xfing for mentioning this.

Currently, demos recorded with Rebirth loop every pick-up sound endlessly. This also applies when the demo in question is played in DOS D2 (D1 demos played in DOS simply end whenever the player picks anything). I am unsure when this started, however Xfing said it occurs with the 16/01/2020 version as well.

Attached is a small demo (in D2:CS, level 10) that displays the problem.
[test.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/5019936/test.zip)

**Comment by vLKp** [comment]
This might be a duplicate of #477.  The demo code is such a mess that I don't tend to prioritize its bugs.  It is interesting though that this apparently causes previously working builds to do the wrong thing with sounds, which suggests that there is an ancient bug in handling the sounds that is now reliably triggered by some relatively recent change.

**Comment by AlumiuN** [comment]
Oh, yep, this is definitely a duplicate of that, my bad.

**Comment by vLKp** [comment]
Your report included new and interesting information, though.  The first report did not state that bad demos remained bad even when played back in legacy clients, so it was unclear whether the issue was in reading the demo or in writing it.  Your statement that a bad demo is bad everywhere clearly blames the creation of the demo.

**Comment by AlumiuN** [comment]
Yeah, and had I thought about it I would have added that information to that issue. Thankfully, it's now unnecessary :)
