### ISSUE TITLE
Runtime bug: MacPlay Descent 1 sound effect patch fails to load

### ISSUE THREAD

**Issue by Kreeblah** [dxx-rebirth/dxx-rebirth#542]
### Environment

https://github.com/dxx-rebirth/dxx-rebirth/commit/faf37e3c1498d45ecb7220ee4bf52a9589029451

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [x] macOS 10.15

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

This is specific to the MacPlay version of Descent 1.

### Description

Because the MacPlay version doesn't have sound effects included in the resource files, they need to be patched in.  However, when attempting to do so, the following error shows up in the log instead:

Warning: Can't read Sounds/sounds.array: not found

#### Regression status

I tracked this down to this specific commit.  It works fine in the prior commit, https://github.com/dxx-rebirth/dxx-rebirth/commit/514c63efadd589a542723c04a35db6fb9259a61d

### Steps to Reproduce

Build the affected commit and load a game with the MacPlay versions of descent.hog and descent.pig, along with a DXA patch to add in sound effects (in my case, I'm using one which adds SND0000.raw through SND0097.raw).

* Engines affected:
  * [x] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by vLKp** [comment]
Usually, it is more helpful to identify the first bad commit, rather than the last good commit, since it is the change in the first bad commit that caused the problem.  In this case, I had checked the code before making the bad commit, but I missed one spot, where the change to the length of the array caused Descent 1 to change behavior, by trying to read 4 elements more.

**Comment by vLKp** [comment]
The steps to reproduce did not indicate how to get the MacPlay data, so I did not attempt to reproduce this.  However, from code inspection, I see that `piggy_read_sounds` would have begun reading more elements, and the commit above reverses that, so I think this should fix the problem.  Please sync and test.

**Comment by Kreeblah** [comment]
Ah, sorry.  The commit I identified in the environment was the first bad one.  I guess I could have called more attention to that.  As far as the MacPlay data, it was descent.hog and descent.pig from the MacPlay version.  I don't recall where I got the patch from, though.

I just tested this commit, and it works fine now.

Thanks!
