### ISSUE TITLE
Runtime bug: Automap sometimes moves on its own in Linux 

### ISSUE THREAD

**Issue by miky-kr5** [dxx-rebirth/dxx-rebirth#545]
### Environment
Commit 97a1bf2b27bd39d30c95c20179324925b21f1973 compiled with the SDL 1.2 profile. The SDL 2 profile fails to compile with linking errors related to the methods used for Redbook Audio (the specific error message and compilation line is copied at the end of this issue)

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [ ] Mac OS X 10.14
  * [ ] Mac OS X 10.15

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [x] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Happens on any map of the base campaing in both Descent 1 and Descent 2

### Description

The automap most of the time is completely unusable because it starts moving randomly, as if an input key was held down. It looks like this https://www.dropbox.com/s/mn85vqidykyq97i/vokoscreen-2020-10-09_23-53-38.gif?dl=0 (sorry for the Dropbox link, tried to upload it to Imgur but it kept failing on me).

It only happens on the automap, though, not during gameplay. And it doesn't happen always, but it does happen with great frecuency.

#### Regression status

Tried to test it with 0.59 (compiled from source from this tag https://github.com/dxx-rebirth/dxx-rebirth/releases/tag/0.59.100) but couldn't get it to compile due to the PhysFS library version.

### Steps to Reproduce

- Expected behavior: the automap moves only when the corresponding keys are pressed.
- Observed behavior: the automap moves on it own, seemingly at random.
- Engines affected: d1x and d2x.
- Steps: start a new game and open the automap. This always works as intended. Move around a bit and open the automap again and it may start moving randomly. It doesn't always happen, as I said, but once it stars moving on its own it very rarely stops.
- Frequency: seems to happen in any level in both games.
- Only tested in single player.

The issue seems to happen no matter the input method enabled, whether it's keyboard only or mouse+keyboard. And it also happens with the mouse settings at default, or with the sensitivity sliders increased.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

Not tested in multiplayer.

### Compilation error with SDL 2

The compilation command `scons d1x=sdl2, sdl2_sdl2=1 sdl2_builddir_prefix=sdl2/ -j4` fails with the following error. The text "referencia a X sin definir" means "reference to X undefined" in Spanish.

```
...
scons: Building targets ...
LD  d1x sdl2/linux-32d70693-ogl/d1x-rebirth/d1x-rebirth
sdl2/linux-32d70693-ogl/common/arch/sdl/event.o: En la función `dcx::event_enable_focus()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/event.cpp:272: referencia a `SDL_WM_GrabInput' sin definir
sdl2/linux-32d70693-ogl/common/arch/sdl/event.o: En la función `dcx::event_disable_focus()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/event.cpp:272: referencia a `SDL_WM_GrabInput' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `redbook_repeat_func()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:441: referencia a `dcx::RBAPlayTracks(int, int, void (*)())' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `d1x::songs_have_cd() [clone .part.7]':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:408: referencia a `dcx::RBAGetDiscID()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `dcx::songs_set_volume(int)':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:127: referencia a `dcx::RBASetVolume(int)' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:128: referencia a `dcx::RBASetVolume(int)' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_stop_all()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:312: referencia a `dcx::RBAStop()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:312: referencia a `dcx::RBAStop()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_pause()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:328: referencia a `dcx::RBAPause()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_resume()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:342: referencia a `dcx::RBAResume()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_pause_resume()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:353: referencia a `dcx::RBAPauseResume()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_stop_all()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:312: referencia a `dcx::RBAStop()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `d1x::songs_init()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:282: referencia a `dcx::RBAInit()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `d1x::songs_play_song(int, int)':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:511: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:533: referencia a `dcx::RBAPlayTracks(int, int, void (*)())' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:523: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:525: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:525: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:525: referencia a `dcx::RBAPlayTracks(int, int, void (*)())' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:527: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `songs_stop_all()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:312: referencia a `dcx::RBAStop()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.songs.o: En la función `d1x::songs_play_level_song(int, int)':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:647: referencia a `dcx::RBAGetNumberOfTracks()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:673: referencia a `dcx::RBAEnabled()' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/songs.cpp:677: referencia a `dcx::RBAPlayTracks(int, int, void (*)())' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.inferno.o: En la función `dcx::standard_handler(dcx::d_event const&)':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/inferno.cpp:385: referencia a `dcx::RBACheckFinishedHook()' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.inferno.o: En la función `dcx::d_interface_unique_state::update_window_title()':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/inferno.cpp:421: referencia a `SDL_WM_SetCaption' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/main/inferno.cpp:414: referencia a `SDL_WM_SetCaption' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.inferno.o: En la función `main':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/inferno.cpp:547: referencia a `SDL_Linked_Version' sin definir
sdl2/linux-32d70693-ogl/similar/arch/ogl/.d1x-rebirth.gr.o: En la función `dcx::ogl_swap_buffers_internal()':
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:168: referencia a `SDL_GL_SwapBuffers' sin definir
sdl2/linux-32d70693-ogl/similar/arch/ogl/.d1x-rebirth.gr.o: En la función `dcx::gr_toggle_fullscreen()':
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:519: referencia a `SDL_VideoModeOK' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:526: referencia a `SDL_SetVideoMode' sin definir
sdl2/linux-32d70693-ogl/similar/arch/ogl/.d1x-rebirth.gr.o: En la función `dcx::gr_list_modes(std::array<screen_mode, 50ul>&)':
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:663: referencia a `SDL_ListModes' sin definir
sdl2/linux-32d70693-ogl/similar/arch/ogl/.d1x-rebirth.gr.o: En la función `d1x::gr_set_mode(screen_mode)':
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:699: referencia a `SDL_VideoModeOK' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:376: referencia a `SDL_WM_SetCaption' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:378: referencia a `SDL_WM_SetIcon' sin definir
/home/miky/Documentos/repos/dxx-rebirth/similar/arch/ogl/gr.cpp:396: referencia a `SDL_SetVideoMode' sin definir
sdl2/linux-32d70693-ogl/common/arch/sdl/key.o: En la función `dcx::key_flush()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/key.cpp:579: referencia a `SDL_GetKeyState' sin definir
sdl2/linux-32d70693-ogl/common/arch/sdl/key.o: En la función `dcx::key_toggle_repeat1()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/key.cpp:611: referencia a `SDL_EnableKeyRepeat' sin definir
sdl2/linux-32d70693-ogl/common/arch/sdl/key.o: En la función `dcx::key_init()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/key.cpp:551: referencia a `SDL_EnableUNICODE' sin definir
sdl2/linux-32d70693-ogl/common/arch/sdl/key.o: En la función `dcx::key_toggle_repeat0()':
/home/miky/Documentos/repos/dxx-rebirth/common/arch/sdl/key.cpp:620: referencia a `SDL_EnableKeyRepeat' sin definir
sdl2/linux-32d70693-ogl/similar/main/.d1x-rebirth.gamecntl.o: En la función `d1x::(anonymous namespace)::HandleSystemKey(int)':
/home/miky/Documentos/repos/dxx-rebirth/similar/main/gamecntl.cpp:929: referencia a `dcx::RBAEjectDisk()' sin definir
collect2: error: ld returned 1 exit status
...
```

**Comment by vLKp** [comment]
I cannot reproduce the random-movement effect in the automap using SDL1, but it happened the first time I tried with SDL2.

I cannot reproduce the build failure with SDL2.  However, the failure you show is strange.  The undefined references should have been eliminated by the preprocessor test for `SDL_MAJOR_VERSION`.  Please clean your build area, then build again with the options you showed, and `verbosebuild=1`.  Report whether that succeeds.  If it fails, post the full build log as an attachment to this ticket.

If you prefer not to translate error messages, you can cause the compiler to produce the error in English by setting `$LC_MESSAGES` to `C` before building.  Your translation is sufficient for this case.

**Comment by vLKp** [comment]
I was able to semi-consistently reproduce the automap drift in an SDL1 build.  The problem seems to be that `Controls` is not cleared, causing the automap to act as if some recently used set of movement modifiers is still active.  I cannot reproduce the problem with a build based on the code I pushed a few minutes ago.  That code includes some changes to thread `Controls` through more functions, which should provide greater consistency on what is reset.

Please sync and retest.  If the automap drift problem still occurs, please post steps to reproduce, and reopen the issue.

**Comment by miky-kr5** [comment]
The automap seems to be working fine now in both SDL 1.2 and SDL 2. And I think the SDL 2 compilation issues were due to a previous SDL 1.2 compilation that I didn't clean up properly. Thank you.
