### ISSUE TITLE
Runtime bug: Listed variable menu items are not displayed

### ISSUE THREAD

**Issue by Donkyhotay** [dxx-rebirth/dxx-rebirth#546]
### Environment

commit: ddcf8c1

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [ ] Mac OS X 10.14
  * [ ] Mac OS X 10.15

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)
  * [x] Lubuntu 20.10 (Groovy)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

When first launching the game, the player name list is not displayed. The name is still listed, I can blindly select it, I just can't see what it is that I have highlisted though. Happens with both d1x and d2x. I have noticed this also affects the "browse for files in the jukebox" option as nothing is listed there though again I can apparently blindly select items. I have not tested much further but this seems to affect all "menu listings that are variable".

#### Regression status

I did not notice this problem with commit 295619e which is the previous commit I compiled and tested before this one.

### Steps to Reproduce

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by vLKp** [comment]
A recent reorganization led to the listbox variable `nitems` being left uninitialized, which could have a variety of problems.  I pushed 31bb275b0f51880a156a30b58512d6125bd96597 to fix that.  Please sync and retest.

**Comment by Donkyhotay** [comment]
Compiled commit: 31bb275 and confirmed all missing menu items that were not displayed before are now in both d1x and d2x. Thank you.
