### ISSUE TITLE
Unification: -Werror=maybe-uninitialized triggered in vecmat.cpp when building on RPi

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#55]
I tried to build the latest unification HEAD on RPi and got this error:

> g++-4.8 -c -O2 -Wall -Werror=missing-declarations -Werror=pointer-arith -Werror=undef -Werror=type-limits -Werror=missing-braces -Werror=uninitialized -Werror=empty-body -Werror=ignored-qualifiers -Werror=unused -Werror=format-security -funsigned-char -O4 -Werror=redundant-decls -std=gnu++0x -Wno-missing-field-initializers -pthread -Wno-sign-compare -isystem=/opt/vc/include -isystem=/opt/vc/include/interface/vcos/pthreads -isystem=/opt/vc/include/interface/vmcs_host/linux -DHAVE_STRUCT_TIMESPEC -DHAVE_STRUCT_TIMEVAL -DOGLES -DOGL -DNDEBUG -DRELEASE -DUSE_UDP -DUSE_TRACKER -DRPI -DWORDS_NEED_ALIGNMENT -Icommon/include -Icommon/main -I. -I/usr/include/SDL common/maths/vecmat.cpp -o common/maths/vecmat.o
common/maths/vecmat.cpp: In function ‘fixang vm_vec_delta_ang(const vms_vector&, const vms_vector&, const vms_vector&)’:
common/maths/vecmat.cpp:148:17: error: ‘t1.vms_vector::z’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t z1 = v.z;
                 ^
common/maths/vecmat.cpp:378:16: note: ‘t1.vms_vector::z’ was declared here
  vms_vector t0,t1;
                ^
common/maths/vecmat.cpp:146:17: error: ‘t1.vms_vector::y’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t y1 = v.y;
                 ^
common/maths/vecmat.cpp:378:16: note: ‘t1.vms_vector::y’ was declared here
  vms_vector t0,t1;
                ^
common/maths/vecmat.cpp:144:17: error: ‘t1.vms_vector::x’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t x1 = v.x;
                 ^
common/maths/vecmat.cpp:378:16: note: ‘t1.vms_vector::x’ was declared here
  vms_vector t0,t1;
                ^
common/maths/vecmat.cpp:147:15: error: ‘t0.vms_vector::z’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t z0 = z;
               ^
common/maths/vecmat.cpp:378:13: note: ‘t0.vms_vector::z’ was declared here
  vms_vector t0,t1;
             ^
common/maths/vecmat.cpp:145:15: error: ‘t0.vms_vector::y’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t y0 = y;
               ^
common/maths/vecmat.cpp:378:13: note: ‘t0.vms_vector::y’ was declared here
  vms_vector t0,t1;
             ^
common/maths/vecmat.cpp:143:15: error: ‘t0.vms_vector::x’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int64_t x0 = x;
               ^
common/maths/vecmat.cpp:378:13: note: ‘t0.vms_vector::x’ was declared here
  vms_vector t0,t1;
             ^
cc1plus: some warnings being treated as errors
scons: *** [common/maths/vecmat.o] Error 1
scons: building terminated because of errors.

This is with

>gcc version 4.8.2 (Raspbian 4.8.2-21~rpi3rpi1) 

Interestlingly, there is no special casing for the RPi in this case, but  I'm not able to reproduce the issue on a desktop machine, even when using gcc 4.8.2.

However, the RPi gcc seems to be right. The code in question is:

    fixang vm_vec_delta_ang(const vms_vector &v0,const vms_vector &v1,const vms_vector &fvec)
    {
        vms_vector t0,t1;

        vm_vec_copy_normalize(t0,v0);
        vm_vec_copy_normalize(t1,v1);

        return vm_vec_delta_ang_norm(t0,t1,fvec);
    }

in combination with

    vm_magnitude vm_vec_copy_normalize(vms_vector &dest,const vms_vector &src)
    {
        auto m = vm_vec_mag(src);
        if (m) {
                vm_vec_divide(dest, src, m);
        }
        return m;
    }

So there is the potential case that m is 0, and both vectors hence uninitialized...

**Comment by vLKp** [comment]
The compiler can only recognize this problem after inlining.  The RPi may have different inlining limits since it is a different instruction set.

Fixed in 5e4bd5c73f24a36654038cef8cfe242bf49e0b83.
