### ISSUE TITLE
[Feature Request] Add level name to summary screen

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#553]
Hi

On the summary screen, which is displayed at level end, you have plenty information about the type of level, kills and deaths. 
What is actually missing is the level name! 

Would it be very complicated to add this information to that screen?

Cheers
Snytek

**Comment by vLKp** [comment]
That seems useful.  I will look into it.

**Comment by vLKp** [comment]
The above commit, much delayed, provides the requested change.  Please reopen if you think this requires further changes.
