### ISSUE TITLE
Runtime bug: All but classic reticles are broken.

### ISSUE THREAD

**Issue by aybe** [dxx-rebirth/dxx-rebirth#554]
dxx-rebirth_20201029-win
 
#### Operating System Environment
  
Microsoft Windows [Version 10.0.19042.630]
(c) 2020 Microsoft Corporation. All rights reserved.

#### CPU environment

 
* [x] x86\_64 (64-bit Intel/AMD)

### Description

All but classic reticles are broken.

### Steps to Reproduce

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
 
![2020-11-28 21-32-03](https://user-images.githubusercontent.com/1537591/100527123-b46d8600-31cf-11eb-8b4f-50cd75e14e42.png)
![2020-11-28 21-32-35](https://user-images.githubusercontent.com/1537591/100527124-b59eb300-31cf-11eb-8e95-b037dfd4a538.png)
![2020-11-28 21-32-58](https://user-images.githubusercontent.com/1537591/100527125-b59eb300-31cf-11eb-90c4-3e689632c190.png)
![2020-11-28 21-33-28](https://user-images.githubusercontent.com/1537591/100527126-b59eb300-31cf-11eb-88a0-2073ab48a1aa.png)
![2020-11-28 21-34-43](https://user-images.githubusercontent.com/1537591/100527127-b6374980-31cf-11eb-9156-d002e8c78694.png)
![2020-11-28 21-36-00](https://user-images.githubusercontent.com/1537591/100527128-b6374980-31cf-11eb-829f-6aef954ad517.png)
![2020-11-28 21-51-32](https://user-images.githubusercontent.com/1537591/100527129-bf281b00-31cf-11eb-85ae-51cdfe62f0da.png)

**Comment by aybe** [comment]
Also, restarting the game doesn't change anything.

**Comment by vLKp** [comment]
Some of those screenshots do appear to have an incorrect reticle, but the reticles look correct to me on my system.  Is this a recent regression?

I notice that the class 1 drone in some of these pictures is rendered incorrectly as well.  Is that also new?

**Comment by aybe** [comment]
I just came here like few days ago so I can't tell.

Good catch, I didn't really notice about the drone.

I tried a few things, switched from 150% DPI to 100% DPI in Windows, switched from 3840*2160 to 1920*1200 and restart the game but none had an effect.

It's pretty clear that at this point having an history of builds would be of great help ;)

**Comment by vLKp** [comment]
> It's pretty clear that at this point having an history of builds would be of great help ;)

@zicodxx maintains such a history: the [https://www.dxx-rebirth.com/download-archive-dxx-rebirth/](DXX-Rebirth download archive).  It's even linked from the page where he posts the current snapshot build.

**Comment by aybe** [comment]
Yes I know there are these but as we talked previously for the slow menu bug, having more granularity, i.e. nightly builds would be helpful.

**Comment by vLKp** [comment]
I agree that having more granularity in testing would be helpful, which is why I make it a goal to have every commit build cleanly for every target.  I disagree that a nightly build would be particularly useful, since I tend to post my work in batches, so nightlies would not give you enough precision.

@aybe: have you been able to determine when this first broke for you, or identify what is required to reproduce the break?  Since I cannot reproduce it and have no specific known bad commit, there is nothing I can do to work on this.

**Comment by zicodxx** [comment]
@aybe I am sorry for this issue. I always try to give the builds a bit of a testing, but I wasn't able to catch this one. I uploaded new builds today and unfortunately also been unable to reproduce this. In case you still experience the issue on the builds of today, could you pack up your descent.cfg, your player files and the ini (in case you made some modifications) so I can check out the results with your exact settings? Things like resolutions, anti-aliasing and such could potentially cause differences.

**Comment by vLKp** [comment]
No further response from original reporter.  Not reproducible here.  There is nothing more that can be done with the information available.

@aybe: if this still affects you, please answer the questions above and reopen the issue.
