### ISSUE TITLE
Runtime bug: Descent 2 menus are very slow

### ISSUE THREAD

**Issue by aybe** [dxx-rebirth/dxx-rebirth#555]
dxx-rebirth_20201029-win

#### Operating System Environment

 
Microsoft Windows [Version 10.0.19042.630]
(c) 2020 Microsoft Corporation. All rights reserved.

#### CPU environment

 
* [x] x86\_64 (64-bit Intel/AMD)

### Description

Menus are very slow to navigate, a couple of seconds to enter each sub-menu.

### Steps to Reproduce
 
* Engines affected:
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player

**Comment by vLKp** [comment]
This was previously reported by @Q3BFG10K in issue #549 (along with a different problem, in the same ticket).  It does not happen for me.  Since it does not happen for me, I cannot debug it or attempt to bisect it to determine when it was introduced.  If you can use `git bisect` to identify the commit where it first began, I can examine that commit to try to find an explanation.

**Comment by aybe** [comment]
I just read the issue you've linked to, my problem is more or less the same, it's quite overkill to have to build specific commits, even more for non Linux/MinGW/GCC users.

Aren't these nightlies sitting in some dev's hard drive ? It'd be nice to have them as direct downloads so people can test without having to do any building of some sort.

For INSTALL.markdown, well ... it's quite cryptic to be honest (Win/VS user here):

- Python -> ok, that's easy
- SCons -> got a .zip but what am I supposed to do with it ? doesn't Python have a package manager anyway ?
- MinGW -> somewhat okay though `mingw-gcc` does not exist in the GUI, name is slightly different
- SDL -> should this be dropped somewhere in cloned repo ?
- PhysFS -> basically, we're on your own

Have precise and tested installation instructions would certainly be of great help!

**Comment by vLKp** [comment]
> it's quite overkill to have to build specific commits, even more for non Linux/MinGW/GCC users.

If I could reproduce the issue, I would be happy to do the bisection myself.

> Aren't these nightlies sitting in some dev's hard drive ?

Not that I know of.  I build what I need when I need it, and discard it after I am done.  I don't publish Windows builds at all.

> For INSTALL.markdown, well ... it's quite cryptic to be honest (Win/VS user here):

Suggestions for documentation improvements are always welcome.

> * SCons -> got a .zip but what am I supposed to do with it ? doesn't Python have a package manager anyway ?

Python has `pip` for installing packages from the Python Package Index.  I get SCons from my distribution's package manager, not from `pip`.

> * MinGW -> somewhat okay though `mingw-gcc` does not exist in the GUI, name is slightly different

What name should be used?

> * SDL -> should this be dropped somewhere in cloned repo ?

SDL is tracked in a Mercurial repository; according to their site, it can be cloned with `hg clone http://hg.libsdl.org/SDL`.

> * PhysFS -> basically, we're on your own

That was my experience when last I looked, yes.

**Comment by arbruijn** [comment]
I had also noticed the slowdown, but only on Windows. It seems to be caused by the switch to SDL_image, that made pcx files open with PHYSFSRWOPS_openRead. That's an unbuffered open, so it does a lot of small read calls to the OS, which is slow on Windows.

I was able to fix it by adding a call to PHYSFS_setBuffer in PHYSFSRWOPS_openRead, but a separate PHYSFSRWOPS_openReadBuffered might be better (similar to PHYSFSX_openReadBuffered).

**Comment by aybe** [comment]
@vLKp 

I've opened #558.

Also, you could make good use of the nice release section on GitHub by, say, automatically pushing interim builds in the future. A quick search on how to automate it brings this: https://github.com/release-it/release-it.

@arbruijn 
Nice, any build to test it?

**Comment by vLKp** [comment]
Based on the comment by @arbruijn, I believe the above commit should resolve the reported slowness.  If the slowness persists in a build with this commit, please reopen.

@aybe: `release-it` appears to require use of `npm`.

**Comment by aybe** [comment]
Alright.

About npm, not sure what you meant but okay :)

**Comment by vLKp** [comment]
The comment to which I was responding appeared to be pushing me to use `release-it`.  However, the documentation for `release-it` makes clear that it requires use of `npm`, and a quick scan of its repository confirms that it is written in NodeJS.  The Node ecosystem has been such a persistent disaster area that I refuse to install `npm` or `nodejs` in my development environment.  As a consequence, anything which relies on those is unusable.

**Comment by aybe** [comment]
Okay, that's more or less what I understood (that you didn't want to use for some reason).
