### ISSUE TITLE
Unification: call of overloaded ‘SWAPSHORT(const int&)’ is ambiguous with -DWORDS_NEED_ALIGNMENT

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#56]
Trying to build the latest unification HEAD on the RPi. Now this happens
in a WORDS_NEED_ALIGNMENT specific code path:

> g++-4.8 -c -O2 -Wall -Werror=missing-declarations -Werror=pointer-arith -Werror=undef -Werror=type-limits -Werror=missing-braces -Werror=uninitialized -Werror=empty-body -Werror=ignored-qualifiers -Werror=unused -Werror=format-security -Werror=redundant-decls -funsigned-char -O4 -std=gnu++0x -Wno-missing-field-initializers -pthread -Wno-sign-compare -isystem=/opt/vc/include -isystem=/opt/vc/include/interface/vcos/pthreads -isystem=/opt/vc/include/interface/vmcs_host/linux -DHAVE_STRUCT_TIMESPEC -DHAVE_STRUCT_TIMEVAL -DUSE_SDLMIXER -D_REENTRANT -DDXX_VERSION_SEQ=0,58,1 -D__STDC_FORMAT_MACROS -DDXX_BUILD_DESCENT_I -DOGLES -DOGL -DNDEBUG -DRELEASE -DUSE_UDP -DUSE_TRACKER -DRPI -DWORDS_NEED_ALIGNMENT -DSHAREPATH=\"/usr/share/games/d1x-rebirth/\" -Icommon/include -Icommon/main -I. -I/usr/include/SDL -Id1x-rebirth/include -Id1x-rebirth/main -Id1x-rebirth/arch/include similar/main/polyobj.cpp -o similar/main/.d1x-rebirth.polyobj.o
In file included from similar/main/polyobj.cpp:38:0:
common/include/byteutil.h: In instantiation of ‘T INTEL_SHORT(const T&) [with T = int]’:
similar/main/polyobj.cpp:242:65:   required from here
common/include/byteutil.h:71:41: error: call of overloaded ‘SWAPSHORT(const int&)’ is ambiguous
 #define byteutil_choose_endian(F,a) (F(a))
                                         ^
common/include/byteutil.h:78:9: note: in expansion of macro ‘byteutil_choose_endian’
  return byteutil_choose_endian(SWAPSHORT, x);
         ^
common/include/byteutil.h:71:41: note: candidates are:
 #define byteutil_choose_endian(F,a) (F(a))
                                         ^
common/include/byteutil.h:78:9: note: in expansion of macro ‘byteutil_choose_endian’
  return byteutil_choose_endian(SWAPSHORT, x);
         ^
In file included from similar/main/polyobj.cpp:38:0:
common/include/byteutil.h:39:24: note: uint16_t SWAPSHORT(const uint16_t&)
 static inline uint16_t SWAPSHORT(const uint16_t &x)
                        ^
common/include/byteutil.h:44:23: note: int16_t SWAPSHORT(const int16_t&)
 static inline int16_t SWAPSHORT(const int16_t &i)
                       ^
In file included from similar/main/polyobj.cpp:38:0:
common/include/byteutil.h: In function ‘T INTEL_SHORT(const T&) [with T = int]’:
common/include/byteutil.h:79:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scons: *** [similar/main/.d1x-rebirth.polyobj.o] Error 1
scons: building terminated because of errors.

**Comment by derhass** [comment]
The offending line is

    *((short *)(cur_ch.new_base + cur_ch.offset))= INTEL_SHORT(cur_ch.correction+ INTEL_SHORT(*((short *)(cur_ch.old_base + cur_ch.offset))));

so this seems just a victim of integer promtion, because we have `INTEL_SHORT( (short) + INTEL_SHORT( (short) ) )` which is simply `INTEL_SHORT( (short) + (short) )`.

**Comment by vLKp** [comment]
Fixed in df9ce26dfb12f4ea60033400870e7500a4ec416f.
