### ISSUE TITLE
Runtime bug: New game dialog text is shifted to the side if open with mouse

### ISSUE THREAD

**Issue by dimag0g** [dxx-rebirth/dxx-rebirth#564]
### Environment
Commit 7204b91e1aad6d359661f1084cad8e9971f28408
`scons -j4`

#### Operating System Environment
Raspbian Buster, Pi 4B
Windows 10, Msys2 + MinGW-w64

#### CPU environment

* [X] x86 (32-bit Intel/AMD)
* [ ] x86\_64 (64-bit Intel/AMD)
* [X] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description
The text in the New Game dialog is rendered outside of dialog borders.

#### Regression status
Not present in commit 03512841b19315532a95cadc1d6351e24a70136c. Seems to be related to newmenu changes.

### Steps to Reproduce
Start the game and click on "New Game" with the mouse pointer.

![2021-01-16-224949_1280x720_scrot](https://user-images.githubusercontent.com/10945319/104823975-82cb7f80-584e-11eb-82e5-0f9658fc7364.png)

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by AlumiuN** [comment]
I don't have time to test further at the moment, but this doesn't happen for me at 2560x1440 in fullscreen. Does it happen for you at higher resolutions?

**Comment by dimag0g** [comment]
@AlumiuN, Yes, it happens in fullscreen too (at 1280x720). The important step is to click on the menu with the mouse, selecting "New Game" with the keyboard works fine. Could be a Linux/SDL1 exclusive, which OS/build options do you have?

**Comment by AlumiuN** [comment]
I'm running on Windows 10 20H2, using the SDL1 build (I'm not specifying any other options). I have tested it again and it functions correctly for me at lower resolutions.

**Comment by dimag0g** [comment]
I seem to have the same issue on Windows, using Msys2 as described [here](https://github.com/cbrt64/dxx-rebirth/blob/docs-windows-native-building/INSTALL.markdown#compiling-with-msys2). Apparently there is still a gcc bug in current wingw32, even if it's gcc10. I had to reactivate the workaround in `bitblt.cpp` in order to build:

     void *(__attribute__((__cdecl__)) *d_memcpy)(void*, const void*, size_t) = memcpy;

**Comment by vLKp** [comment]
Confirmed, for both the mouse/text problem, and the i686-w64 gcc bug.  I missed the mouse/text problem because I use keyboard navigation normally, and keyboard is fine.

@dimag0g: I pushed [Expand gcc memcpy workaround to gcc-10](/dxx-rebirth/dxx-rebirth/commit/775d03908367410ba834b009d2a7d6033504cbf8) in response to your comment.

**Comment by vLKp** [comment]
The above commit resolves the problem for me.  Please reopen if you still see a problem.
