### ISSUE TITLE
Runtime crash: D1X crash on key press in save game dialog, Apple Silicon compiled. 

### ISSUE THREAD

**Issue by kitelessd** [dxx-rebirth/dxx-rebirth#571]
### Environment
Homebrew

#### Operating System Environment
macOS Big Sur 11.2

#### CPU environment
Apple Silicon M1 SOC

#### Game environment
D1X Rebirth compiled for Apple Silicon

### Description
Crashes on save game dialog keypress

### Steps to Reproduce
Game plays fine. Go into the save dialog, comes up fine, the moment a key is pressed to give the save a name, it instantly crashes. Currently in it's default compiled state. Haven't tried to roll it all up into a .app package yet. Using vanilla 1995 Descent retail asset files. Game does remember that a level has been passed so if I finish level 1, go back to play agains I can start at level 2. But any time I try and enter a name into a save slot, instant crash. 

Crash report attached. 

**Note:** The security dialog would pop up every time I run the game asking for additional access. It was crashing like this before I enabled the access, and also after. So this setting seemed to have no effect. All that, said it seems like this is some kind of security issue, but really I have no idea. 

I haven't had time to try D2X yet. 

[D1X-Crash-Report.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/5940086/D1X-Crash-Report.txt)

**Comment by MaddTheSane** [comment]
Are you using SDL 1.2 or SDL 2?

I am also getting this when built against MacPorts and SDL2.

**Comment by kitelessd** [comment]
I appear to have both installed. I have to assume that it's using SDL2. I'm not a Dev like at all... so I'm not sure. Attached is my build log. Hoping this will help. 

[d1x-sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/5940218/d1x-sconf.log)

**Comment by MaddTheSane** [comment]
Okay, this is just strange…
When building without compiler optimizations, it works just fine.

**Comment by kitelessd** [comment]
Are you compiling on Apple Silicon or Intel? Can you post the command string you use for compile? Here's mine: 

`scons opengl=1 sdlmixer=1 d1x=1 macos_add_frameworks=0 builddir=dx1-build`

Cheers! 

Also what's MacPorts?

**Comment by MaddTheSane** [comment]
So `allowed_chars` for save games should be `NULL` instead of an empty string. Why optimizations is making it an empty string is a mystery.

**Comment by MaddTheSane** [comment]
I'm using Apple Silicon, and my compile options that make it work are these:

    CXXFLAGS="-O0" scons sdl2=yes macos_add_frameworks=no

The `CXXFLAGS` is what's needed to get it to input text in the save slots.
MacPorts is a different package management software I use instead of HomeBrew.

**Comment by kitelessd** [comment]
Ahh great thank you. Sounds like there's something a little wonky about compiling on AS? Maybe @vLKp can find the issue instead of doing a work around in compile. Will give it a try and post me log here shortly. Glad I'm not the only Descent addict trying to compile on M1. I will also specify SDL as you did.

**Comment by kitelessd** [comment]
@MaddTheSane I'm still getting a crash at the save text entry. I also got an error when I tried to specify SDL2. (See SDL2-sconf.log. 

So I ran it like this: 
CXXFLAGS="-O0" scons opengl=1 sdlmixer=1 d1x=1 macos_add_frameworks=0 builddir=dx1-build 

I noticed the flag is "oh zero" is that correct or is that Mac copy/paste being dumb? 

Compile was successful however. See CXXFLAGS-sconf.log attached. 

And finally the crash report. Attached here as well but it looks exactly the same as my original crash report. 

[CXXFLAGS-sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/5940406/CXXFLAGS-sconf.log)
[SDL2-sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/5940407/SDL2-sconf.log)
[D1X-Crash-Report_CXXFLAGS.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/5940409/D1X-Crash-Report_CXXFLAGS.txt)

**Comment by vLKp** [comment]
I saw this report earlier, but it grew quite a bit while I was not looking.

---

I initially could not reproduce this crash on d1x for Linux/amd64, but once I enabled debugging of uninitialized variables, I saw a similar crash.

```
Exception Codes:       KERN_INVALID_ADDRESS at 0xaaaaaaaaaaaaaaaa -> 0xffffaaaaaaaaaaaa (possible pointer authentication failure)
```
This looks like a bad pointer was loaded from somewhere.  This pointer is not under user control.

```
0   d1x-rebirth                   	0x0000000100604a64 dcx::(anonymous namespace)::char_disallowed(char, char const*) + 8 (newmenu.cpp:504) [inlined]
1   d1x-rebirth                   	0x0000000100604a64 dcx::(anonymous namespace)::char_allowed(char, char const*) + 8 (newmenu.cpp:514) [inlined]
2   d1x-rebirth                   	0x0000000100604a64 (anonymous namespace)::newmenu_key_command(dcx::d_event const&, dcx::newmenu*) + 64 (newmenu.cpp:1217) [inlined]
```
This is consistent with the reported reproduction scenario.  When you type a character, `newmenu_key_command` tests whether the character is permissible, by calling `char_allowed`, which is a wrapper that calls `char_disallowed` and inverts the result.  This is primarily used to enforce limits on pilot names, but the test runs for everything.  When the input field in question has no limitations on allowed characters, `char_disallowed` returns a result of allow without checking the character.  Based on your stack trace, it looks like the parameter `allowed_chars` is bogus.  This comes from the `newmenu_item` field `nm_private_imenu.allowed_chars`.  This should have been initialized when the value was constructed, but was not.  I have been working toward changing `newmenu_item` initialization in a way that would have caught this at compile time.  However, for now, I pushed a fix for the specific bad site.  As a temporary measure until I can finish the more general cleanup, I also pushed a change to zero-initialize newmenu_item's union member.

---

The above commit should resolve the crash.  Please reopen if the crash persists in the latest code.

---

> I noticed the flag is "oh zero" is that correct or is that Mac copy/paste being dumb?

That is correct.  It requests Optimization level 0, hence `-O0`.

**Comment by vLKp** [comment]
For completeness, since there was some other debugging going on: this was an uninitialized variable used as a pointer.  There was a special case that if the pointer was `nullptr`, that was legal (and produced the behavior the save game code intended to have).  Disabling optimizations likely had the fortunate accidental effect of putting a `nullptr` (or possibly pointer to `""`) into the stack location that was later read to get this pointer.

**Comment by kitelessd** [comment]
Wanted to just confirm that this all worked. Just did a compile and tested. It's perfect. Thanks for the quick work, support, and future general cleanup. Also shoutout to @MaddTheSane for the knowledge as well! Feel honored I helped (and I use that term loosely) track down some issues. Cheers all. Lets go kill some robots! :D 

[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/5941258/sconf.log)
