### ISSUE TITLE
Runtime bug: 

### ISSUE THREAD

**Issue by Zombie-Ryushu** [dxx-rebirth/dxx-rebirth#580]
Are there any plans for DXX-Rebirth to support playing D1 Missions in D2 Mode with perks such as the use of D2 Weapons in D2 Mode or the Guide bot?

**Comment by vLKp** [comment]
This is not a bug.

The engine already supports this.  You just need to find the D2 weapons or a guidebot, as appropriate.  You can also create them using cheat codes.

**Comment by Zombie-Ryushu** [comment]
Yes but there are strange things like textures being displayed wrong.

**Comment by vLKp** [comment]
True, that is a known issue that has never completely worked right.  However, the levels are still playable because most textures are right, or close enough.  Also, you asked about weapons and a guidebot, not about textures.
