### ISSUE TITLE
Build failure: 

### ISSUE THREAD

**Issue by noabody** [dxx-rebirth/dxx-rebirth#584]
Heftig already commented on the commit and identified the problem.  I did the same thing once, a very long time ago, and the comment wasn't noticed.  As a result, I'm just opening the report with his comment.

Besides, I don't understand what he's saying anyway.  Just that ‘Cursegp’ was not declared in this scope and that is where the build fails for me in Manjaro Linux Ornara 21.0.

[ddb9e8e](https://github.com/dxx-rebirth/dxx-rebirth/commit/ddb9e8e774f1a7ff187079d7a551f6ca02748cc1#commitcomment-49094909)

**Comment by noabody** [comment]
Oh I get it, Heftig is saying that the editor code block has to be guarded.  I can only get a successful build if I do:

```scons editor=yes```

Because that activates the include in gamecntl.cpp

```
#if DXX_USE_EDITOR
#include "editor/editor.h"
#include "editor/esegment.h"
#endif
```

**Comment by vLKp** [comment]
> I did the same thing once, a very long time ago, and the comment wasn't noticed.

Where was this?

> As a result, I'm just opening the report with his comment.

This is the correct venue to report build breaks.  Generally, it would be helpful to be a bit more detailed.  In this case, the break was easy to reproduce.

----

Yes, `Cursegp` only exists in editor builds.  Moreover, the new menu is only used in builds with +editor +debug.  I pushed [Fix break for !DXX_USE_EDITOR](/dxx-rebirth/dxx-rebirth/commit/1ebb73843445f0b6adfbba132d7e681005e39632) to address this.
