### ISSUE TITLE
PC master race standard F5/F9 - quick load and quick save would be nice.

### ISSUE THREAD

**Issue by ruthan** [dxx-rebirth/dxx-rebirth#586]
Hello,
its possible to use some quickload and quicksave and map keys to standart F5 and F9? As far is was searching for it.. i found only ALT-F2 / ALT-F3 slow saving mechanism and its not good enough.

**Comment by vLKp** [comment]
I am not familiar with a "PC master race" nor any standard here for where quicksave/quickload keys should be bound.  Yes, it is possible to use Quicksave and Quickload.  According to the in-game F1 help (and F1 is standard for help), you want Alt-Shift-F2 / Alt-Shift-F3 for QuickSave/QuickLoad.

The game does not support rebinding function keys.  You can, if you wish, patch the source (see `similar/main/gamecntl.cpp`, around line 840) to change these.

Note that in single player, the game should pause while the non-Quick dialogs are open, so there is no rush to pick a slot.

**Comment by ruthan** [comment]
Its standard, same as ALT+F4 for close..

**Comment by AlumiuN** [comment]
That's absolutely not a standard. Alt+F4 is an OS hotkey, anyway.

**Comment by ruthan** [comment]
Hardcoded keys are stone age programming. Alt+F4 is Windows thing, but because Linux is starting behave more and more human, lots of Linux apps already adapted it too.

  Well i reported it, for me it is issue, no will fix it, ok..

**Comment by vLKp** [comment]
@ruthan wrote:

> Its standard, same as ALT+F4 for close..

[Citation needed.](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)

@AlumiuN wrote:

> (and I suspect other OSes as a result)

Generally yes, although on the more customizable window managers, it may be something completely different.  For me, Alt+F4 is iconify, not close.  I could make it be close, but I iconify windows more often than I need to force kill them.

> especially as I don't believe there's currently code for having rebindable controls take modifier keys

True, and controls that involve Fn keys are generally completely hardcoded, so you cannot even move the option to a different Fn key with the same modifiers as currently used.  This is issue #551.  It's not that hard to add an indirection layer to allow custom keys, but I don't want to use the limited graphical libraries that Descent currently has to write a configuration GUI for it, and I expect that the people who most want to rebind these keys are the ones least likely to use a feature that requires manual editing of a configuration file.

@ruthan wrote:

> Hardcoded keys are stone age programming.

Descent is originally a DOS game.  Large parts of that logic survive into the current Rebirth code.

> lots of Linux apps already adapted it too.

Except that, as @AlumiuN wrote above, it's generally not the application that matters, but the window manager.

> Well i reported it, for me it is issue, no will fix it, ok..

You opened a Question class issue (though you did not label it as such).  I answered your questions, and closed the issue as a result.
