### ISSUE TITLE
Unification: texture filter setup via menu does not work

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#59]
Whenever one changes something in the graphcis options menu, the texture filter is reset to nearest, It is impossible to set it back to something else via menu. Setting it via the config file still works. This happens with both d1x and d2x of current unification/master branch.

**Comment by vLKp** [comment]
Fixed in 55fada5c14c7fe67c5f2b5e904ae453e803fd09b.
