### ISSUE TITLE
Runtime bug: Mission menu severely broken when using subdirectories

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#594]
Using Win10 64-bit, 32b7899 (traced the break to commit 7f2df64649796bbbd74edc400baab2edde1287ad)

The mission menu subdirectory handling seems to be severely broken - only the same number of items that are present in the root directory are displayed in any subdirectory (with the notable exception of a folder that the mission selection opens to), and if the entry in the same position in the list as the selected mission is a directory in the root, that directory is opened instead of it selecting the mission in question. My theory is that the subdirectory window is being passed the correct strings for mission names and window title, but incorrect behaviour for the entries.

**Comment by vLKp** [comment]
Agreed.  It looks like the breaking commit had a copy-paste error that passed the wrong variable.  I pushed your proposed fix as-is.
