### ISSUE TITLE
Game autosaves during demo playback

### ISSUE THREAD

**Issue by polstomo** [dxx-rebirth/dxx-rebirth#598]
Commit cae9c5f26c727bd7f3b1bdedd40b1a4831695d8c
Only tested on D1X-Rebirth

Game autosaves during demo playback.
The game becomes quite buggy upon loading the saved game (not that it matters I think; it shouldn't save in the first place)

**Comment by vLKp** [comment]
The above commit prevents the inappropriate autosave.  Please reopen if you see the game save incorrectly during a demo, or miss a save during regular play.

Yes, demos break many rules about how the game environment should work, so restoring the state from one is likely to be very broken.  The original demo design format, which Rebirth retains even today, saved just barely enough to even work as a replay mechanism.
