### ISSUE TITLE
[QoL] Allow warping at any level with new game, even if the player hasn't completed the maps

### ISSUE THREAD

**Issue by AtifArshad1995** [dxx-rebirth/dxx-rebirth#608]
I just came back to playing Descent after sometime and because I had my game deleted, I have to play all the maps in order to unlock them. I think this simple QoL change will be great for any returning player.

**Comment by vLKp** [comment]
[Allow non-developers to start on any level](/dxx-rebirth/dxx-rebirth/commit/b0103a19503247f1b4098a2bbb45f1a6d95c73c3) enables this functionality.  Please sync to `master` and try it out.  Reopen the issue if this change does not suffice.
