### ISSUE TITLE
scons: *** Header physfs.h is usable, but library physfs is not usable.  See build/sconf.log for details.  Stop

### ISSUE THREAD

**Issue by willingtonvr** [dxx-rebirth/dxx-rebirth#618]
#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Ubuntu
  * [ X] Ubuntu 18.04 LTS (Bionic Beaver)

#### CPU environment

* [ x] x86\_64 (64-bit Intel/AMD)

### Description

Hello there!

try to complie, ends with the error , thanks in advance

### Steps to Reproduce

First error was
scons: *** Header physfs.h is usable, but library physfs is not usable.  See build/sconf.log for details.  Stop

Checking on SConstruct  
line 4530 has CPPDEFINES = [('PHYSFS_DEPRECATED', '')],

which generates  a PHYSFS_DEPRECATED=  on the command line like this

*************
g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -std=gnu++17 -Werror -Wno-sign-compare -DPHYSFS_DEPRECATED= -Icommon/include -Icommon/main -I. -Ibuild -I/usr/include/libpng16 build/.sconf_temp/conftest_6.cpp -o build/.sconf_temp/conftest_6.o
************

changed to  CPPDEFINES = [('PHYSFS_DEPRECATED', '1')],

scons: *** Header physfs.h exists, but cannot compile an empty program.  See build/sconf.log for details.  Stop.

last lines of log file are:

g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -std=gnu++17 -Werror -E -Wno-sign-compare -DPHYSFS_DEPRECATED=1 -Icommon/include -Icommon/main -I. -Ibuild -I/usr/include/libpng16 build/.sconf_temp/conftest_6.cpp -o build/.sconf_temp/conftest_6.o
scons: Configure: yes

[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/7878719/sconf.log)

attached is de log file whitout chanfges on SConstruct

**Comment by vLKp** [comment]
Please set `LC_MESSAGES=C` when generating a build log to be posted.  This will cause the tools to emit messages in English, which is easier for maintainers to process and more amenable to searches.

However, I can see part of the problem already.  On your system, `pkg-config --cflags --libs physfs` reported that neither CFLAGS nor libraries are required to use physfs.  This seems unlikely to be correct.  As a result of that report, SCons did not attempt to link libphysfs.so into the test program (because `pkg-config` failed to state that such was needed).  The test program then failed to find any PhysFS symbols.

What is the full output of `pkg-config --version ; pkg-config --modversion physfs ; pkg-config --cflags --libs physfs ; grep -n 'define PHYSFS_VER_' /usr/include/physfs.h`?

**Comment by willingtonvr** [comment]
Hi, thanks for response.

output of pkg-config command:  (seems ubuntu 18.04 does not provide pkg-config files  i've checked de deb packages)

https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libphysfs-dev_3.0.1-1_amd64.deb.html

*********************
0.29.1
Package physfs was not found in the pkg-config search path.
Perhaps you should add the directory containing `physfs.pc'
to the PKG_CONFIG_PATH environment variable
No package 'physfs' found
Package physfs was not found in the pkg-config search path.
Perhaps you should add the directory containing `physfs.pc'
to the PKG_CONFIG_PATH environment variable
No package 'physfs' found
435:#define PHYSFS_VER_MAJOR 3
436:#define PHYSFS_VER_MINOR 0
437:#define PHYSFS_VER_PATCH 1
****************************************************
Attached is a scons.log with english output

[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/7885864/sconf.log)

**Comment by willingtonvr** [comment]
Hello,  seems 18.04 related problem i fixed this way 

since is a problem of the devel packe 
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libphysfs-dev_3.0.1-1_amd64.deb.html it does not provide physfs.pc
iv just picked it from the 20.04 package and manual install it then file:

file name and location: /usr/lib/x86_64-linux-gnu/pkgconfig/physfs.pc 
***********************
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: PhysicsFS
Description: PhysicsFS is a library to provide abstract access to various archives.
URL: https://icculus.org/physfs/
Version: 3.0.1
Libs: -L${libdir} -lphysfs
Cflags: -I${includedir}
************************

Also i've manually mod the scons script to force python3 (since de default on 18.04 is 2.7)

/usr/bin/scons
change 
#! /usr/bin/python
to
#! /usr/bin/python3

be sure you do with root privs

after these changes everything went fine, now i'm playing !
