### ISSUE TITLE
No music in d1x-rebirth when using -hogdir

### ISSUE THREAD

**Issue by arkdae** [dxx-rebirth/dxx-rebirth#628]
### Environment

d1x-rebirth version 20210623-1

#### Operating System Environment

Arch

#### CPU environment

Intel Core i7 920  @ 2.67GHz

### Description

I have been struggling to get music  working with this game. Everything else works fine, my 6DOF controller, sound effects, in-game graphics, etc.

I see this output while running:

    Music descent.hmp could not be loaded: Module format not recognized
    Music briefing.hmp could not be loaded: Module format not recognized
    Music game0.hmp could not be loaded: Module format not recognized
    Music descent.hmp could not be loaded: Module format not recognized

and so I looked at issue #430 

No matter what I did, following the comments made there, I could not get music working until I finally copied all of the DESCENT.* files into ~/.d1x-rebirth/ and ran the game without the -hogdir option.

So, I think the problem is that whatever mechanism extracts the MIDI files from the .hog file is not making use of the -hogdir to go look for them, expecting the files in ~/.d1x-rebirth.

### Steps to Reproduce

Put your DESCENT.* files into some directory other than ~/.d1x-rebirth and run

    d1x-rebirth -hogdir path/to/DESCENT/files

Expected behavior is music plays, but actual behavior is that it doesn't.

* Engines affected:
D1X-Rebirth

* Game modes affected:
All

**Comment by arkdae** [comment]
I have done some more investigation. It turns out, when `-hogdir` is used as an option, it replaces `/usr/share/d1x-rebirth` (compiled for Arch), in the `PHYSFS` search path. The Arch AUR package puts https://www.dxx-rebirth.com/download/dxx/res/d1xr-sc55-music.dxa into `/usr/share/d1x-rebirth`, so without the `-hogdir`, that's what it is using for music.

I verified this by making that .dxa file unreadable, and consequently no music is playing. So I think my ultimate problem is the same as issue #430, in that I can't get MIDI files playing. I don't care too much whether the music is MIDI or OGG, but I would rather keep my official Descent files separate from the D1X-Rebirth files. So maybe either `-hogdir` shouldn't remove `/usr/share/d1x-rebirth` from the search path, or perhaps a new option `+hogdir` would add it without removing the share path.

**Comment by vLKp** [comment]
`-hogdir` is specifically to set the shared data directory, overriding the built-in default path.  The write directory (`~/.d1x-rebirth`) is also added to the search path automatically.  Do I understand correctly that you want _three_ directories searched?

- Shared hog directory managed by the distribution
- Write directory `~/.d1x-rebirth`
- and another directory of your choosing

Your original Descent files should be installed by the package manager in the shared directory path.  Your pilot files will go in the write directory.  Could you explain why putting custom music also in the write directory is a problem?

**Comment by arkdae** [comment]
`-hogdir` is not set to the shared data directory. They are independent

    if (!CGameArg.SysHogDir.empty())
    {
        const auto p = CGameArg.SysHogDir.c_str();
        con_printf(CON_DEBUG, "PHYSFS: append argument hog directory \"%s\" to search path", p);
        PHYSFS_mount(p, nullptr, 1);
    }
    #if DXX_USE_SHAREPATH
    else if (!GameArg.SysNoHogDir)
    {
        con_puts(CON_DEBUG, "PHYSFS: append sharepath directory \"" DXX_SHAREPATH "\" to search path");
        PHYSFS_mount(DXX_SHAREPATH, nullptr, 1);
    }

How could a Linux package manager install the files of a proprietary game? Where would it get those? Are there package managers to which you provide additional details? Arch's pacman just installs software. No questions asked, so there's no way for it to know where to get those files.

I think three directories is reasonable.

   1. `~/.d1x-rebirth` for save games and personal configuration.
   2. `/usr/share/d1x-rebirth` for the high-res D1X-Rebirth files and music, automatically updated by the package manager (not that there may ever be any further updates, but making full use of the package manager where it is available is my preference).
   3. Wherever `-hogdir` points for the base game or any one of the thousands of user created levels. Separate and not maintained by the package manager.

Ultimately I could just copy the files out of /usr/share/d1x-rebirth, but this just seems to be a logical structuring to me.

**Comment by arkdae** [comment]
[diff.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/8237924/diff.txt)

Here is a patch which adds a +hogdir option.

**Comment by vLKp** [comment]
Please use github blob links when showing code.  That will preserve line numbers and enable syntax highlighting.  For the bit you quoted, which I reviewed locally before making my prior comment, you would use:

https://github.com/dxx-rebirth/dxx-rebirth/blob/21aae1a352c8a3db10c6a71725bd3a8f3c1c97d1/similar/misc/physfsx.cpp#L214-L225

I said `-hogdir` is _to set the shared data directory_, not that it is set to that value.  If it is set, then the game uses it in place of the built-in sharepath.  If it is unset, then the built-in sharepath is used.

> How could a Linux package manager install the files of a proprietary game? Where would it get those?

From a directory provisioned by `root`.  Gentoo has several ebuilds for fetch-restricted proprietary packages.  The user obtains those files out of band, from a physical CD or by purchasing them from a digital download store.  The user places those files in a directory the package manager is documented to search.  Then the package manager picks them up and puts them in the right place with reasonable permissions.  The extra complexity has two benefits.  First, the Gentoo ebuild can validate that the files are laid out reasonably - appropriate capitalization, spelling, etc.  Second, it allows the package manager to clearly enforce that installing the open source game without installing the proprietary data files is not a useful thing to do.  Without this, a user might install Rebirth, then wonder why the installed game doesn't work.

> I think three directories is reasonable.

I think if we need more than the current, it would be better to follow the [Zero one infinity rule](https://en.wikipedia.org/wiki/Zero_one_infinity_rule).  In this case, that would mean changing the semantics of `-hogdir`, or adding a sibling option, which can be repeated as needed to add as many directories as the user cares to request.

Typically, user levels are put in the `missions/` subdirectory under the user's personal area.

> Here is a patch which adds a +hogdir option.

By convention, all existing options use a single leading dash, and then the word.  There are no options which start with `+`.

**Comment by vLKp** [comment]
To get back to the original report:

	Music descent.hmp could not be loaded: Module format not recognized

This message comes from:

https://github.com/dxx-rebirth/dxx-rebirth/blob/21aae1a352c8a3db10c6a71725bd3a8f3c1c97d1/common/arch/sdl/digi_mixer_music.cpp#L218-L220

I pushed some changes to this area, with the hope of improving the error message when that path fails.

---

The ticket title asserts that music fails to play when using `-hogdir`.  The opening comment describes that MIDI music does not work.  Later the comments seem to indicate that MIDI music works when the MIDI data files are in the default sharepath.  Is that correct?  Exactly which files need to be in the default sharepath directory in order for this to work for you?

**Comment by vLKp** [comment]
No response from original reporter.  Not reproducible with the information provided.  Closing.  If this is still a problem, please reopen and answer the questions above.
