### ISSUE TITLE
Build failure: similar/main/automap.cpp:373:30: cannot convert ‘const d2x::player_marker_index’ to ‘d2x::game_marker_index’

### ISSUE THREAD

**Issue by dbermond** [dxx-rebirth/dxx-rebirth#638]
### Environment

git commit: a8e7f6ad597d5036adb738a784dc15f50266dab6

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

I'm getting the following build error with dxx-rebirth git master when building d2x:

```
similar/main/automap.cpp: In function ‘d2x::game_marker_index d2x::convert_player_marker_index_to_game_marker_index(dcx::game_mode_flags, unsigned int, unsigned int, player_marker_index)’:
similar/main/automap.cpp:373:30: error: cannot convert ‘const d2x::player_marker_index’ to ‘d2x::game_marker_index’ in initialization
  373 |     return game_marker_index{player_marker_num};
      |                              ^~~~~~~~~~~~~~~~~
      |                              |
      |                              const d2x::player_marker_index
```

#### Regression status

No info (never tried with sdl2 before).

### Steps to Reproduce

- command: `scons -j7 -Cdxx-rebirth lto=1 builddir=./build prefix=/usr opengl=yes sdl2=yes sdlmixer=yes ipv6=yes use_udp=yes use_tracker=yes screenshot=png verbosebuild=1 d1x=0 d2x=1 sharepath=/usr/share/d2x-rebirth`
- [Scons full output](https://paste.ee/p/ezfZd) ([also attached](https://github.com/dxx-rebirth/dxx-rebirth/files/8788427/scons-full-output.txt)).
- [sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/8788550/sconf.log)
- [dxxsconf.h.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/8788555/dxxsconf.h.txt)

### Other
- scons: 4.3.0
- compiler: gcc 12.1.0
- sdl2: 2.0.22
- sdl2_image: 2.0.5
- sdl2_mixer: 2.0.4

### Note
It builds d1x fine with the same command (by switching `d1x=0 d2x=1` to `d1x=1 d2x=0`).

**Comment by vLKp** [comment]
The above commit fixes this for me in gcc-12.  However, I still see several other build errors, including one caused by [gcc bug 104165](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104165).

```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/bits/stl_algo.h:1849:28: error: array subscript 16 is outside array bounds of 'dcx::sort_child_array_t [1
]' {aka 'std::array<dcx::sidenum_t, 6> [1]'} [-Werror=array-bounds]
 1849 |       std::__insertion_sort(__first, __first + int(_S_threshold), __comp);
      |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Please sync and retest.  If the problem persists for you, please reopen.

**Comment by dbermond** [comment]
Thank you for fixing this!

I also continue to get build error with gcc 12.1.0:

```
In function ‘unchecked_partial_range_advance’,
    inlined from ‘unchecked_partial_range’ at common/include/partial_range.h:371:88,
    inlined from ‘partial_range’ at common/include/partial_range.h:473:48,
    inlined from ‘partial_range’ at common/include/partial_range.h:489:88,
    inlined from ‘partial_const_range’ at common/include/partial_range.h:512:78,
    inlined from ‘piggy_find_bitmap’ at similar/main/piggy.cpp:403:2:
common/include/partial_range.h:319:9: error: call to ‘partial_range_is_always_empty’ declared with attribute error: offset never less than length
  319 |         DXX_ALWAYS_ERROR_FUNCTION(partial_range_is_always_empty, "offset never less than length");
      |         ^
```

Switched to clang (version 13.0.1) and it builds fine both d1x and d2x.

**Comment by vLKp** [comment]
I do not get that error when using gcc-12.1.1 snapshot 20220514 here.  Looking at the usage, I think the diagnostic is incorrect.  `Num_aliases` is a global, so its exact value is hard for the compiler to predict.  The call is the two-argument form, so the offset is always `0` and `Num_aliases` is the length; since `Num_aliases` is `unsigned`, the compiler must have decided that `Num_aliases` is always 0.  I don't think the compiler can actually prove that here though, so it must be warning about a path that might exist, rather than one that provably does exist.  The failure is strange though, because a configure test ought to catch when the compiler gets confused by conditional paths and disable the compile-time test.  You can force the `compiler_always_error_optimizer` test result to disable this compile-time check.  In this case, the diagnostic is meant to catch a range that is always empty because such is likely to be a bug.  Since the range is not actually always empty, suppressing the diagnostic should be safe.

**Comment by dbermond** [comment]
Thank you for the investigation. Let's see if gcc 12.2.0 will exhibit this error when it's released.
