### ISSUE TITLE
Sometimes I get screen stuttering (stuttering).

### ISSUE THREAD

**Issue by wanisea** [dxx-rebirth/dxx-rebirth#659]
Sometimes I get screen stuttering (stuttering).

I am a high-end user, and I play the game with the maximum processor in the power option assigned to 50%.
The display refresh rate is 144hz, so 144fps is fine.
Occasionally, the screen freezes. (screen stuttering)
Dropped frames are normal and this happens intermittently, not periodically.
Of course, if you set the power options to Balanced or High Performance, there is no problem, but it is a bit of a concern.
Sorry to bother you, but I'd like to ask you to test.
I'm using Google Translate, so please understand.

The system specifications are
i7-10700k / 16G RAM / GTX1060 6G

**Comment by vLKp** [comment]
I do not see a problem like this.  Game play is consistently smooth for me.  Balanced and High Performance modes allow the processor to run at its full capability.  If you force the processor to run slow, the game may not get sufficient CPU time.  Do other games work normally when you limit processor power to 50%?

**Comment by wanisea** [comment]
> 나는 이런 문제를 보지 않는다. 게임 플레이는 일관되게 매끄럽습니다. 균형 및 고성능 모드를 사용하면 프로세서를 최대 성능으로 실행할 수 있습니다. 프로세서를 강제로 느리게 실행하면 게임이 충분한 CPU 시간을 얻지 못할 수 있습니다. 프로세서 전력을 50%로 제한하면 다른 게임이 정상적으로 작동합니까?

Yes. Other low-end games work fine. (Doom 1/2, etc.)
I can't figure out what the problem is.
At 50%, the CPU is 1.9Ghz, which covers all low-spec games.
Sorry for the inconvenience.

**Comment by wanisea** [comment]
You seem to have found the cause.
I checked the task manager and saw that the Logitech option's peak CPU usage went up to 9%.
When I removed the Logitech option, the frame was maintained normally.
Sorry for mistaking it for a bug.

**Comment by vLKp** [comment]
Based on these comments, I believe this was not a game bug, but a user system issue.  Therefore, I am closing this ticket.  If this is incorrect, please reopen.
