### ISSUE TITLE
Thief Bot Dying in the Level

### ISSUE THREAD

**Issue by Glumduk** [dxx-rebirth/dxx-rebirth#665]
I'm on the most current commit of D2X Rebirth (e3faab0) & Thief Bot removal is off. 
I think enemy robots are friendly firing on the Thief. This is easiest for me to replicate in Vertigo level 10 - I followed the Thief around until it ran into some Diamond Claws, where it died pretty much instantly. I don't think this is intended behavior & I only noticed Thief being absent in levels when I started using Commit 366b048

Let me know if I can provide any more helpful info. I'm not savvy with code

**Comment by vLKp** [comment]
Yes, that would be wrong behavior.  Are the Diamond Claws actively attacking the thief (and making their scratch sound), or does it explode as a side effect of trying to fly past them?  Are any other robots firing on the thief?

**Comment by Glumduk** [comment]
No attack sound - it looks like the Thief is dying as it tries to move through the Diamond Claws & other robots (and the robots 'look' at Thief when it rams them). I've tried about a dozen resets & haven't seen other robots directly shoot at it, but it does seem to get hit incidentally. The higher the difficulty, the faster it dies. 
I've found Counterstrike level 6 to be another easy level for observations. Down the well, first door to the right - even If I make no inputs at all, I can see the explosion through the walls.

**Comment by vLKp** [comment]
Confirmed.  I built 0.57.3-d2x and started Descent 2: Counterstrike level 6 ("The Well").  The thief bot showed up in short order, and a breakpoint on `apply_damage_to_robot` triggered only when a different robot fired a missile, resulting in this call stack:

```
#0  0x0000555555588870 in apply_damage_to_robot ()
#1  0x0000555555597287 in object_create_explosion_sub ()
#2  0x0000555555596cc3 in explode_badass_weapon ()
#3  0x0000555555587a53 in collide_weapon_and_wall ()
#4  0x00005555555ffd08 in do_physics_sim ()
#5  0x00005555555fc758 in object_move_one ()
#6  0x00005555555fd376 in object_move_all ()
```

In comparison, using current code, a breakpoint on `d2x::apply_damage_to_robot` triggered almost immediately, and resulted in this call stack:

```
#0  d2x::apply_damage_to_robot (Robot_info=..., robot=..., damage=751035, killer_objnum=57) at similar/main/collide.cpp:1436
#1  0x00005555555ba057 in d2x::(anonymous namespace)::apply_force_damage (Robot_info=..., obj=..., force=..., other_obj=..., other_obj=...) at similar/main/collide.cpp:240
#2  0x00005555555ba2e0 in d2x::(anonymous namespace)::bump_this_object (Robot_info=..., objp=..., force=..., damage_flag=1, other_objp=..., other_objp=...) at similar/main/collide.cpp:320
#3  0x00005555555ba4e3 in d2x::(anonymous namespace)::bump_two_objects (Robot_info=..., obj0=..., obj1=..., damage_flag=1) at similar/main/collide.cpp:348
#4  0x000055555563d535 in d2x::do_physics_sim (Robot_info=..., obj=..., obj_previous_position=..., phys_segs=phys_segs@entry=0x0) at similar/main/physics.cpp:682
#5  0x000055555563b106 in d2x::(anonymous namespace)::object_move_one (LevelSharedRobotInfoState=..., obj=..., Controls=...) at similar/main/object.cpp:1935
#6  0x000055555563b86b in d2x::(anonymous namespace)::object_move_all (LevelSharedRobotInfoState=...) at similar/main/object.cpp:2097
```

From this, I believe that in current code, the thief bot can collide with other robots, and this collision deals damage.  After enough collisions, the accumulated damage destroys the thief bot.  The diamond claws need not actively attack it.  Their mere presence on a path it wishes to fly is sufficient.  In the historical code, the thief bot appears to pass through robots without colliding with them, and therefore does not take damage.

---

`git bisect` implicates 37132ab88746267eb020d86341c75cc4314ca6ad as the first bad commit, and inspection shows a likely culprit.  An attempt to simplify the rules changed the behavior of robot-vs-robot collisions.  Prior to that change, in Descent 2, robots never collided with other robots.  After that change, they could.  Reversing the attempted simplification allows the thief bot to survive the test case.

Please sync and retest.  Reopen if you still see problems.
