### ISSUE TITLE
Build failure: Apple clang doesn't support std::ranges::find

### ISSUE THREAD

**Issue by Kreeblah** [dxx-rebirth/dxx-rebirth#667]
### Environment

macOS 12.6 (ARM)
Apple clang 14.0.0
Commit https://github.com/dxx-rebirth/dxx-rebirth/commit/e385ff1c3bc82f01180f50174b915069bae33118

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [x] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [ ] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [x] ARM64 (64-bit; sometimes called AArch64)

### Description

It seems Apple clang doesn't pass the new `std::ranges` test.  Compiling the above-mentioned commit or later results in:

```
DXX-Archive.3: checking whether C++ compiler provides std::ranges by default...no
DXX-Archive.3: checking whether C++ compiler provides std::ranges with -D_LIBCPP_ENABLE_EXPERIMENTAL...no
scons: *** C++ compiler does not support std::ranges.  See build/sconf.log for details.  Stop.
```

Here's the relevant bit from `sconf.log`:

```
g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -funsigned-char -std=gnu++20 -Werror=unused -Werror -Wno-sign-compare -D__unix__ -DGL_SILENCE_DEPRECATION -DPHYSFS_DEPRECATED= -D_LIBCPP_ENABLE_EXPERIMENTAL -Icommon/include -Icommon/main -I. -Ibuild -I/opt/homebrew/Cellar/libpng/1.6.38/include/libpng16 -I/opt/homebrew/Cellar/physfs/3.0.2/include -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -I/opt/homebrew/Cellar/jpeg-turbo/2.1.4/include -I/opt/homebrew/Cellar/libtiff/4.4.0_1/include -I/opt/homebrew/Cellar/webp/1.2.4/include -I/opt/homebrew/Cellar/libmodplug/0.8.9.0/include -I/opt/homebrew/Cellar/mpg123/1.30.2/include build/.sconf_temp/conftest_35d3868d99cc1a88d800a01ffca55d52_1.cpp -o build/.sconf_temp/conftest_35d3868d99cc1a88d800a01ffca55d52_1_c3d0fa27c699ddae505526075b58e2a1.o
build/.sconf_temp/conftest_35d3868d99cc1a88d800a01ffca55d52_1.cpp:52:22: error: no member named 'find' in namespace 'std::ranges'
    return std::ranges::find(a, argc) == a;
           ~~~~~~~~~~~~~^
1 error generated.
scons: Configure: no
```

#### Regression status

https://github.com/dxx-rebirth/dxx-rebirth/commit/e385ff1c3bc82f01180f50174b915069bae33118
[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/9750389/sconf.log)

### Steps to Reproduce

`$ scons macos_add_frameworks=False macos_bundle_libs=True sdl2=True macos_code_signing_identity="MyCodeSigningIdentity" macos_notarization_keychain_item="MyNotarizationKeychainItem"`

**Comment by vLKp** [comment]
Apple clang is becoming a problem.  I find it strange that x86_64-pc-linux-gnu-clang with the clang standard library has no problem with these C++20 constructs, but Apple clang cannot handle them.  I would have expected, given Apple's involvement with clang, that they would do a better job of tracking upstream clang's C++20 support.

---

Unfortunately, the configure test is not written to provide enough output for me to diagnose this using only the attached `sconf.log`.  My guess is that Apple's C++ standard library is simply missing this functionality entirely, but I am hopeful that it is merely the same problem I hit on Linux: that the required functionality is gated behind a preprocessor symbol which, if set, will expose enough of an implementation that this will work.  On Linux, that symbol is `_LIBCPP_ENABLE_EXPERIMENTAL`, and I already have SConf set that as part of the test.  If Apple's C++ standard library used a different symbol, then setting that symbol might suffice.  I do not know under what path your standard library headers will be installed, so I cannot give you exact commands to collect the information I need.  However, it appears you can find `algorithm` by running:
```
$ clang -H -E -o /dev/null -x c++ - <<<'#include <algorithm>' 2>&1 | grep -e '/algorithm' -e /__algorithm/find
. /usr/include/c++/v1/algorithm
.. /usr/include/c++/v1/__algorithm/find.h
.. /usr/include/c++/v1/__algorithm/find_end.h
.. /usr/include/c++/v1/__algorithm/find_first_of.h
.. /usr/include/c++/v1/__algorithm/find_if.h
.. /usr/include/c++/v1/__algorithm/find_if_not.h
```

By extension, omitting that `grep` will show you the full list of supporting headers that `algorithm` includes.  For me, that is more than 600 lines long.

- What is the output of `grep -C4 ranges::find /usr/include/c++/v1/algorithm` (or such other path as appropriate to your copy of the C++ standard header `algorithm`)?
- If there exists a directory `__algorithm` in the directory that holds `algorithm`, is there a file `ranges_find.h` there?  If yes, what is its content?  For me, this is quite short:

```
$ stat -c '%s %n' /usr/include/c++/v1/algorithm /usr/include/c++/v1/__algorithm/ranges_find.h 
99026 /usr/include/c++/v1/algorithm
2348 /usr/include/c++/v1/__algorithm/ranges_find.h
```

`/usr/include/c++/v1/__algorithm/ranges_find.h`:
```c++
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef _LIBCPP___ALGORITHM_RANGES_FIND_H
#define _LIBCPP___ALGORITHM_RANGES_FIND_H

#include <__algorithm/ranges_find_if.h>
#include <__config>
#include <__functional/identity.h>
#include <__functional/invoke.h>
#include <__functional/ranges_operations.h>
#include <__iterator/concepts.h>
#include <__iterator/projected.h>
#include <__ranges/access.h>
#include <__ranges/concepts.h>
#include <__ranges/dangling.h>
#include <__utility/forward.h>
#include <__utility/move.h>

#if !defined(_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER)
#  pragma GCC system_header
#endif

#if _LIBCPP_STD_VER > 17 && !defined(_LIBCPP_HAS_NO_INCOMPLETE_RANGES)

_LIBCPP_BEGIN_NAMESPACE_STD

namespace ranges {
namespace __find {
struct __fn {
  template <input_iterator _Ip, sentinel_for<_Ip> _Sp, class _Tp, class _Proj = identity>
    requires indirect_binary_predicate<ranges::equal_to, projected<_Ip, _Proj>, const _Tp*>
  _LIBCPP_HIDE_FROM_ABI constexpr
  _Ip operator()(_Ip __first, _Sp __last, const _Tp& __value, _Proj __proj = {}) const {
    auto __pred = [&](auto&& __e) { return std::forward<decltype(__e)>(__e) == __value; };
    return ranges::__find_if_impl(std::move(__first), std::move(__last), __pred, __proj);
  }

  template <input_range _Rp, class _Tp, class _Proj = identity>
    requires indirect_binary_predicate<ranges::equal_to, projected<iterator_t<_Rp>, _Proj>, const _Tp*>
  _LIBCPP_HIDE_FROM_ABI constexpr
  borrowed_iterator_t<_Rp> operator()(_Rp&& __r, const _Tp& __value, _Proj __proj = {}) const {
    auto __pred = [&](auto&& __e) { return std::forward<decltype(__e)>(__e) == __value; };
    return ranges::__find_if_impl(ranges::begin(__r), ranges::end(__r), __pred, __proj);
  }
};
} // namespace __find

inline namespace __cpo {
  inline constexpr auto find = __find::__fn{};
} // namespace __cpo
} // namespace ranges

_LIBCPP_END_NAMESPACE_STD

#endif // _LIBCPP_STD_VER > 17 && !defined(_LIBCPP_HAS_NO_INCOMPLETE_RANGES)

#endif // _LIBCPP___ALGORITHM_RANGES_FIND_H
```

The key part is that `_LIBCPP_HAS_NO_INCOMPLETE_RANGES`, which for me is handled as a consequence of `_LIBCPP_ENABLE_EXPERIMENTAL`:

`/usr/include/c++/v1/__config` (excerpt):
```c++
// Incomplete features get their own specific disabling flags. This makes it
// easier to grep for target specific flags once the feature is complete.
#  if !defined(_LIBCPP_ENABLE_EXPERIMENTAL) && !defined(_LIBCPP_BUILDING_LIBRARY)
#    define _LIBCPP_HAS_NO_INCOMPLETE_FORMAT
#    define _LIBCPP_HAS_NO_INCOMPLETE_RANGES
#  endif
```

If you have something similar, I can change SConf to set that symbol as well.  If the Apple clang standard library is missing this entirely, then a more invasive solution will be needed.

**Comment by Kreeblah** [comment]
The header location is essentially a virtual directory located within the Xcode app bundle.  So, in my case, it's:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`

`grep -C4 ranges::find /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm` returns no matches, and `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__algorithm/ranges_find.h` doesn't exist.

Looking for anything range-related in `__config` just has this:

```
#if _LIBCPP_STD_VER <= 17 || defined(_LIBCPP_HAS_NO_CONCEPTS)
#define _LIBCPP_HAS_NO_RANGES
#endif
```

I suspect it might be a versioning difference, if you have clang 15.  Apple's currently shipping clang 14, and https://libcxx.llvm.org/Status/Ranges.html seems to indicate that a lot of the C++20 ranges features (P0896R4 in particular) weren't actually completed until clang 15, which was just released a few weeks ago.

Unfortunately, if I had to guess, I don't think Apple's going to be shipping clang 15 for a few months.  They typically lag a bit behind clang's releases (they just started shipping clang 14 last month, for example, as opposed to the clang team's release of 14 back in March, which followed Apple shipping clang 13 in March, when the clang team had released 13 the previous October).

**Comment by vLKp** [comment]
I test using clang-14.x, but I have libcxx-15, so for this purpose, yes, the version on Linux seems to be one release newer than the one Apple is using.

I had not realized that clang's support for this was so new.  I tested the build in C++20 mode and assumed that since it worked (albeit with the experimental flag), that it had been working for a while.  clang's standard library is not slotted on Linux, so I can only keep one version at a time.  Perhaps I should pin on a somewhat old version of clang's standard library so that I do not introduce any other dependencies on things that Apple will not be shipping yet.

Apple being months behind is unfortunate.  I don't want to leave Rebirth broken on OSX for so long, but I don't see a way to fix this without either reverting that commit or adding some ugly hacks.  I will see what I can do here.  At least I can readily break it locally by removing that preprocessor symbol.

**Comment by vLKp** [comment]
[Fix OS X clang build](/dxx-rebirth/dxx-rebirth/commit/3d5de92058296f4b6bbc7986b29a3518354522ea) should resolve this.  I can build using clang-14 and its libc++ on x86_64-pc-linux-gnu with that commit.  Please sync and test.

**Comment by Kreeblah** [comment]
Hmmm.  I tried checking out that exact revision, but it still seems to be failing, though this time it's failing on finding `std::ranges::range`, which might also need to be added to that `backports-ranges.h` header.  Below is my `sconf.log` from the build, but here's the relevant part:

```
g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -funsigned-char -std=gnu++20 -Werror=unused -Werror -Wno-sign-compare -D__unix__ -DGL_SILENCE_DEPRECATION -DPHYSFS_DEPRECATED= -D_LIBCPP_ENABLE_EXPERIMENTAL -Icommon/include -Icommon/main -I. -Ibuild -I/opt/homebrew/Cellar/libpng/1.6.38/include/libpng16 -I/opt/homebrew/Cellar/physfs/3.0.2/include -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -I/opt/homebrew/Cellar/jpeg-turbo/2.1.4/include -I/opt/homebrew/Cellar/libtiff/4.4.0_1/include -I/opt/homebrew/Cellar/webp/1.2.4/include -I/opt/homebrew/Cellar/libmodplug/0.8.9.0/include -I/opt/homebrew/Cellar/mpg123/1.31.1/include build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1.cpp -o build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1_2a20d289cc8bfb39ee0a58d8e4e69edb.o
build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1.cpp:52:29: error: 'R' does not refer to a value
requires(std::ranges::range<R>)
                            ^
build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1.cpp:51:20: note: declared here
template <typename R>
                   ^
build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1.cpp:52:23: error: no member named 'range' in namespace 'std::ranges'
requires(std::ranges::range<R>)
         ~~~~~~~~~~~~~^
build/.sconf_temp/conftest_cfec7f24938b59c2755ab4d0c5de1d6b_1.cpp:52:31: error: expected expression
requires(std::ranges::range<R>)
                              ^
3 errors generated.
scons: Configure: no
```

Also, since Xcode 14.1 came out a couple days ago, I did upgrade to that, but it still only includes clang 14 (just with a slightly newer build number than Xcode 14 did).

[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/9935863/sconf.log)

**Comment by MaddTheSane** [comment]
Try using `scons sconf_have_std_ranges=force-success`. That got it working for me.

**Comment by vLKp** [comment]
That is strange.  I omitted `std::ranges::range` from the backports header because, in my testing on x86_64-pc-linux-gnu with clang libcxx-14.0.6, the test succeeds as committed.  I can remove that from the test; none of the Rebirth code directly `requires(std::ranges::range<T>)` for any T yet, though I had planned to add some code that would.  Likewise for std::ranges::borrowed_range.  When I build the test program in pre-process only mode, even without `_LIBCPP_ENABLE_EXPERIMENTAL`, I get a definition for `range` and `borrrowed_range`:

```
# 31 "/usr/include/c++/v1/__ranges/concepts.h" 3


namespace std { inline namespace __1 {



namespace ranges {



  template <class _Tp>
  concept range = requires(_Tp& __t) {
```

These are guarded behind `!defined(_LIBCPP_HAS_NO_CONCEPTS)`, but I am not specifically defining anything to influence whether that is defined.  I wonder why Apple clang does not see this.  Is it using an even older libcxx?

**Comment by Kreeblah** [comment]
Hmmm.  Looks like `concepts.h` on Apple's shipped version of libcxx gates it behind `!defined(_LIBCPP_HAS_NO_RANGES)`, but it does have a definition in there:

```
#if !defined(_LIBCPP_HAS_NO_RANGES)

namespace ranges {
  // [range.range]
  template <class _Tp>
  concept range = requires(_Tp& __t) {
    ranges::begin(__t); // sometimes equality-preserving
    ranges::end(__t);
  };
```

So, I think you're right about this being an even older version of libcxx.  I can't find any documentation anywhere on what libcxx version Apple ships (just the clang version), so I had to do some looking, and that snipped you posted there was helpful in that.  Specifically because it turns out that https://github.com/llvm/llvm-project/commit/2eb2ff2a02a30cf3466ab487fa5a1b2abefadcc2 was committed to the LLVM tree back in January to change `_LIBCPP_HAS_NO_RANGES` to `_LIBCPP_HAS_NO_CONCEPTS` in that location.

So, using that as a basis, I looked through the source of released libcxx versions (at least according to the LLVM GitHub project).  13.0.1 is the last released version I can find that uses `_LIBCPP_HAS_NO_RANGES` in that spot, whereas 14.0.0 has it replaced with `_LIBCPP_HAS_NO_CONCEPTS`.  So, I strongly suspect that Apple is still shipping libcxx 13, even though they're shipping clang 14.

**Comment by vLKp** [comment]
[Backport more ranges support for OS X clang](/dxx-rebirth/dxx-rebirth/commit/962a37e75e5d2168f286ef017ab4dc9e2ab3b0f4) changes the configure test to use stub concepts in `backports-ranges.h`.  This builds for me with clang-14 and libcxx-14.  I cannot readily test whether it works with libcxx-13, since I cannot have libcxx-13 and libcxx-14 installed at the same time.

Please sync, test, and report whether this works for you without needing the sconf override.

**Comment by Kreeblah** [comment]
With those further stubs added to the backports header, both D1X and D2X do build and run for me without the sconf override.

**Comment by vLKp** [comment]
Good.  In that case, I think this is resolved.  Please reopen if you disagree.

I will try to be careful in my planned `std::ranges` work to avoid breaking this again.
