### ISSUE TITLE
Runtime bug: 

### ISSUE THREAD

**Issue by 1da1a172** [dxx-rebirth/dxx-rebirth#668]
### Environment

Installed with the AUR PKGBUILD:
- d1x-rebirth-git-0.60.0.beta2.r2216.g2dd538eb4-1
- d2x-rebirth-git-0.60.0.beta2.r2216.g2dd538eb4-1

#### Operating System Environment

Arch Linux, updated on 2022-10-25.
Other environments were not tested.

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Impacts Descent and Descent 2.

### Description

When saving a game, the up/down arrow keys do not change the save slot selection

#### Regression status
This was _not_ a problem in dxx-rebirth-git-0.60.0.beta2.r2046.g366b04887-1.
I've not tested anything in between.

### Steps to Reproduce

- Start playing a game. Descent, Descent 2, new game, or saved game does not matter.
- Press `Esc` to pull up the menu
- Press `s` to select "Save Game"
- Press `Return` to go to the save game menu
- Try to select a different slot with the arrow keys or `tab`

Expected behavior:
- Save slot selection changes

Actual behavior:
- The first slot stays selected. Notably, it seems it can be used.

* Engines affected:
  * [ ] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
Confirmed.  First bad commit: 0269bc82dbb33d4edb232a13fb7bd0b2e9823ee0.

Affected versions also have an assertion failure:
```
d2x-rebirth: similar/main/newmenu.cpp:698: void {anonymous}::newmenu_scroll(dcx::newmenu*, int): Assertion `first != rlast' failed.
```

**Comment by vLKp** [comment]
I believe 7981fd1b1732f51ac8f7863f7797cfb5df2a1d08 will resolve this.  Please sync and retest.  Reopen if you still see problems.
