### ISSUE TITLE
Build failure: 

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#674]
#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [X] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

I am currently having the issue building on Windows 10, commit [7fc6879](https://github.com/dxx-rebirth/dxx-rebirth/commit/7fc68795559dc4b116b3dc7faad7a9e26e8dce15).
It seems that DXX_USE_STEREOSCOPIC_RENDERER is not defined at all when compiling on Windows (using MinGW64)
`In file included from common/2d/canvas.cpp:26:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/bitmap.cpp:34:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/gpixel.cpp:23:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/bitblt.cpp:35:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/rect.cpp:29:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/line.cpp:33:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/2d/pixel.cpp:29:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/3d/setup.cpp:22:
common/include/ogl_init.h:69:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   69 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
CXX dxx build/ common/arch/ogl/ogl_sync.cpp
In file included from common/arch/ogl/ogl_sync.cpp:16:
common/include/args.h:103:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
  103 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
CXX dxx build/ common/arch/sdl/digi_mixer_music.cpp
CXX dxx build/ common/arch/sdl/event.cpp
cc1plus.exe: some warnings being treated as errors
scons: *** [build/common/2d/canvas.o] Error 1
In file included from common/arch/sdl/digi_mixer_music.cpp:21:
common/include/args.h:103:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
  103 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from common/main/game.h:28,
                 from common/arch/ogl/ogl_sync.cpp:19:
common/main/fwd-game.h:95:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
   95 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: some warnings being treated as errors
common/main/game.h:141:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
  141 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build/common/2d/gpixel.o] Error 1
In file included from common/arch/sdl/event.cpp:27:
common/include/args.h:103:5: error: "DXX_USE_STEREOSCOPIC_RENDER" is not defined, evaluates to 0 [-Werror=undef]
  103 | #if DXX_USE_STEREOSCOPIC_RENDER
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
`

Even weirder, if I try to specify use_stereo_renderer=no or yes, scons reports:
*** Unknown values specified on command line.
        use_stereo_renderer
So, the issue seems to be on Scons-level already.

**Comment by vLKp** [comment]
The option is spelled `use_stereo_render`, not `use_stereo_renderer`:

https://github.com/dxx-rebirth/dxx-rebirth/blob/7fc68795559dc4b116b3dc7faad7a9e26e8dce15/SConstruct#L3854

---

Cross-compiling for Windows64 using gcc-10 works for me with commit 7fc68795559dc4b116b3dc7faad7a9e26e8dce15, and I see the expected define inserted in the generated `dxxsconf.h`.  Please attach your `sconf.log` and generated `dxxsconf.h`.

**Comment by vLKp** [comment]
The Windows/i686 and Windows/x86_64 builds seem to work here with gcc-10 and the latest code.  No response from reporter.  Closing.  Please reopen if you still see problems.
