### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [dxx-rebirth/dxx-rebirth#680]
Would love to see a flatpak of this to make getting it running on the steamdeck easier!

**Comment by vLKp** [comment]
I have no plans to create a flatpak of Rebirth.  If you wish to do so, please link to it so that others can find your work.

**Comment by vLKp** [comment]
No response from original poster (and the poster seems to have posted identical requests across a number of Github projects).  I have no plans to work on this.  No other maintainers are presently active.  Closing.  Please reopen if you wish to work on this.

- https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1700
- https://github.com/tonihele/OpenKeeper/issues/423
- https://github.com/omf2097/openomf/issues/462
- https://github.com/alariq/mc2/issues/16
- https://github.com/dethrace-labs/dethrace/issues/239
