### ISSUE TITLE
Homers (again)

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#70]
Homers are too easy. Please recheck how Retro did it, because the Rebirth homers are slightly easier than the Retro ones (and everyone agrees that the Retro homers are correct.)

**Comment by zicodxx** [comment]
That can only be related to the tracking and discovers dots. Those were really kinda messed in Descent 2 where the discovers dot was smaller than tracking. I made this to Descent 1 style. Other than that, the code does not really differ except that Rebirth homers are locked to 30 FPS while Retro locks to 25.

**Comment by Mako88** [comment]
Alright! We have a definitive solution!

#define HOMING_TURN_TIME                (F1_0/45)

Boom. lol. This was tested and works great.

**Comment by zicodxx** [comment]
This greatly differs from the turning time specified by Retro (almost double). I have to check that code to find out why that is.

**Comment by zicodxx** [comment]
Please check out 6eb724d. I reworked the tick count for the individual homers (not basing them on the global one) and isolated a bit more of the turning code into a timed condition.

**Comment by Mako88** [comment]
Do you mean 7ba3d1317bad709d0771e9307c810859c8e00370? lol

**Comment by zicodxx** [comment]
Uh... I do. Did I make a mistake? ;)

**Comment by Mako88** [comment]
They still seem a bit too easy. Should I try fiddling with the turn time again?

**Comment by zicodxx** [comment]
No need to. I'm still looking at the codes of Retro, Rebirth and the original sources and I notice a few differences between them all which I am not going to investigate. I'm also planning on simplifying the time-counters further (having one in each missile seems the right idea but also slightly overkill in hindsight).

**Comment by Mako88** [comment]
I plan on testing this tomorrow with the FPS set to 30. I'm assuming that's going to be right, and if it is, I say that we go with it.

**Comment by Mako88** [comment]
Good news zico!! With the FPS set to 30 (#define HOMING_TURN_TIME (F1_0/30)) the homers work perfectly! I say you change that and we call this issue closed :)

**Comment by zicodxx** [comment]
Okay, I changed the turn time accordingly in 2bfe21183e25d441c02e464e2577e9c75860d951. Thanks for all the testing.

**Comment by Mako88** [comment]
Though the homers seemed to work perfectly in the tests me and Entropy performed, now that several old-time players have tested the latest beta, they've shown me that the homers are still too easy. The general consensus currently is that Retro homers are a tad too hard, while Rebirth homers are still too easy.

Comparing Rebirth to Retro currently: when a player dodges a homer in Rebirth, the missile turns very little after it has passed the ship (a max of 45 degrees...sometimes it isn't even noticable that it turned). In Retro a homer will turn up to 90 degrees behind the ship. (So if the player was facing east, then dodges a homer coming straight-on, the homer will turn so that it hits a wall either due north, or due south...if that makes sense).

I've asked Kp to look through the homer code when he gets a chance, since I know you've already done it two or three times zico. Maybe he'll catch something you and I missed.
