### ISSUE TITLE
unable to rename guide bot keystroke conflict. 

### ISSUE THREAD

**Issue by LordKane1701** [dxx-rebirth/dxx-rebirth#706]
Unable to rename guide bot on Win 11. 

I cannot use Alt-Shift-F4 to rename the guide bot as it just causes an abort game dialog and tries to drop a marker.

**Comment by LordKane1701** [comment]
I want to note this is a self built build done via forking DXX, I have made no code changes as there isnt a up to date build on the site yet, as its still the build from september.

**Comment by vLKp** [comment]
This seems strange.  The game has no code to do this, and the problem does not occur for me on Linux.  I see that @arbruijn opened #707 around the time you filed this, and looking at the SDL documentation for the option enabled in that pull request, it seems like the result you observed is an SDL behavior, though fortunately a tunable one.  Does pull request #707 fix the problem you see?

**Comment by LordKane1701** [comment]
> This seems strange. The game has no code to do this, and the problem does not occur for me on Linux. I see that @arbruijn opened #707 around the time you filed this, and looking at the SDL documentation for the option enabled in that pull request, it seems like the result you observed is an SDL behavior, though fortunately a tunable one. Does pull request #707 fix the problem you see?

Infact he made this pull when I mentioned it in discord, and yes it does, I absorbed that pull into my fork of the repo ran github actions to compile a version and tada, yes it was fixed. 

so yeah it did.

**Comment by vLKp** [comment]
Pull request #707 was merged to `master` yesterday, so based on your remark above, this should now work for you without needing a local patch.  Closing.  Please reopen if you disagree with this resolution.
