### ISSUE TITLE
Secondary weapons based on primary slots (maybe)

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#72]
In multiplayer, for both the host and client:

You are unable to select a secondary weapon unless you have the corresponding primary already. (I.E. in order to select homers, you must have a vulcan cannon. To select proxbombs you have to have a spread cannon etc.)

Smart missiles are the exception...you don't need plasma to select them.

There seemed to occasionally be other minor exceptions, but the general rule is what I said above.

**Comment by Mako88** [comment]
This also results in the secondaries not being dropped on death if the corresponding primary isn't carried.

**Comment by vLKp** [comment]
I do not see this with 6eb724d8724fe35a4cbb61e93dfa88b191168b18 after granting myself all weapons, then ejecting my Vulcan and Gauss cannon.  I can still select both homing and guided missiles.  Does this apply only if the player has never had the corresponding primary?  Does it matter what game host settings are used?

**Comment by Mako88** [comment]
I didn't check having a weapon and then dropping it. I only tested with never having the weapon.

Also this was with 74b66a7f5a6411a829beb962f18b9230f0e86af4

**Comment by Mako88** [comment]
I'm not sure if it matters, but this was tested in D1. There weren't any host-specific settings that seemed to trigger it. Also I forgot to mention that this allows you to select a secondary even if you don't have any (when you have the corresponding primary).

**Comment by vLKp** [comment]
This is D1 specific.  It is a copy/paste error from some refactoring.  Fixed in 3239693c266b9d6f6166cec745bf27319e58bbc8.
