### ISSUE TITLE
Runtime crash: Crashes at random on Multiplayer Games

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [dxx-rebirth/dxx-rebirth#725]
### Environment

**Linux:** Installed from AUR: https://aur.archlinux.org/packages/d2x-rebirth
**Windows:** Installed from official GitHub release.

#### Operating System Environment

**NOTE:** The host player was on ArchLinux, the guest was on Windows 10.

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10 (Version 22H2)

* Linux

Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-arch2-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S UD

**NOTE:** I usually don't take more than 1 week to update my system. Even after updates, this issue was still seen.

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

**Assets:**

descent2.hog:
- Obtained from: GoG
- Size: 7.2 MiB (7,595,079)
- SHA256: f1abf516512739c97b43e2e93611a2398fc9f8bc7a014095ebc2b6b2fd21b703

### Description

Crashes happen at random while playing multiplayer games. I don't know what triggers it.

#### Regression status

I didn't check other versions.

### Steps to Reproduce

**Engines affected:** D2X-Rebirth

This issue happens at random while playing, I don't know how to reproduce. I noticed on Multiplayer games, and I don't remember / know if this happens on Single Player too. Maybe this happens because robots tend to bump each other.

**Error message:**
```
/usr/include/c++/13.1.1/array:202: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = long int; long unsigned int _Nm = 5; reference = long int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [x] Multiplayer cooperative

* Players affected by issue:
  * [x] Game host
  * [x] Game guests

**Comment by vLKp** [comment]
The crash indicates that a standard library sanity check aborted to prevent undefined behavior.  This is a good thing.  The backtrace from the resulting core file is necessary to understand further though.  There are likely many arrays in the game that consist of 5 elements of type `long int`, so seeing only that one of them was accessed improperly is vague.  Seeing the backtrace would show where in the program this failure occurred.  Please post the output of `gdb --batch -ex 'bt full' /path/to/d2x-rebirth --core /path/to/core`, with those paths expanded as appropriate.

**Comment by WilliamWeberBerrutti** [comment]
As mentioned on [This comment](https://github.com/dxx-rebirth/dxx-rebirth/issues/728#issuecomment-1694411928), I intend to check it as soon as possible.

**Comment by vLKp** [comment]
That is good to see.  Closing.
