### ISSUE TITLE
Multiplayer Settings Remembered

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#73]
Two different things regarding this:
1. Last connected IP address should be remembered so it doesn't have to be typed in over and over when manually joining.
2. Duplication of powerups (and powerups granted at spawn) should NOT be remembered as these settings are likely to change every game.

**Comment by vLKp** [comment]
Remembering the IP address would be nice, at least until process restart, and maybe indefinitely if you only ever play with one host.

I can see why you might want to forget powerup settings, but on the other hand, tuning the grants every time would get irritating if you did want to use similar or identical grants often.  I think this would be better addressed by the netgame profiles feature, so that users could save different sets of netgame configurations for a single pilot, then load whichever one applies to the game they want to play this time.  We could also add a set-all/clear-all choice as a shortcut.

**Comment by Mako88** [comment]
Yeah, having different profiles would be ideal, with a way to easily clear everything.

Also, it'd be nice to restructure things just a tad bit (mainly adding space in a couple places throughout the hosting menu) so that it's not so jumbled and it's easier to read.

**Comment by vLKp** [comment]
"Clear all" could be a built-in profile that is always blank and cannot be replaced.

Adding blank space is easy.  Blank space is a text field with no text, but which consumes a line anyway.  Where did you want blank lines added?

**Comment by Mako88** [comment]
OK, here's how I think it should be ordered (for readability):

The main hosting menu is fine, just add a "load profile" option at the top that would open a page similar to the pilot select screen

Advanced menu:

Difficulty:                            -D--------------
Reactor Life:                      -D--------------
Max Time:                         -D--------------
Kill Goal:                           -D--------------
Extra Primaries: None      -D--------------- (When the slider moves "none" changes to "x2" "x3" etc.)
Extra Secondaries: None  -D--------------
Extra Accessories: None   -D-------------
Cap Secondaries: Default    -----D------ (Start with slider in middle. If you go to the left it becomes "x2" "x3" "x4". If you go to the right it becomes "max 6" "max 2" "none".)
Spawn Invulnerable Time: None   -D---------- (As the slider moves "none" changes to "0.5 sec" "1 sec" etc.)

---Space Here---

Set objects allowed...
Set objects granted at spawn...

---Space Here---

[ ] Show All Players on Automap
[ ] Invulnerable When Reappearing
[ ] Bright Player Ships
[ ] Alternate Colors (if we do this at some point)
[ ] All Players Blue (if we do this)
[ ] Allow Realistic Lighting
[ ] Allow Players to Choose Their Colors (if we ever do this)
[ ] Show Enemy Names on HUD
[ ] Disable Friendly Damage

---Space Here---

Packets Per Second (5 - 40)
[_____________________]
Network Port
[_____________________]
[ ] Track this game (Do we need to have the server name? It takes up a lot of space).

**Comment by Mako88** [comment]
Just realized, since the spawn invuln is a slider, we don't need the checkbox anymore. I'll edit my above comment to reflect that when I'm back at a computet

**Comment by vLKp** [comment]
Target host IP address/name, target host port, and local port are now copied aside when a connection is started.  On reopening the dialog, if the copied values are non-empty, they are used instead of the default values.

Please reopen if this is not sufficient.
