### ISSUE TITLE
Macintosh Higher Resolution Cockpit HUD + DOS Sound Effects?

### ISSUE THREAD

**Issue by BigheadSMZ** [dxx-rebirth/dxx-rebirth#730]
So this is something I've been pondering about for a long time now, but so far have not been able to come up with any type of a solution. To put it simply, my goal is to have the cockpit HUD from the mac version of the game because it looks so much better than the DOS version but not lose the sound effects from using the mac version of the game.

DOS: [https://i.imgur.com/dBwpcAQ.png](https://i.imgur.com/dBwpcAQ.png)
Macintosh: [https://i.imgur.com/nG6R88R.png](https://i.imgur.com/nG6R88R.png)

Does anyone have any idea about how I can achieve this? So far I have no idea how it can be done. Using the PC files, you get a low resolution cockpit but sound effects work. Using the macintosh files, you get a high resolution cockpit but sound effects do not work. I was thinking maybe it would be possible to create like a "hybrid" of the PIG/HOG files, but that seems to be beyond my understanding. An alternative solution could be some kind of addon like the "Hires Pack" found here ([https://www.dxx-rebirth.com/addons/](https://www.dxx-rebirth.com/addons/)) but again, I have no idea how to create this (.dxa) format or where to even begin. Not sure why that pack does not include a better cockpit as this issue wouldn't even exist, it includes all the other mac textures. Perhaps it would be possible to maybe inject the texture over the original like something with Special K that hashes textures and injects them with a replacement, but that seems overkill for this situation.

So I am here, because this seems like the only place I can find someone knowledgeable enough to come up with some kind of solution. It would be fantastic to have a "definitive" version of Descent that has all the features: higher resolution, best textures, highest quality music, etc. etc. But currently something has to be sacrificed, cockpit or sound effects, and in 2023 there has to be a way to have our cake and eat it too. So... any ideas?

**Comment by vLKp** [comment]
`dxa` files are just `zip` with a special extension, so that the game does not scan every random `zip` file you might happen to leave in its data area.  However, dxa files can only override files that are opened by name, so some game assets cannot be replaced through use of a dxa file.

As I read the code, `cockpit_bitmap` is only ever populated by reading sections of internal game data files, so supplying an alternate cockpit graphic in a dxa file would be ignored, at least with the code as it is today, because the cockpit is not a named file.  It is a slice of bytes from a different, larger file.  If you want this to work without a code change, then you probably need a replacement for the game's data files.  If a code change is acceptable, it is probably not that hard to add a branch that replaces the built-in cockpit with one loaded from a named external file.

**Comment by Kreeblah** [comment]
@BigheadSMZ - There are some DXA files that add the missing DOS assets into the Mac version, including missing graphics, MIDI, and sound effects.  The ones in question are d1mac-gfx.dxa, d1mac-midi.dxa, and d1mac-sfx.dxa.  They should be included in the Windows installer (not the zip file) linked from the DXX Rebirth site, or directly from the Github project that the installer is built from at https://github.com/Mako88/dxx-rebirth-installer/tree/master/include/Addons

To use them, you need a copy of the Mac version of Descent (the Mac versions of the HOG and PIG files) and then the DXA files add in the additional assets when placed alongside them in the same directory, so you end up with a copy that has the higher-resolution cockpit, etc., while still having the sound effects and such from the DOS version.

**Comment by BigheadSMZ** [comment]
Wow thank you so much, this is exactly what I was looking for. Yeah I was using the zip from the downloads page, I didn't know the installer included things that were missing from the archive. I usually tend to stick with "official" stuff, and the installer was listed as 3rd party. And throw in the fact I prefer a portable folder over an installation. With all that combined, chances I would have ever tried the installer are close to 0%...

Tested it out and yes, this is amazing. Exactly what I always dreamed of. Just out of curiosity, what is the "uud2sp.dxa" addon?

**Comment by Kreeblah** [comment]
The funny thing is that I can't remember how I found out about the differences in the installer vs. the ZIP file in the first place.  I run DXX Rebirth on a Mac, not Windows, so I don't even have a use for the builds on the official site at all, let alone the installer.  But, I've been using those DXAs for a while, and they really do feel like the definitive Descent 1 experience to me.

As for the other DXA, it seems to be an older version (somebody in the replies mentions it's 1.1, whereas 1.4 is current) of this, for D2X: https://www.descentbb.net/viewtopic.php?t=21386  I haven't really checked it out, though, to see how well it works.

**Comment by BigheadSMZ** [comment]
For sure, this definitely completes the "definitive experience" that I was hoping for. The Mac version was always superior to the DOS version, its a shame the improvements never got ported back at any point. But at least we have dxx-rebirth now to modernize the experience even more, and with these mods the definitive edition is now possible. I got rid of my old macintosh probably 20 years ago and haven't owned an apple computer since, so it's been awhile since I was able to play the "good" version at least with sound. Getting the mac files off disk was far from an easy experience but not impossible (through emulation). But yeah, thanks again. I've been really enjoying it now that I can hear those satisfying laser shots and explosions. :)

**Comment by JeodC** [comment]
@BigheadSMZ where does one find these mac files in 2024? The steam depot appears to have just coped them from DOS.

**Comment by Kreeblah** [comment]
@JeodC - As far as I know, the only reliable way is to extract them from a CD copy of the MacPlay port of Descent through something like SheepShaver.  I got mine off of eBay.

The SHA256 sums of the HOG and PIG files (the only two files you need to extract) are:

```
d0ab72fda672ac9d751d24899f96ac14eb1720386cf2b0226a5add71543c4339  descent.hog
9eb232c9da830309b2d3a1de75713f6155c62215cd867f4570536180af31f299  descent.pig
```
