### ISSUE TITLE
Build failure: build with opengl=0 and no GL headers available

### ISSUE THREAD

**Issue by mikrosk** [dxx-rebirth/dxx-rebirth#731]
Just a reminder of https://github.com/dxx-rebirth/dxx-rebirth/pull/699 which I accidentally closed it before resolution.

I have a patch for it but according to https://github.com/dxx-rebirth/dxx-rebirth/pull/699#issuecomment-1403017263 there's a cleaner solution available.

**Comment by vLKp** [comment]
I made several changes in this area to remove inclusions of OpenGL headers on the SDL-only path.  However, I did not specifically test the build on a system with no OpenGL headers installed.

As a general caution, presently the game does not support SDL2 with `opengl=0`.  I have seen increasing reports that SDL1 support is troublesome on modern systems, and that projects should move to using SDL2.  As a result, it is likely the game will move to SDL2-by-default at some point within the next months.  Barring further work, at that point, `opengl=0` builds will no longer be usable.

**Comment by mikrosk** [comment]
I pulled latest master and tried again. Compilation still fails in `config.cpp`:

```
In file included from common/include/ogl_init.h:21,
                 from similar/main/config.cpp:44:
common/include/d_gl.h:21:21: fatal error: GL/gl.h: No such file or directory
   21 | #           include <GL/gl.h>
      |                     ^~~~~~~~~
compilation terminated.
scons: *** [build/similar/main/.d1x-rebirth.config.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
        build/similar/main/.d1x-rebirth.config.o
Failed command list:
 m68k-atari-mintelf-g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -m68020-60 -fomit-frame-pointer -D__STDC_LIMIT_MACROS -Wno-error=format-truncation -funsigned-char -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -Wno-dangling-reference -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild -I/home/mikro/gnu-tools/m68000/m68k-atari-mintelf/sys-root/usr/include -I/home/mikro/gnu-tools/m68000/m68k-atari-mintelf/sys-root/usr/include/SDL -Id1x-rebirth/main "similar/main/config.cpp" -o "build/similar/main/.d1x-rebirth.config.o"
```
compiled with `scons host_platform=freemint host_endian=big opengl=0 screenshot=none sdlimage=0 sdlmixer=0 verbosebuild=1 CHOST=m68k-atari-mintelf`.

If keeping SDL1 compatibility (even disabled by default) wont be burden, personally I would appreciate the possibility to use it. :)

**Comment by vLKp** [comment]
It looks like I missed pushing at least one commit related to this.

SDL1 will likely become a burden at some point.  Making SDL2 work without OpenGL may be the better path forward, but I have not tried to determine how difficult that would be.

**Comment by mikrosk** [comment]
Indeed, the close relationship between hardware acceleration and SDL2 is the reason why many retro projects still stick to SDL1.

**Comment by vLKp** [comment]
I believe the above commit resolves this.  With it applied, I can now build with `opengl=0` and `/usr/include/GL` empty.  Without it, the `opengl=0` build fails with `/usr/include/GL` empty, as shown in https://github.com/dxx-rebirth/dxx-rebirth/issues/731#issuecomment-1753593218 .  If you still see problems, please reopen.

Is SDL2 really not usable on platforms without OpenGL acceleration?  I thought I had skipped the no-GL SDL2 configuration with the idea that it was not worth the effort at the time, not because it was impossible to do.

**Comment by mikrosk** [comment]
Confirmed, thanks!

As for OpenGL-less SDL2 changes, frankly, I don't know. I've just seen other retro projects being quite hesitant  to abandon it.

Btw I'm very keen of your source base. It is a very good test case for our new m68k toolchain. Some of your more recent changes triggered an [internal gcc error.](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112712) :-)
