### ISSUE TITLE
Runtime crash: Mission directories with very long names will crash the game after opened from in-game menu

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [dxx-rebirth/dxx-rebirth#736]
### Environment

Git Commit: 3ad507fad88f7475751e2ca94d911c97c62cbc65

#### Operating System Environment

Operating System: Arch Linux 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.9-arch2-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S UD

#### CPU environment

x86\_64 (64-bit AMD)

#### Game environment

descent2.hog:

- Obtained from: GoG
- Size: 7.2 MiB (7,595,079)
- SHA256: f1abf516512739c97b43e2e93611a2398fc9f8bc7a014095ebc2b6b2fd21b703

### Description

Mission directories with very long names (like 60 characters) will crash the game after opened from in-game menu. This happens for both Descent 1 and 2.

#### Regression status

Iirc I tested on this version too: [dxx-rebirth_20220929](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220929-src.tar.xz)

### Steps to Reproduce

Steps to reproduce:

- Launch the game
- Go to New Game or Multiplayer, then Host Game and try to open a directory with a very long name
- Crash!

and (if you had played a map in a directory, renamed the directory to have a long name and restarted the game)

- Launch the game
- Go to New Game or Multiplayer, then Host Game
- Crash!

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player and Multiplayer

**Comment by vLKp** [comment]
Confirmed, but only if there are at least 2 missions in the long directory.  If there is at most one, then the code which flattens out the directory structure makes it as if the long directory does not exist, so no error occurs.

When an error occurs, it is:
```
#8  0x000055555556f363 in dcx::gr_init_sub_bitmap (bm=..., bmParent=...,
    x=<optimized out>, y=<optimized out>, w=<optimized out>, h=h@entry=298)
    at common/2d/bitmap.cpp:135
#9  0x000055555556fdbc in dcx::gr_init_sub_canvas (n=..., src=...,
    x=<optimized out>, y=<optimized out>, w=<optimized out>, h=h@entry=298)
    at common/2d/canvas.cpp:68
#10 0x0000555555576e87 in dcx::window::window (this=this@entry=0x55555667a160,
    src=..., x=<optimized out>, y=<optimized out>, w=<optimized out>,
    h=h@entry=298) at common/arch/sdl/window.cpp:33
#11 0x000055555563b890 in dcx::listbox::listbox (
    this=this@entry=0x55555667a160, citem=citem@entry=0,
    nitems=<optimized out>, item=<optimized out>, title=..., canvas=...,
    allow_abort_flag=1 '\001') at similar/main/newmenu.cpp:1687
#12 0x000055555560cc63 in (anonymous namespace)::mission_menu::mission_menu (
    this=0x55555667a160, rml=std::vector of length 2, capacity 2 = {...},
    count_name_pointer_strings=<optimized out>, name_pointer_strings=...,
    title_parameter=...,
    when_selected=0x5555556016a4 <d2x::(anonymous namespace)::do_new_game_menu()>, parent=0x555556d30e30, default_item=0, canvas=...)
    at similar/main/mission.cpp:1268
#13 0x000055555560d00e in (anonymous namespace)::mission_menu::mission_menu (
    this=this@entry=0x55555667a160,
    rml=std::vector of length 2, capacity 2 = {...},
    count_name_pointer_strings=3, name_pointer_strings=...,
    message=<optimized out>,
    when_selected=0x5555556016a4 <d2x::(anonymous namespace)::do_new_game_menu()>, parent=0x555556d30e30, default_item=0, canvas=...)
    at similar/main/mission.cpp:1259
#14 0x000055555560d227 in (anonymous namespace)::subdirectory_mission_menu::subdirectory_mission_menu (this=0x55555667a160) at similar/main/mission.cpp:1306
```

**Comment by vLKp** [comment]
I believe the above commit resolves the problem.  I reproduced the problem without it, and with that commit applied, the game can correctly show the menu list.  Please reopen if you still see problems.
