### ISSUE TITLE
REQ: Play d1x music in d2x engine

### ISSUE THREAD

**Issue by JeodC** [dxx-rebirth/dxx-rebirth#740]
Currently when playing d2x-rebirth, only the d2xr-sc55-music.dxa file is loaded. This causes no music to be played when one runs D1 missions from a shared hogfile directory. Is it possible to combine the .dxa files into one or otherwise get music working for both games under the same d2x engine?

**Comment by vLKp** [comment]
`dxa` are just zip files with a special extension, so that the game does not pick up zip files not intended for it.  You can have multiple `dxa` files present, and they will all be loaded.  What music were you expecting would play?

**Comment by JeodC** [comment]
If I run d2x-rebirth it will only use the d2x dxa file even if I load First Strike missions while d1x dxa is present.

**Comment by vLKp** [comment]
Yes, I understood that.  If you need help, please describe the problem in enough detail that I can reproduce it from a clean environment.  In particular:

- Tell what version of the game you are running
- Tell where to get any non-builtin files, such as the music files.  I could guess that these are the ones from the website, but I want to confirm that I am using the same inputs you used.
- Tell where those files are in the game's data hierarchy
- Tell any non-default player settings required to make the game use D2 music in D2 missions

**Comment by JeodC** [comment]
- v0.61

- Just the addons from the website

- In the data folder

- Default settings are used

The expected behavior is that the game will recognize when Descent 1 missions are being played and use d1xr-sc55-music.dxa. Instead, since the game either plays the wrong track (D2's briefing over D1's briefing) or does not play a track altogether.

**Comment by JeodC** [comment]
This is only occurring on Linux aarch builds. Windows build works fine. Linux build I'm working with is _v0.61 0.60.0-beta2-1223-GCF888DF4598_

**Comment by vLKp** [comment]
If this only fails on aarch systems, there is little I can do to help you.  I only test on x86_64-pc-linux-gnu, and have no aarch hardware on which to run the game.

I do not seem to have a commit starting `CF888DF4598` here.  However, your code appears to be badly outdated:

```
$ git describe --long github/master --tags
0.60.0-beta2-2701-ga6161c031
```

That suggests the current tip of `master` is (2701 - 1223) = 1478 commits ahead of the commit you are using, which would put you somewhere around 1d5afd34ceb97104e97c6c795d2c53fa1f21e669, from January 2021.  What is the output of `git log -5 HEAD --not 1d5afd34ceb97104e97c6c795d2c53fa1f21e669` in the working copy where you built the game that is described as `0.60.0-beta2-1223-GCF888DF4598`?

**Comment by JeodC** [comment]
It's definitely outdated. Someone the remnants of a build from AnberPorts (2021) and tried to bring it to PortMaster in 2022. I picked up the remnants of that and here I am.

Was wrong about aarch by the way. I'm working with Ubuntu 20.0.4.

**Comment by JeodC** [comment]
D2X-Rebirth has been updated to v0.61 0.60.0-BETA2-2701-GA6161C031A5B and d1x-sc55-music.dxa seems to still not be recognized in d2x when playing first strike. Compiled on native aarch64 via chroot with ```scons sdl2=1 sdlmixer=1 opengl=1```. On my windows device, the same compiled source only shows v0.61 for the version info.

**Comment by vLKp** [comment]
I was not aware of the AnberPorts or PortMaster projects.  I was never contacted about anyone porting Rebirth to them, and have no knowledge of what they may have done with the code.  I am curious what additional commits they made, and why.

---

The full version string is only available if the build system can find `git` and is given a `git` working copy (or the code is from a `git archive` that expanded the relevant placeholders in `SConstruct`).  Otherwise, you get only the brief and rarely updated MAJOR/MINOR numbers that are embedded in `SConstruct`.

---

The most recent describe string looks like you are now using current code, which is good.  I generally provide limited support for old code.  It is strange that this works in Windows, since the code is mostly the same.

**Comment by JeodC** [comment]
Well, we compiled from this repo, so no dxx-rebirth modifications. So the game runs in aarch64:
```ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0```

But when playing the first strike mission (descent.hog) in d2x-rebirth, while having d1x-music-sc55.dxa in the data folder, no music is played. This isn't a big deal personally since PortMaster can use d1x-rebirth for that mission, but I am curious as to why a Windows machine would not have this issue. The only thing I can think of is a stripped binary. Oh well.

**Comment by vLKp** [comment]
Yes, the most recent description string matches a compilation from this repository.  However, the earlier description string of `0.60.0-beta2-1223-GCF888DF4598`, when you used code from January 2021, seems to have at least a HEAD commit that is not from this repository.  That is why I requested the output of `git log`, to try to understand how significantly it had deviated.

Stripping should have no effect on functionality.  That is only the removal of debug symbols.

Does this work for you on x86_64-pc-linux-gnu, and only fail on aarch64?  Or is the music non-functional on both aarch64 and x86_64 Linux?

**Comment by JeodC** [comment]
I don't know what changes were made from the 2021 compile--that's before my time on the project, and I don't have access to any custom forks they may have used.

Have not tested on x86-64-pc-linux-gnu. I can see if someone can try it. Would you like me to keep the issue open?

**Comment by JeodC** [comment]
An update:

The theory is correct. I added a soundfont.sf2 file and pointed d2x-rebirth to it in the descent2.sh file:
```
export SDL_FORCE_SOUNDFONTS=1
export SDL_SOUNDFONTS="$GAMEDIR/lib/soundfont.sf2"
```

A d2x dxa file was also present, and was correctly used for Descent 2 missions and the menu. On loading Descent: First Strike, the .hmp music took priority.

I am not sure how or if you would want to rectify this. I would consider it a feature request, not a bug.

**Comment by vLKp** [comment]
The engine already has a number of special case rules around the Descent 1 emulation.  Adding more would be reasonable.  Internally, there are two paths that might be taken.  One path would be to recognize the use of `Descent: First Strike` and do this override only for that mission.  The other would be to use the special path for any Descent 1 mission, in which case missions from Levels of the World and any other user-made custom Descent 1 missions would be impacted.

**Comment by JeodC** [comment]
I imagine the second path would be preferable, but it does provide for a somewhat slippery slope in that there may eventually be no use for the d1x-rebirth build any longer.

**Comment by vLKp** [comment]
Although we are not particularly close to that point, I have always thought it would be nice if we could reach the point that there is no need for a `d1x-rebirth` build, by reaching the point that a single binary can faithfully reproduce the Descent behavior in Descent 1 missions and the Descent 2 behavior in Descent 2 missions.  Combining the source trees just after 0.58.1 was an early step in this process.  Maintaining the source for both games in a combined tree makes it easier to do an improvement that affects both games at once, and makes it easier to see where the game logic differs.
