### ISSUE TITLE
Descent 1 build fails: DSO missing from command line

### ISSUE THREAD

**Issue by olivier1980** [dxx-rebirth/dxx-rebirth#760]
Using gcc-13/g++13, I get the following output: 

```
LD  d1x build/d1x-rebirth/d1x-rebirth
/usr/bin/ld: build/similar/main/.d1x-rebirth.game.o: undefined reference to symbol '_ZTVN10__cxxabiv121__vmi_class_type_infoE@@CXXABI_1.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Full log: 
https://pastebin.com/3u1cDmAs

**Comment by vLKp** [comment]
Rebirth is a C++ program, so you must use a C++ compiler to build it.  I can reproduce the shown undefined reference error if I force the use of a C compiler for linking.  Set `CXX=g++13`, rather than `CXX=gcc-13` as you did in the pastebin.

**Comment by olivier1980** [comment]
Thanks, I didn't realize that..build works now

**Comment by vLKp** [comment]
[Test whether C++ linker can link a program with a virtual function](/dxx-rebirth/dxx-rebirth/commit/d7ea47e6bbde0428e46ae75e59ac622b3fe8ff36) adds a configure time test to detect this mistake, and report the compiler as non-functional.  Hopefully, this will produce a better user experience than letting the final link fail.
