### ISSUE TITLE
Runtime bug: left/right movement controls also cause inadvertent vertical turning

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#766]
### Environment

b5ca993d71739e9542fafe13d7332cc6ce008cc5

SDL2 build

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [ ] Mac OS X 10.14
  * [ ] Mac OS X 10.15

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [x] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Any D1/D2 mission

### Description

Turning the ship either left or right also causes the ship to turn up or down somewhat. For example, alternating between left and right inputs causes the ship to eventually turn up.

Both mouse and keyboard are affected.

#### Regression status

This did not happen on my previous build, which was long ago (at least a year). I'll try to narrow it down further.

### Steps to Reproduce

Try to turn either left or right, the movement will feel off. Alternating between left and right will cause a noticeable drift up/down, which should not happen.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by ziplantil** [comment]
bisecting landed me on commit d32ee5fefaaf244fb4365ddefec5005f6748e8f1

**Comment by vLKp** [comment]
After rereading that commit, I see a potential problem.  The last hunk was reloading `obj.mtype.phys_info.turnroll`, and now uses a local variable that was initialized from `obj.mtype.phys_info.turnroll` earlier in the function.  However, `set_object_turnroll` may, depending on the object's state, modify `obj.mtype.phys_info.turnroll`, causing the cached local to go stale.  The old code would use the value modified by `set_object_turnroll`; the new code ignores any such change.  I will experiment with reloading from the object to see if that resolves the reported problem.

**Comment by ziplantil** [comment]
It does indeed seem that re-initializing `turnroll` after the `set_object_turnroll` call fixes the issue.

**Comment by vLKp** [comment]
I don't know if specific circumstances are required to trigger it.  I found the problem via code inspection after you identified a specific commit as bad.  I have seen some indications recently that few people actually use the code I work on, so it is possible that no one else has reported it because you're the only person both playing recent builds and filing issues.  That would be discouraging.  It's also possible that someone else noticed it, but failed to recognize it as a reportable issue.  The problem only occurs if `set_object_turnroll` modifies the object's `turnroll` member, so perhaps other people are playing in a way that this function computes a value that is almost or exactly equal to the stale cached value, causing a much smaller error in ship movement.

**Comment by vLKp** [comment]
The above commit should resolve this in `master`.  Please reopen if you see further problems.

**Comment by AlumiuN** [comment]
> I have seen some indications recently that few people actually use the code I work on, so it is possible that no one else has reported it because you're the only person both playing recent builds and filing issues.

I think the majority of users don't build Rebirth for themselves, they just used the pre-built binaries, so the lack of those for a while will reduce the number of people who are likely to see it somewhat.

**Comment by JeodC** [comment]
The most recent dxx-rebirth builds distributed via PortMaster (I don't think many use rebirth on pc these days) are used on devices with analog sticks. This sort of issue would more likely be attributed to dead zones than a code problem.
