### ISSUE TITLE
Left Click on Player Select Doesn't Close Window

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#77]
This happens most of the time.

**Comment by vLKp** [comment]
I do not see this happen.  If I click on a valid pilot name, or on the `<Create New>` entry, the game responds correctly every time I have tried it.  If I click on an empty area, it does not respond, but that is correct, because a choice must be made before you can continue.

**Comment by Mako88** [comment]
Yeah, I can't duplicate it either...the same person who had the energy bug is the one who reported it, so maybe it has something to do with that player profile?

**Comment by vLKp** [comment]
That is the dialog to choose which player profile to use, so it is possible.  When the window does not close, what happens?  Does the game hang?  Can the profile be chosen by using the keyboard?  Can it be chosen by using left clicks if the user repeats the attempt a few times?

**Comment by Mako88** [comment]
The game doesn't hang or anything, and the keyboard works to do it. The guy said that he thinks sometimes clicking multiple times works, but he's not sure. I'll have to wait till I'm with him when it happens again to get more info.

**Comment by Mako88** [comment]
I talked to the guy, and he can no longer reproduce this bug. Closing.
