### ISSUE TITLE
Website host 0.58 binaries instead of latest

### ISSUE THREAD

**Issue by Daivuk** [dxx-rebirth/dxx-rebirth#779]
Mystery solved. Looks like its a problem with the web site: https://www.dxx-rebirth.com/
Somehow it got reverted to a previous version back to 0.58
The binary cannot be found anywhere other than web archives.
From this post: https://www.reddit.com/r/descent/comments/146grks/descent_getting_started_guide/
The mirror file can be found here: https://double-jump.net/Files/dxx-rebirth_20220929-win.zip
May I suggest doing builds and binary releases on github.

I've edited this issue and its title to reflect the real problem.

~Hi, I haven't played this in at least 4 years. I am now unable to bind axis to actions. For example: Bind Right-Trigger on an Xbox controller to Shoot.~

~This was fixed by me a while ago on this commit: https://github.com/dxx-rebirth/dxx-rebirth/commit/74ef8b02e6a20c24f6713d8126ccb5dc2d2c6039~

~Maybe that commit was overridden in a bad merge a few years later? Or it was decided that this wasn't a good change? It makes it impossible to play with a controller without those quality of life feature.~

**Comment by Daivuk** [comment]
Oh, I should mention that I took the binaries from here: https://www.dxx-rebirth.com/

**Comment by vLKp** [comment]
Sometime around the start of 2024, Zico replaced the previous website with what you see now, and in the process removed both the post-0.58 binaries and various other extras, such as shareware files.  This replacement led to issue #747, and was referenced in passing in https://github.com/dxx-rebirth/dxx-rebirth/pull/765#issuecomment-2028454085 .

---

The project does have builds automatically created and published through the GitHub Actions system.  See https://github.com/dxx-rebirth/dxx-rebirth/actions .

**Comment by Daivuk** [comment]
Ok thank you for the information, closing this then. It's redundant.
