### ISSUE TITLE
[Suggestion] Command-Line Option to Set Main Dir

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#79]
If I'm running two versions of Rebirth (or Retro and Rebirth) they both try to use .d*x-rebirth for everything (data, player files, missions, etc.)

It would be nice to be able to tell it to look in a different place for all of that. Or really it'd be really nice to set Data dir (we already have that), Players dir, Missions dir, and Demos dir separately via command line. That way Retro and Rebirth could share the missions and data dir, but have separate places for Players, Demos and Configuration files.

**Comment by vLKp** [comment]
Although not a command line option, this is supported via an environment variable as of [Add $D*X_REBIRTH_HOME and $REBIRTH_HOME to override default path](/dxx-rebirth/dxx-rebirth/commit/03b57abff0d8447f6a5ff0954b45894aa7da9c65) (2015-10-18).  If either of those variables is set, they override the default of `~/.d1x-rebirth/` / `~/.d2x-rebirth/`.

**Comment by Mako88** [comment]
I think that's good enough :) Closing.
