### ISSUE TITLE
Linux .AppImage versions won't pick up addon files (missiosn, demos, etc)

### ISSUE THREAD

**Issue by DarthZiplock** [dxx-rebirth/dxx-rebirth#793]
I install the game data and .AppImage file to ~/.d1x-rebirth as that's the only place it can find the main .hog files, but no matter where I put additional .hog files or demo files the game refuses to see them. Missions folder, game root folder, nothing works.

Same goes for D2. It will not detect addon missions or demos.

Mac and Windows versions work just fine.

**Comment by vLKp** [comment]
The Windows, Mac, and Linux builds are all drawn from the same code, and generally should work the same way.  AppImage artifacts are the result of an outside contribution.  I do not use AppImage for development or testing.

If you run the game with `-debug` to increase its verbosity, what does it output?

**Comment by DarthZiplock** [comment]
> The Windows, Mac, and Linux builds are all drawn from the same code, and generally should work the same way. AppImage artifacts are the result of an outside contribution. I do not use AppImage for development or testing.
> 
> If you run the game with `-debug` to increase its verbosity, what does it output?

I gave up on it honestly. The furthest I got was executing the .appimage via terminal to find out that it was only looking in a few specific folders for the game data (it said something like "no .hog file found, look in ~/.d1x-rebirth or ./data")

After trying to get it to find player profiles and missions with their respective command lines, I tried just running the Windows version via Wine and that worked completely flawless so that's what I'm doing now.

**Comment by vLKp** [comment]
I suspect this is some weirdness with AppImage presenting a modified view of the filesystem as part of some sandboxing attempt.  However, as I do not have the ability to run AppImage binaries, and you gave up on it, there is no one to investigate further.  Therefore, closing.  If you decide to revisit this issue, please reopen.

The game writes its player files to one of the directories it searches.  Adding the requisite files to the directory where the `.plr` and `.plx` files are written should work.
