### ISSUE TITLE
Can't load missions from subdirectory

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#87]
I think I reported this on the forum, but I don't remember. I'm gonna put this here anyway as a personal reminder to double check and get back with more info if, in fact, it hasn't been fixed yet.

**Comment by vLKp** [comment]
This was reported on the forum.  I believe this is fixed by [Simplify add_missions_to_list](https://github.com/dxx-rebirth/dxx-rebirth/commit/ddf1ded74c7ec20b287a9670eaa0b9335b76c90a).
