### ISSUE TITLE
Autoselect after firing

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#97]
Add this as an option in the misc options. If you pick up a weapon while firing that should be autoselected, it won't autoselect until you let off the fire button.

NOTE: Be sure that fusion actually fires before the autoselect kicks in.

**Comment by Mako88** [comment]
If it's not too hard, it'd be really nice to have this in 0.60, because with "Don't autoselect while firing" enabled, but without an "Autoselect after firing", what happens very often is you're not aware that you have weapons because you didn't notice that you picked them up while shooting, and it never autoselects. This is especially true with secondaries...if you hold down your secondary fire key and happen to pick something up, you won't realize that you have it.

**Comment by vLKp** [comment]
I never have that happen, but maybe my choice of HUD influences whether I notice new weapons.  [Add new autoselect-while-firing mode: "when firing stops"](https://github.com/dxx-rebirth/dxx-rebirth/commit/7da64d37825e1d32b4672eea86390ef941bdaad5) is based on your pull request.  I think it will address what you want.
