### ISSUE TITLE
Spawn Invuln time slider

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#99]
This is bundled in issue #80 but I figured I'd add it as a separate issue for clarity.

Add a slider to the advanced hosting menu that would set the amount of time a player is invulnerable on spawn. It should go from 0 to 2 seconds in 0.5 second increments.

**Comment by vLKp** [comment]
Implemented in 2a62fa7d7817b50f0ba3bf2f1c1282e908e956ea.
